In [12]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 338, done.
remote: Counting objects: 100% (67/67), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 338 (delta 40), reused 22 (delta 22), pack-reused 271 (from 2)
Receiving objects: 100% (338/338), 2.70 MiB | 6.87 MiB/s, done.
Resolving deltas: 100% (175/175), done.
/content/vaipe-contextual-pill-recognition

In [2]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

tải dataset

In [3]:
!pip install -q kagglehub

import kagglehub
from pathlib import Path

dataset_path = kagglehub.dataset_download("tommyngx/vaipepill2022")

print("Dataset path:", dataset_path)
print("Exists:", Path(dataset_path).exists())

Downloading to /root/.cache/kagglehub/datasets/tommyngx/vaipepill2022/1.archive...

100%|██████████| 25.2G/25.2G [04:25<00:00, 102MB/s]

Extracting files...

Dataset path: /root/.cache/kagglehub/datasets/tommyngx/vaipepill2022/versions/1
Exists: True

In [4]:
from pathlib import Path
import shutil

ZIP_PATH = "/content/drive/MyDrive/VAIPE_FINAL_BACKUP/processed_pika_best.zip"

print("Zip exists:", Path(ZIP_PATH).exists(), ZIP_PATH)

!rm -rf /content/processed_pika_best
!rm -rf /content/_processed_pika_unzip
!mkdir -p /content/_processed_pika_unzip

!unzip -q "$ZIP_PATH" -d /content/_processed_pika_unzip

tmp = Path("/content/_processed_pika_unzip")

print("Extracted top-level items:")
for p in list(tmp.glob("*"))[:30]:
    print(p)

graph_files = list(tmp.rglob("graph_labels.json"))
print("\nFound graph_labels.json:", graph_files[:5])

if len(graph_files) == 0:
    raise FileNotFoundError("Không tìm thấy graph_labels.json trong processed_pika_best.zip")

src_root = graph_files[0].parent
print("Detected processed root:", src_root)

shutil.copytree(src_root, "/content/processed_pika_best")

print("\nDone.")
print("Data root:", Path("/content/processed_pika_best").exists())
print("Graph labels:", Path("/content/processed_pika_best/graph_labels.json").exists())
print("Graph PMI:", Path("/content/processed_pika_best/graph_pmi.npy").exists())

Zip exists: True /content/drive/MyDrive/VAIPE_FINAL_BACKUP/processed_pika_best.zip
Extracted top-level items:
/content/_processed_pika_unzip/graph_labels.json
/content/_processed_pika_unzip/graph_pmi.npy
/content/_processed_pika_unzip/pill_crops
/content/_processed_pika_unzip/best_pika_metadata.csv

Found graph_labels.json: [PosixPath('/content/_processed_pika_unzip/graph_labels.json')]
Detected processed root: /content/_processed_pika_unzip

Done.
Data root: True
Graph labels: True
Graph PMI: True

In [5]:
import pandas as pd
from pathlib import Path

csvs = {
    "train": "/content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv",
    "val": "/content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv",
    "test": "/content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv",
}

for name, csv_path in csvs.items():
    df = pd.read_csv(csv_path)

    print("\n====================")
    print("SPLIT:", name)
    print("====================")
    print("CSV rows:", len(df))
    print("Labels:", df["pill_label"].nunique())

    for col in ["pill_crop_path", "prescription_image_path"]:
        exists = df[col].apply(lambda p: Path(str(p)).exists())
        print(f"{col} existing:", int(exists.sum()), "/", len(df))
        print(f"{col} missing:", int((~exists).sum()))

        if (~exists).sum() > 0:
            missing_df = df[~exists]
            show_cols = [c for c in [col, "pill_label", "prescription_key", "source_split"] if c in missing_df.columns]
            print("Missing examples:")
            print(missing_df[show_cols].head(5).to_string(index=False))

====================
SPLIT: train
====================
CSV rows: 23189
Labels: 108
pill_crop_path existing: 23189 / 23189
pill_crop_path missing: 0
prescription_image_path existing: 23189 / 23189
prescription_image_path missing: 0

====================
SPLIT: val
====================
CSV rows: 4974
Labels: 89
pill_crop_path existing: 4974 / 4974
pill_crop_path missing: 0
prescription_image_path existing: 4974 / 4974
prescription_image_path missing: 0

====================
SPLIT: test
====================
CSV rows: 4550
Labels: 82
pill_crop_path existing: 4550 / 4550
pill_crop_path missing: 0
prescription_image_path existing: 4550 / 4550
prescription_image_path missing: 0

######
Tái hiện lại bản baseline PIKA từ đầu trước

M17 sẽ làm nhiệm vụ tái hiện paper

M17 nên có các phần:

1. Dataset split theo prescription_key
2. Graph xây từ train split
3. Graph embedding riêng
4. Pill visual encoder
5. Projection visual feature sang graph embedding space
6. Context attention
7. Pseudo classifier / auxiliary loss
8. Train theo 2 stage nếu có thể

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh build_m17_pika_graph_embeddings.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 250, done.
remote: Counting objects: 100% (128/128), done.
remote: Compressing objects: 100% (106/106), done.
remote: Total 250 (delta 79), reused 22 (delta 22), pack-reused 122 (from 1)
Receiving objects: 100% (250/250), 2.59 MiB | 10.72 MiB/s, done.
Resolving deltas: 100% (134/134), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 14K May  4 15:17 build_m17_pika_graph_embeddings.py

In [ ]:
import os

M17_GRAPH_DIR = "/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts"
os.makedirs(M17_GRAPH_DIR, exist_ok=True)

print("M17 graph output dir:", M17_GRAPH_DIR)

M17 graph output dir: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python build_m17_pika_graph_embeddings.py \
  --train_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv \
  --output_dir /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts \
  --label_col pill_label \
  --group_col prescription_key \
  --context_col context_labels \
  --embedding_dim 64 \
  --min_cooccur 1 \
  --self_loop_value 1.0 \
  2>&1 | tee /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/build_graph_log.txt

/content/vaipe-contextual-pill-recognition
=== M17 PIKA GRAPH EMBEDDING BUILDER ===
Train CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv
Output dir: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts
Label col: pill_label
Group col: prescription_key
Context col: context_labels
Include context labels: False
Embedding dim: 64
Min cooccur: 1
Self loop value: 1.0

Train rows: 23189
Train groups: 597
Train labels: 108
Num classes: 108
Min label: 0
Max label: 107

Valid prescription groups: 597
Graph cooccur shape: (108, 108)
Non-zero cooccur entries: 1308
Group size distribution:
  1 labels/group: 34 groups
  2 labels/group: 174 groups
  3 labels/group: 200 groups
  4 labels/group: 137 groups
  5 labels/group: 46 groups
  6 labels/group: 6 groups

PMI shape: (108, 108)
PPMI shape: (108, 108)
Embeddings shape: (108, 64)

Saved artifacts:
/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/build_graph_log.txt
/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_class_stats.csv
/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_cooccur.npy
/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_edges.csv
/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_embeddings.npy
/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_labels.json
/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_pmi.npy
/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_ppmi.npy
/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_raw_pmi.npy
/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/idx_to_label.json
/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/label_to_idx.json
/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/m17_graph_config.json
/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/m17_graph_summary.txt
/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/prescription_label_sets.csv

Done.

In [ ]:
from pathlib import Path
import json
import numpy as np
import pandas as pd

out_dir = Path("/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts")

files = [
    "graph_labels.json",
    "label_to_idx.json",
    "idx_to_label.json",
    "graph_cooccur.npy",
    "graph_pmi.npy",
    "graph_ppmi.npy",
    "graph_embeddings.npy",
    "graph_edges.csv",
    "graph_class_stats.csv",
    "m17_graph_config.json",
]

for f in files:
    p = out_dir / f
    print(f, "=>", p.exists(), p)

labels = json.load(open(out_dir / "graph_labels.json", "r", encoding="utf-8"))
pmi = np.load(out_dir / "graph_pmi.npy")
emb = np.load(out_dir / "graph_embeddings.npy")

print("\nNum labels:", len(labels))
print("PMI shape:", pmi.shape)
print("Embedding shape:", emb.shape)

edge_df = pd.read_csv(out_dir / "graph_edges.csv")
class_df = pd.read_csv(out_dir / "graph_class_stats.csv")

display(edge_df.head(20))
display(class_df.sort_values("instance_count").head(20))

graph_labels.json => True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_labels.json
label_to_idx.json => True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/label_to_idx.json
idx_to_label.json => True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/idx_to_label.json
graph_cooccur.npy => True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_cooccur.npy
graph_pmi.npy => True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_pmi.npy
graph_ppmi.npy => True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_ppmi.npy
graph_embeddings.npy => True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_embeddings.npy
graph_edges.csv => True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_edges.csv
graph_class_stats.csv => True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_class_stats.csv
m17_graph_config.json => True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/m17_graph_config.json

Num labels: 108
PMI shape: (108, 108)
Embedding shape: (108, 64)

    src_idx  dst_idx  src_label  dst_label  cooccur_count       pmi      ppmi
0        13       21         13         21            1.0  5.293305  5.293305
1        35       93         35         93            1.0  5.293305  5.293305
2        32       71         32         71            1.0  5.005623  5.005623
3        49      101         49        101            1.0  5.005623  5.005623
4         5       35          5         35            1.0  4.782479  4.782479
5        49       63         49         63            1.0  4.782479  4.782479
6        11       12         11         12            2.0  4.600158  4.600158
7        82       98         82         98            1.0  4.600158  4.600158
8         9      106          9        106            1.0  4.446007  4.446007
9        22       52         22         52            1.0  4.312476  4.312476
10       30       80         30         80            3.0  4.194693  4.194693
11        6       30          6         30            2.0  4.194693  4.194693
12       63      101         63        101            2.0  4.089332  4.089332
13       11       41         11         41            2.0  3.994022  3.994022
14        0      103          0        103            2.0  3.907011  3.907011
15        0       84          0         84            1.0  3.907010  3.907010
16        3       24          3         24            1.0  3.907010  3.907010
17       71       82         71         82            1.0  3.907010  3.907010
18       53       75         53         75            1.0  3.826968  3.826968
19       40      100         40        100            3.0  3.801650  3.801650

     idx  label  instance_count  prescription_doc_count
25    25     25               1                       1
49    49     49               1                       1
13    13     13               2                       1
32    32     32               4                       1
88    88     88               6                       2
77    77     77               6                       2
102  102    102               8                       1
66    66     66               8                       1
76    76     76              12                       2
21    21     21              13                       3
86    86     86              16                       1
58    58     58              18                       2
42    42     42              20                       2
22    22     22              20                       4
53    53     53              21                       1
11    11     11              22                       2
100  100    100              22                       4
39    39     39              24                       3
101  101    101              25                       4
63    63     63              26                       5

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh train_m17_faithful_pika.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 253, done.
remote: Counting objects: 100% (131/131), done.
remote: Compressing objects: 100% (109/109), done.
remote: Total 253 (delta 81), reused 22 (delta 22), pack-reused 122 (from 1)
Receiving objects: 100% (253/253), 2.59 MiB | 18.16 MiB/s, done.
Resolving deltas: 100% (136/136), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 25K May  4 15:22 train_m17_faithful_pika.py

In [ ]:
from pathlib import Path

graph_dir = Path("/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts")

files = [
    "graph_labels.json",
    "label_to_idx.json",
    "idx_to_label.json",
    "graph_embeddings.npy",
    "graph_pmi.npy",
    "m17_graph_config.json",
]

for f in files:
    p = graph_dir / f
    print(f, "=>", p.exists(), p)

graph_labels.json => True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_labels.json
label_to_idx.json => True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/label_to_idx.json
idx_to_label.json => True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/idx_to_label.json
graph_embeddings.npy => True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_embeddings.npy
graph_pmi.npy => True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_pmi.npy
m17_graph_config.json => True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/m17_graph_config.json

In [ ]:
import os

M17_TRAIN_DIR = "/content/drive/MyDrive/model/M17_faithful_pika/train_run"
os.makedirs(M17_TRAIN_DIR, exist_ok=True)

print("M17 train output dir:", M17_TRAIN_DIR)

M17 train output dir: /content/drive/MyDrive/model/M17_faithful_pika/train_run

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python train_m17_faithful_pika.py \
  --train_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv \
  --val_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv \
  --test_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv \
  --graph_artifacts_dir /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts \
  --output_dir /content/drive/MyDrive/model/M17_faithful_pika/train_run \
  --epochs 15 \
  --batch_size 16 \
  --lr 1e-4 \
  --class_weight_exponent 0.35 \
  --label_smoothing 0.02 \
  --pseudo_loss_weight 0.30 \
  --link_loss_weight 0.10 \
  --dropout_p 0.45 \
  --patience 5 \
  2>&1 | tee /content/drive/MyDrive/model/M17_faithful_pika/train_run/train_log.txt

/content/vaipe-contextual-pill-recognition
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
=== M17 FAITHFUL PIKA TRAINING ===
Using device: cuda
Train CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv
Val CSV  : /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv
Test CSV : /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv
Graph artifacts dir: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts
Output dir: /content/drive/MyDrive/model/M17_faithful_pika/train_run
Num classes: 108
Graph labels: 108
Graph embeddings shape: (108, 64)
Train pill images existing: 23189 / 23189
Train prescription images existing: 23189 / 23189
Val pill images existing: 4974 / 4974
Val prescription images existing: 4974 / 4974

Train rows: 23189
Val rows  : 4974
Train labels: 108
Val labels  : 89
Labels in train but missing in val: 19
[np.int64(0), np.int64(3), np.int64(4), np.int64(9), np.int64(13), np.int64(16), np.int64(20), np.int64(25), np.int64(32), np.int64(35), np.int64(44), np.int64(49), np.int64(53), np.int64(66), np.int64(85), np.int64(86), np.int64(94), np.int64(96), np.int64(102)]

Created M17FaithfulPIKAModel.
Pill model        : tf_efficientnetv2_s.in21k_ft_in1k
Prescription model: resnet18.a1_in1k
Graph dim         : 64
Hidden dim        : 256
Train graph embeddings: False

M17 Faithful PIKA Epoch [1/15]
Current LR: 0.00010000
Train Loss: 5.2806 | Main: 4.2883 | Pseudo: 3.3011 | Link: 0.0203 | Train Acc: 0.2471 | Train Macro F1: 0.0066
Val Loss  : 4.3853 | Val Acc  : 0.3315 | Val Macro Precision: 0.0197 | Val Macro Recall: 0.0219 | Val Macro F1: 0.0143
Saved best checkpoint: /content/drive/MyDrive/model/M17_faithful_pika/train_run/M17_faithful_pika_best.pth
Best Val Macro F1: 0.0143

M17 Faithful PIKA Epoch [2/15]
Current LR: 0.00009891
Train Loss: 4.3646 | Main: 3.6216 | Pseudo: 2.4710 | Link: 0.0172 | Train Acc: 0.4094 | Train Macro F1: 0.0418
Val Loss  : 3.7859 | Val Acc  : 0.5304 | Val Macro Precision: 0.1281 | Val Macro Recall: 0.1170 | Val Macro F1: 0.0999
Saved best checkpoint: /content/drive/MyDrive/model/M17_faithful_pika/train_run/M17_faithful_pika_best.pth
Best Val Macro F1: 0.0999

M17 Faithful PIKA Epoch [3/15]
Current LR: 0.00009568
Train Loss: 3.6847 | Main: 3.0391 | Pseudo: 2.1467 | Link: 0.0159 | Train Acc: 0.5305 | Train Macro F1: 0.1054
Val Loss  : 3.3742 | Val Acc  : 0.5877 | Val Macro Precision: 0.1709 | Val Macro Recall: 0.1745 | Val Macro F1: 0.1517
Saved best checkpoint: /content/drive/MyDrive/model/M17_faithful_pika/train_run/M17_faithful_pika_best.pth
Best Val Macro F1: 0.1517

M17 Faithful PIKA Epoch [4/15]
Current LR: 0.00009045
Train Loss: 3.1516 | Main: 2.5676 | Pseudo: 1.9416 | Link: 0.0152 | Train Acc: 0.6124 | Train Macro F1: 0.2125
Val Loss  : 3.0863 | Val Acc  : 0.6375 | Val Macro Precision: 0.2700 | Val Macro Recall: 0.2409 | Val Macro F1: 0.2323
Saved best checkpoint: /content/drive/MyDrive/model/M17_faithful_pika/train_run/M17_faithful_pika_best.pth
Best Val Macro F1: 0.2323

M17 Faithful PIKA Epoch [5/15]
Current LR: 0.00008346
Train Loss: 2.7335 | Main: 2.1933 | Pseudo: 1.7958 | Link: 0.0146 | Train Acc: 0.6826 | Train Macro F1: 0.3217
Val Loss  : 2.9355 | Val Acc  : 0.6486 | Val Macro Precision: 0.2768 | Val Macro Recall: 0.2870 | Val Macro F1: 0.2682
Saved best checkpoint: /content/drive/MyDrive/model/M17_faithful_pika/train_run/M17_faithful_pika_best.pth
Best Val Macro F1: 0.2682

M17 Faithful PIKA Epoch [6/15]
Current LR: 0.00007500
Train Loss: 2.4253 | Main: 1.9191 | Pseudo: 1.6825 | Link: 0.0142 | Train Acc: 0.7307 | Train Macro F1: 0.4067
Val Loss  : 2.7808 | Val Acc  : 0.6719 | Val Macro Precision: 0.3249 | Val Macro Recall: 0.3132 | Val Macro F1: 0.2962
Saved best checkpoint: /content/drive/MyDrive/model/M17_faithful_pika/train_run/M17_faithful_pika_best.pth
Best Val Macro F1: 0.2962

M17 Faithful PIKA Epoch [7/15]
Current LR: 0.00006545
Train Loss: 2.1757 | Main: 1.7049 | Pseudo: 1.5647 | Link: 0.0139 | Train Acc: 0.7689 | Train Macro F1: 0.4812
Val Loss  : 2.8144 | Val Acc  : 0.6661 | Val Macro Precision: 0.3786 | Val Macro Recall: 0.3375 | Val Macro F1: 0.3291
Saved best checkpoint: /content/drive/MyDrive/model/M17_faithful_pika/train_run/M17_faithful_pika_best.pth
Best Val Macro F1: 0.3291

M17 Faithful PIKA Epoch [8/15]
Current LR: 0.00005523
Train Loss: 1.9716 | Main: 1.5338 | Pseudo: 1.4550 | Link: 0.0135 | Train Acc: 0.7976 | Train Macro F1: 0.5459
Val Loss  : 2.7458 | Val Acc  : 0.6870 | Val Macro Precision: 0.4320 | Val Macro Recall: 0.3791 | Val Macro F1: 0.3770
Saved best checkpoint: /content/drive/MyDrive/model/M17_faithful_pika/train_run/M17_faithful_pika_best.pth
Best Val Macro F1: 0.3770

M17 Faithful PIKA Epoch [9/15]
Current LR: 0.00004477
Train Loss: 1.8107 | Main: 1.4033 | Pseudo: 1.3538 | Link: 0.0132 | Train Acc: 0.8288 | Train Macro F1: 0.6044
Val Loss  : 2.8157 | Val Acc  : 0.6763 | Val Macro Precision: 0.4266 | Val Macro Recall: 0.4068 | Val Macro F1: 0.3955
Saved best checkpoint: /content/drive/MyDrive/model/M17_faithful_pika/train_run/M17_faithful_pika_best.pth
Best Val Macro F1: 0.3955

M17 Faithful PIKA Epoch [10/15]
Current LR: 0.00003455
Train Loss: 1.6720 | Main: 1.2932 | Pseudo: 1.2583 | Link: 0.0128 | Train Acc: 0.8530 | Train Macro F1: 0.6385
Val Loss  : 2.8005 | Val Acc  : 0.6745 | Val Macro Precision: 0.4085 | Val Macro Recall: 0.3940 | Val Macro F1: 0.3834

M17 Faithful PIKA Epoch [11/15]
Current LR: 0.00002500
M17 Training:  63%|██████▎   | 917/1450 [08:01<04:04,  2.18it/s]

In [ ]:
!pip install -q kagglehub

import kagglehub
from pathlib import Path

dataset_path = kagglehub.dataset_download("tommyngx/vaipepill2022")

print("Dataset path:", dataset_path)
print("Exists:", Path(dataset_path).exists())

Downloading to /root/.cache/kagglehub/datasets/tommyngx/vaipepill2022/1.archive...

100%|██████████| 25.2G/25.2G [12:07<00:00, 37.2MB/s]

Extracting files...

Dataset path: /root/.cache/kagglehub/datasets/tommyngx/vaipepill2022/versions/1
Exists: True

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
from pathlib import Path
import torch
import pandas as pd

run_dir = Path("/content/drive/MyDrive/model/M17_faithful_pika/train_run")

best_path = run_dir / "M17_faithful_pika_best.pth"
last_path = run_dir / "M17_faithful_pika_last.pth"
hist_path = run_dir / "train_history.csv"

print("Best exists:", best_path.exists(), best_path)
print("Last exists:", last_path.exists(), last_path)
print("History exists:", hist_path.exists(), hist_path)

if best_path.exists():
    best_ckpt = torch.load(best_path, map_location="cpu", weights_only=False)
    print("\nBEST epoch:", best_ckpt.get("epoch"))
    print("BEST val_macro_f1:", best_ckpt.get("val_macro_f1"))

if last_path.exists():
    last_ckpt = torch.load(last_path, map_location="cpu", weights_only=False)
    print("\nLAST epoch:", last_ckpt.get("epoch"))
    print("LAST val_macro_f1:", last_ckpt.get("val_macro_f1"))

if hist_path.exists():
    hist = pd.read_csv(hist_path)
    display(hist.tail(10))

Best exists: True /content/drive/MyDrive/model/M17_faithful_pika/train_run/M17_faithful_pika_best.pth
Last exists: True /content/drive/MyDrive/model/M17_faithful_pika/train_run/M17_faithful_pika_last.pth
History exists: True /content/drive/MyDrive/model/M17_faithful_pika/train_run/train_history.csv

BEST epoch: 9
BEST val_macro_f1: 0.39549658214545763

LAST epoch: 10
LAST val_macro_f1: 0.38342794488233045

,epoch,train_loss,train_main_loss,train_pseudo_loss,train_link_loss,train_acc,train_macro_f1,val_loss,val_acc,val_macro_precision,val_macro_recall,val_macro_f1,lr
0,1,5.280605,4.288255,3.301055,0.020329,0.247057,0.006594,4.385271,0.331524,0.019682,0.021864,0.014268,0.000099
1,2,4.364617,3.621589,2.471021,0.017221,0.409375,0.041818,3.785906,0.530358,0.128141,0.116994,0.099908,0.000096
2,3,3.684720,3.039117,2.146697,0.015946,0.530510,0.105419,3.374181,0.587656,0.170864,0.174504,0.151737,0.000090
3,4,3.151620,2.567622,1.941597,0.015184,0.612446,0.212541,3.086325,0.637515,0.270043,0.240859,0.232300,0.000083
4,5,2.733478,2.193285,1.795769,0.014625,0.682608,0.321668,2.935523,0.648573,0.276824,0.287046,0.268242,0.000075
5,6,2.425302,1.919115,1.682547,0.014229,0.730734,0.406717,2.780773,0.671894,0.324899,0.313210,0.296181,0.000065
6,7,2.175749,1.704943,1.564730,0.013870,0.768856,0.481181,2.814371,0.666064,0.378567,0.337452,0.329071,0.000055
7,8,1.971603,1.533760,1.454972,0.013518,0.797620,0.545894,2.745828,0.686972,0.431984,0.379118,0.376999,0.000045
8,9,1.810748,1.403300,1.353774,0.013164,0.828755,0.604412,2.815663,0.676317,0.426573,0.406804,0.395497,0.000035
9,10,1.672012,1.293238,1.258297,0.012850,0.853034,0.638545,2.800467,0.674507,0.408512,0.394039,0.383428,0.000025

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh train_m17_faithful_pika.py train_m17_faithful_pika_resume.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 258, done.
remote: Counting objects: 100% (136/136), done.
remote: Compressing objects: 100% (114/114), done.
remote: Total 258 (delta 83), reused 22 (delta 22), pack-reused 122 (from 1)
Receiving objects: 100% (258/258), 2.59 MiB | 6.78 MiB/s, done.
Resolving deltas: 100% (138/138), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 25K May  5 06:15 train_m17_faithful_pika.py
-rw-r--r-- 1 root root 15K May  5 06:15 train_m17_faithful_pika_resume.py

In [ ]:
from pathlib import Path

graph_dir = Path("/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts")

files = [
    "graph_labels.json",
    "label_to_idx.json",
    "idx_to_label.json",
    "graph_embeddings.npy",
    "graph_pmi.npy",
]

for f in files:
    p = graph_dir / f
    print(f, "=>", p.exists(), p)

graph_labels.json => True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_labels.json
label_to_idx.json => True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/label_to_idx.json
idx_to_label.json => True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/idx_to_label.json
graph_embeddings.npy => True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_embeddings.npy
graph_pmi.npy => True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_pmi.npy

In [ ]:
from pathlib import Path
import shutil

ZIP_PATH = "/content/drive/MyDrive/VAIPE_FINAL_BACKUP/processed_pika_best.zip"

print("Zip exists:", Path(ZIP_PATH).exists(), ZIP_PATH)

!rm -rf /content/processed_pika_best
!rm -rf /content/_processed_pika_unzip
!mkdir -p /content/_processed_pika_unzip

!unzip -q "$ZIP_PATH" -d /content/_processed_pika_unzip

tmp = Path("/content/_processed_pika_unzip")

print("Extracted top-level items:")
for p in list(tmp.glob("*"))[:30]:
    print(p)

# Tìm thư mục chứa graph_labels.json để xác định root đúng
graph_files = list(tmp.rglob("graph_labels.json"))
print("\nFound graph_labels.json:", graph_files[:5])

if len(graph_files) == 0:
    raise FileNotFoundError("Không tìm thấy graph_labels.json trong processed_pika_best.zip")

src_root = graph_files[0].parent
print("Detected processed root:", src_root)

shutil.copytree(src_root, "/content/processed_pika_best")

print("\nDone.")
print("Data root:", Path("/content/processed_pika_best").exists())
print("Graph labels:", Path("/content/processed_pika_best/graph_labels.json").exists())
print("Graph PMI:", Path("/content/processed_pika_best/graph_pmi.npy").exists())

Zip exists: True /content/drive/MyDrive/VAIPE_FINAL_BACKUP/processed_pika_best.zip
error:  zipfile read error
Extracted top-level items:
/content/_processed_pika_unzip/pill_crops
/content/_processed_pika_unzip/best_pika_metadata.csv
/content/_processed_pika_unzip/graph_pmi.npy
/content/_processed_pika_unzip/graph_labels.json

Found graph_labels.json: [PosixPath('/content/_processed_pika_unzip/graph_labels.json')]
Detected processed root: /content/_processed_pika_unzip

Done.
Data root: True
Graph labels: True
Graph PMI: True

In [ ]:
import pandas as pd
from pathlib import Path

csvs = {
    "train": "/content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv",
    "val": "/content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv",
    "test": "/content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv",
}

for name, csv_path in csvs.items():
    df = pd.read_csv(csv_path)

    print("\n====================")
    print("SPLIT:", name)
    print("====================")
    print("CSV rows:", len(df))
    print("Labels:", df["pill_label"].nunique())

    for col in ["pill_crop_path", "prescription_image_path"]:
        exists = df[col].apply(lambda p: Path(str(p)).exists())
        print(f"{col} existing:", int(exists.sum()), "/", len(df))
        print(f"{col} missing:", int((~exists).sum()))

====================
SPLIT: train
====================
CSV rows: 23189
Labels: 108
pill_crop_path existing: 15720 / 23189
pill_crop_path missing: 7469
prescription_image_path existing: 23189 / 23189
prescription_image_path missing: 0

====================
SPLIT: val
====================
CSV rows: 4974
Labels: 89
pill_crop_path existing: 3282 / 4974
pill_crop_path missing: 1692
prescription_image_path existing: 4974 / 4974
prescription_image_path missing: 0

====================
SPLIT: test
====================
CSV rows: 4550
Labels: 82
pill_crop_path existing: 3149 / 4550
pill_crop_path missing: 1401
prescription_image_path existing: 4550 / 4550
prescription_image_path missing: 0

In [ ]:
import os

RESUME_DIR = "/content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9"
os.makedirs(RESUME_DIR, exist_ok=True)

print("Resume output dir:", RESUME_DIR)

Resume output dir: /content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python train_m17_faithful_pika_resume.py \
  --resume_checkpoint /content/drive/MyDrive/model/M17_faithful_pika/train_run/M17_faithful_pika_best.pth \
  --previous_history_csv /content/drive/MyDrive/model/M17_faithful_pika/train_run/train_history.csv \
  --train_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv \
  --val_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv \
  --test_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv \
  --graph_artifacts_dir /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts \
  --output_dir /content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9 \
  --total_epochs 15 \
  --batch_size 16 \
  --lr 4.5e-5 \
  --class_weight_exponent 0.35 \
  --label_smoothing 0.02 \
  --pseudo_loss_weight 0.30 \
  --link_loss_weight 0.10 \
  --dropout_p 0.45 \
  --patience 4 \
  2>&1 | tee /content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9/train_log.txt

/content/vaipe-contextual-pill-recognition
=== M17 FAITHFUL PIKA RESUME TRAINING ===
Using device: cuda
Resume checkpoint: /content/drive/MyDrive/model/M17_faithful_pika/train_run/M17_faithful_pika_best.pth
Train CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv
Val CSV  : /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv
Test CSV : /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv
Graph artifacts dir: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts
Output dir: /content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9

Resume epoch: 9
Start epoch : 10
Initial best Val Macro F1: 0.39549658214545763
Num classes: 108
Graph dim: 64
Max context len: 5
Graph embeddings shape: (108, 64)
Train pill images existing: 23189 / 23189
Train prescription images existing: 23189 / 23189
Val pill images existing: 4974 / 4974
Val prescription images existing: 4974 / 4974

Train rows: 23189
Val rows  : 4974
Train labels: 108
Val labels  : 89
Labels in train but missing in val: 19
[np.int64(0), np.int64(3), np.int64(4), np.int64(9), np.int64(13), np.int64(16), np.int64(20), np.int64(25), np.int64(32), np.int64(35), np.int64(44), np.int64(49), np.int64(53), np.int64(66), np.int64(85), np.int64(86), np.int64(94), np.int64(96), np.int64(102)]

Loaded model weights from resume checkpoint.
Pill model        : tf_efficientnetv2_s.in21k_ft_in1k
Prescription model: resnet18.a1_in1k
Hidden dim        : 256
Train graph embeddings: False
Copied resume checkpoint as initial best: /content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9/M17_faithful_pika_resume_best.pth
Copied resume checkpoint as initial last: /content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9/M17_faithful_pika_resume_last.pth
Loaded previous history rows: 10

M17 Resume Epoch [10/15]
Current LR: 0.00004500
Train Loss: 1.6526 | Main: 1.2739 | Pseudo: 1.2582 | Link: 0.0128 | Train Acc: 0.8537 | Train Macro F1: 0.6467
Val Loss  : 2.7392 | Val Acc  : 0.6858 | Val Macro Precision: 0.4194 | Val Macro Recall: 0.4125 | Val Macro F1: 0.3996
Saved best checkpoint: /content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9/M17_faithful_pika_resume_best.pth
Best Val Macro F1: 0.3996

M17 Resume Epoch [11/15]
Current LR: 0.00004199
Train Loss: 1.5278 | Main: 1.1766 | Pseudo: 1.1667 | Link: 0.0125 | Train Acc: 0.8754 | Train Macro F1: 0.6892
Val Loss  : 2.8211 | Val Acc  : 0.6832 | Val Macro Precision: 0.4254 | Val Macro Recall: 0.4214 | Val Macro F1: 0.4096
Saved best checkpoint: /content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9/M17_faithful_pika_resume_best.pth
Best Val Macro F1: 0.4096

M17 Resume Epoch [12/15]
Current LR: 0.00003375
Train Loss: 1.4029 | Main: 1.0806 | Pseudo: 1.0703 | Link: 0.0122 | Train Acc: 0.8999 | Train Macro F1: 0.7295
Val Loss  : 2.8449 | Val Acc  : 0.6773 | Val Macro Precision: 0.4258 | Val Macro Recall: 0.4131 | Val Macro F1: 0.4053

M17 Resume Epoch [13/15]
Current LR: 0.00002250
Train Loss: 1.2949 | Main: 0.9998 | Pseudo: 0.9797 | Link: 0.0119 | Train Acc: 0.9219 | Train Macro F1: 0.7659
Val Loss  : 2.8476 | Val Acc  : 0.6803 | Val Macro Precision: 0.4200 | Val Macro Recall: 0.4087 | Val Macro F1: 0.4023

M17 Resume Epoch [14/15]
Current LR: 0.00001125
Train Loss: 1.2182 | Main: 0.9421 | Pseudo: 0.9164 | Link: 0.0116 | Train Acc: 0.9324 | Train Macro F1: 0.7741
Val Loss  : 2.8470 | Val Acc  : 0.6785 | Val Macro Precision: 0.4154 | Val Macro Recall: 0.4177 | Val Macro F1: 0.4069

M17 Resume Epoch [15/15]
Current LR: 0.00000301
Train Loss: 1.1694 | Main: 0.9069 | Pseudo: 0.8711 | Link: 0.0115 | Train Acc: 0.9440 | Train Macro F1: 0.7927
Val Loss  : 2.8521 | Val Acc  : 0.6805 | Val Macro Precision: 0.4381 | Val Macro Recall: 0.4228 | Val Macro F1: 0.4175
Saved best checkpoint: /content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9/M17_faithful_pika_resume_best.pth
Best Val Macro F1: 0.4175

M17 resume training done.
Best checkpoint: /content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9/M17_faithful_pika_resume_best.pth
Best Val Macro F1: 0.4175186514209033
Last checkpoint: /content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9/M17_faithful_pika_resume_last.pth

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh evaluate_m17_faithful_pika.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 261, done.
remote: Counting objects: 100% (139/139), done.
remote: Compressing objects: 100% (117/117), done.
remote: Total 261 (delta 85), reused 22 (delta 22), pack-reused 122 (from 1)
Receiving objects: 100% (261/261), 2.60 MiB | 6.66 MiB/s, done.
Resolving deltas: 100% (140/140), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 13K May  5 07:56 evaluate_m17_faithful_pika.py

In [ ]:
import os

EVAL_DIR = "/content/drive/MyDrive/model/M17_faithful_pika/test_eval"
os.makedirs(EVAL_DIR, exist_ok=True)

print("Eval output dir:", EVAL_DIR)

Eval output dir: /content/drive/MyDrive/model/M17_faithful_pika/test_eval

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python evaluate_m17_faithful_pika.py \
  --checkpoint /content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9/M17_faithful_pika_resume_best.pth \
  --test_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv \
  --graph_artifacts_dir /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts \
  --output_dir /content/drive/MyDrive/model/M17_faithful_pika/test_eval \
  --batch_size 32 \
  2>&1 | tee /content/drive/MyDrive/model/M17_faithful_pika/test_eval/test_log.txt

/content/vaipe-contextual-pill-recognition
=== EVALUATE M17 FAITHFUL PIKA ===
Using device: cuda
Checkpoint: /content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9/M17_faithful_pika_resume_best.pth
Test CSV  : /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv
Graph artifacts dir: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts
Output dir: /content/drive/MyDrive/model/M17_faithful_pika/test_eval
Using graph embeddings: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_embeddings.npy
Num classes: 108
Max context len: 5
Graph embeddings shape: (108, 64)

Raw test rows: 4550
Raw test labels: 82
Raw test columns: ['pill_crop_path', 'pill_label', 'pill_json', 'prescription_json', 'prescription_image_path', 'context_labels', 'prescription_key', 'split', 'source_split', 'clean_split']
Test pill images existing: 4550 / 4550
Test prescription images existing: 4550 / 4550

Test rows after image check: 4550
Test labels present: 82
Test mapped label min: 1
Test mapped label max: 107
Model type        : M17FaithfulPIKAModel
Pill model        : tf_efficientnetv2_s.in21k_ft_in1k
Prescription model: resnet18.a1_in1k
Hidden dim        : 256
Graph dim         : 64
Num classes       : 108
Evaluating M17: 100%|██████████| 143/143 [01:59<00:00,  1.20it/s]

=== M17 TEST RESULTS ===
Test Accuracy                 : 0.683516
Test Macro Precision Present  : 0.417033
Test Macro Recall Present     : 0.404075
Test Macro F1 Present Classes : 0.394083
Test Macro Precision All      : 0.355250
Test Macro Recall All         : 0.344212
Test Macro F1 All Classes     : 0.335701
Test Weighted F1              : 0.674269

Saved files:
/content/drive/MyDrive/model/M17_faithful_pika/test_eval/m17_test_metrics.json
/content/drive/MyDrive/model/M17_faithful_pika/test_eval/m17_test_predictions.csv
/content/drive/MyDrive/model/M17_faithful_pika/test_eval/m17_classification_report.csv
/content/drive/MyDrive/model/M17_faithful_pika/test_eval/m17_per_class_metrics.csv
/content/drive/MyDrive/model/M17_faithful_pika/test_eval/m17_confusion_matrix.csv

đây là baseline chính thức:

M17 faithful PIKA baseline:
Test Macro F1 Present = 0.3941

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh train_m18_improved_pika.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 264, done.
remote: Counting objects: 100% (142/142), done.
remote: Compressing objects: 100% (120/120), done.
remote: Total 264 (delta 87), reused 22 (delta 22), pack-reused 122 (from 1)
Receiving objects: 100% (264/264), 2.60 MiB | 6.37 MiB/s, done.
Resolving deltas: 100% (142/142), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 17K May  5 08:02 train_m18_improved_pika.py

In [ ]:
import os

M18_DIR = "/content/drive/MyDrive/model/M18_improved_pika/train_run"
os.makedirs(M18_DIR, exist_ok=True)

print("M18 output dir:", M18_DIR)

M18 output dir: /content/drive/MyDrive/model/M18_improved_pika/train_run

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python train_m18_improved_pika.py \
  --base_checkpoint /content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9/M17_faithful_pika_resume_best.pth \
  --previous_history_csv /content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9/train_history.csv \
  --train_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv \
  --val_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv \
  --test_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv \
  --graph_artifacts_dir /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts \
  --output_dir /content/drive/MyDrive/model/M18_improved_pika/train_run \
  --epochs 8 \
  --batch_size 16 \
  --lr 2.5e-5 \
  --class_weight_exponent 0.35 \
  --label_smoothing 0.02 \
  --pseudo_loss_weight 0.15 \
  --link_loss_weight 0.05 \
  --dropout_p 0.45 \
  --train_graph_embeddings \
  --patience 4 \
  --min_delta 0.0001 \
  2>&1 | tee /content/drive/MyDrive/model/M18_improved_pika/train_run/train_log.txt

/content/vaipe-contextual-pill-recognition
=== M18 IMPROVED PIKA TRAINING ===
Using device: cuda
Base checkpoint: /content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9/M17_faithful_pika_resume_best.pth
Train CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv
Val CSV  : /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv
Test CSV : /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv
Graph artifacts dir: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts
Output dir: /content/drive/MyDrive/model/M18_improved_pika/train_run

Base epoch: 15
Base Val Macro F1: 0.4175186514209033
Num classes: 108
Graph dim: 64
Max context len: 5
Pill model: tf_efficientnetv2_s.in21k_ft_in1k
Prescription model: resnet18.a1_in1k

Graph embeddings shape: (108, 64)
Train pill images existing: 23189 / 23189
Train prescription images existing: 23189 / 23189
Val pill images existing: 4974 / 4974
Val prescription images existing: 4974 / 4974

Train rows: 23189
Val rows  : 4974
Train labels: 108
Val labels  : 89
Labels in train but missing in val: 19
[np.int64(0), np.int64(3), np.int64(4), np.int64(9), np.int64(13), np.int64(16), np.int64(20), np.int64(25), np.int64(32), np.int64(35), np.int64(44), np.int64(49), np.int64(53), np.int64(66), np.int64(85), np.int64(86), np.int64(94), np.int64(96), np.int64(102)]

Loaded base M17 checkpoint successfully.
Train graph embeddings: True
Updated Dropout modules: 4 | dropout_p=0.45
Total params: 31996093
Trainable params: 31996093
Copied base checkpoint as initial M18 best: /content/drive/MyDrive/model/M18_improved_pika/train_run/M18_improved_pika_best.pth
Loaded previous history rows: 16

M18 Improved PIKA Fine-tune Epoch [1/8]
Current LR: 0.00002500
Train Loss: 0.9675 | Main: 0.8437 | Pseudo: 0.8216 | Link: 0.0112 | Train Acc: 0.9589 | Train Macro F1: 0.8239
Val Loss  : 2.5397 | Val Acc  : 0.6755 | Val Macro Precision: 0.4230 | Val Macro Recall: 0.4198 | Val Macro F1: 0.4065
No significant improvement. bad_epochs=1/4

M18 Improved PIKA Fine-tune Epoch [2/8]
Current LR: 0.00002405
Train Loss: 0.9190 | Main: 0.8018 | Pseudo: 0.7779 | Link: 0.0110 | Train Acc: 0.9671 | Train Macro F1: 0.8391
Val Loss  : 2.5755 | Val Acc  : 0.6779 | Val Macro Precision: 0.4305 | Val Macro Recall: 0.4242 | Val Macro F1: 0.4146
No significant improvement. bad_epochs=2/4

M18 Improved PIKA Fine-tune Epoch [3/8]
Current LR: 0.00002134
Train Loss: 0.8735 | Main: 0.7644 | Pseudo: 0.7240 | Link: 0.0107 | Train Acc: 0.9736 | Train Macro F1: 0.8528
Val Loss  : 2.6100 | Val Acc  : 0.6735 | Val Macro Precision: 0.4249 | Val Macro Recall: 0.4161 | Val Macro F1: 0.4061
No significant improvement. bad_epochs=3/4

M18 Improved PIKA Fine-tune Epoch [4/8]
Current LR: 0.00001728
Train Loss: 0.8454 | Main: 0.7405 | Pseudo: 0.6961 | Link: 0.0105 | Train Acc: 0.9780 | Train Macro F1: 0.8748
Val Loss  : 2.6738 | Val Acc  : 0.6685 | Val Macro Precision: 0.4306 | Val Macro Recall: 0.4166 | Val Macro F1: 0.4061
No significant improvement. bad_epochs=4/4
Early stopping triggered after 4 non-improving epochs.

M18 training done.
Best checkpoint: /content/drive/MyDrive/model/M18_improved_pika/train_run/M18_improved_pika_best.pth
Best Val Macro F1: 0.4175186514209033
Last checkpoint: /content/drive/MyDrive/model/M18_improved_pika/train_run/M18_improved_pika_last.pth

In [ ]:
import os

M18_V2_DIR = "/content/drive/MyDrive/model/M18_improved_pika/train_run_v2_safe"
os.makedirs(M18_V2_DIR, exist_ok=True)

print("M18 v2 output dir:", M18_V2_DIR)

M18 v2 output dir: /content/drive/MyDrive/model/M18_improved_pika/train_run_v2_safe

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python train_m18_improved_pika.py \
  --base_checkpoint /content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9/M17_faithful_pika_resume_best.pth \
  --previous_history_csv /content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9/train_history.csv \
  --train_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv \
  --val_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv \
  --test_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv \
  --graph_artifacts_dir /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts \
  --output_dir /content/drive/MyDrive/model/M18_improved_pika/train_run_v2_safe \
  --epochs 6 \
  --batch_size 16 \
  --lr 1e-5 \
  --class_weight_exponent 0.35 \
  --label_smoothing 0.02 \
  --pseudo_loss_weight 0.20 \
  --link_loss_weight 0.05 \
  --dropout_p 0.50 \
  --freeze_backbone_epochs 1 \
  --patience 3 \
  --min_delta 0.0001 \
  2>&1 | tee /content/drive/MyDrive/model/M18_improved_pika/train_run_v2_safe/train_log.txt

/content/vaipe-contextual-pill-recognition
=== M18 IMPROVED PIKA TRAINING ===
Using device: cuda
Base checkpoint: /content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9/M17_faithful_pika_resume_best.pth
Train CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv
Val CSV  : /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv
Test CSV : /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv
Graph artifacts dir: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts
Output dir: /content/drive/MyDrive/model/M18_improved_pika/train_run_v2_safe

Base epoch: 15
Base Val Macro F1: 0.4175186514209033
Num classes: 108
Graph dim: 64
Max context len: 5
Pill model: tf_efficientnetv2_s.in21k_ft_in1k
Prescription model: resnet18.a1_in1k

Graph embeddings shape: (108, 64)
Train pill images existing: 23189 / 23189
Train prescription images existing: 23189 / 23189
Val pill images existing: 4974 / 4974
Val prescription images existing: 4974 / 4974

Train rows: 23189
Val rows  : 4974
Train labels: 108
Val labels  : 89
Labels in train but missing in val: 19
[np.int64(0), np.int64(3), np.int64(4), np.int64(9), np.int64(13), np.int64(16), np.int64(20), np.int64(25), np.int64(32), np.int64(35), np.int64(44), np.int64(49), np.int64(53), np.int64(66), np.int64(85), np.int64(86), np.int64(94), np.int64(96), np.int64(102)]

Loaded base M17 checkpoint successfully.
Train graph embeddings: False
Updated Dropout modules: 4 | dropout_p=0.5
Will freeze visual backbones for first 1 epoch(s).
Total params: 31996093
Trainable params: 31989181
Copied base checkpoint as initial M18 best: /content/drive/MyDrive/model/M18_improved_pika/train_run_v2_safe/M18_improved_pika_best.pth
Loaded previous history rows: 16

M18 Improved PIKA Fine-tune Epoch [1/6]
Current LR: 0.00001000
Visual backbones frozen: True
Train Loss: 1.0537 | Main: 0.8866 | Pseudo: 0.8328 | Link: 0.0115 | Train Acc: 0.9538 | Train Macro F1: 0.8147
Val Loss  : 2.6302 | Val Acc  : 0.6817 | Val Macro Precision: 0.4387 | Val Macro Recall: 0.4229 | Val Macro F1: 0.4166
No significant improvement. bad_epochs=1/3

M18 Improved PIKA Fine-tune Epoch [2/6]
Current LR: 0.00000933
Visual backbones frozen: False
Rebuilt optimizer after unfreezing backbones.
Train Loss: 1.0325 | Main: 0.8674 | Pseudo: 0.8229 | Link: 0.0114 | Train Acc: 0.9596 | Train Macro F1: 0.8166
Val Loss  : 2.6691 | Val Acc  : 0.6801 | Val Macro Precision: 0.4500 | Val Macro Recall: 0.4271 | Val Macro F1: 0.4217
Saved best checkpoint: /content/drive/MyDrive/model/M18_improved_pika/train_run_v2_safe/M18_improved_pika_best.pth
Best Val Macro F1: 0.4217

M18 Improved PIKA Fine-tune Epoch [3/6]
Current LR: 0.00000905
Visual backbones frozen: False
Train Loss: 1.0002 | Main: 0.8423 | Pseudo: 0.7864 | Link: 0.0113 | Train Acc: 0.9640 | Train Macro F1: 0.8274
Val Loss  : 2.6759 | Val Acc  : 0.6787 | Val Macro Precision: 0.4317 | Val Macro Recall: 0.4119 | Val Macro F1: 0.4057
No significant improvement. bad_epochs=1/3

M18 Improved PIKA Fine-tune Epoch [4/6]
Current LR: 0.00000655
Visual backbones frozen: False
Train Loss: 0.9815 | Main: 0.8272 | Pseudo: 0.7683 | Link: 0.0113 | Train Acc: 0.9665 | Train Macro F1: 0.8274
Val Loss  : 2.7094 | Val Acc  : 0.6749 | Val Macro Precision: 0.4318 | Val Macro Recall: 0.4217 | Val Macro F1: 0.4127
No significant improvement. bad_epochs=2/3

M18 Improved PIKA Fine-tune Epoch [5/6]
Current LR: 0.00000345
Visual backbones frozen: False
Train Loss: 0.9881 | Main: 0.8310 | Pseudo: 0.7824 | Link: 0.0113 | Train Acc: 0.9651 | Train Macro F1: 0.8259
Val Loss  : 2.7088 | Val Acc  : 0.6755 | Val Macro Precision: 0.4512 | Val Macro Recall: 0.4172 | Val Macro F1: 0.4141
No significant improvement. bad_epochs=3/3
Early stopping triggered after 3 non-improving epochs.

M18 training done.
Best checkpoint: /content/drive/MyDrive/model/M18_improved_pika/train_run_v2_safe/M18_improved_pika_best.pth
Best Val Macro F1: 0.42168542248228313
Last checkpoint: /content/drive/MyDrive/model/M18_improved_pika/train_run_v2_safe/M18_improved_pika_last.pth

Sau khi M18_v2 chạy xong, dùng lại evaluate_m17_faithful_pika.py để đánh giá checkpoint M18 trên test, vì model class vẫn là M17FaithfulPIKAModel.

In [ ]:
import os

M18_EVAL_DIR = "/content/drive/MyDrive/model/M18_improved_pika/test_eval_v2_safe"
os.makedirs(M18_EVAL_DIR, exist_ok=True)

print("M18 eval output dir:", M18_EVAL_DIR)

M18 eval output dir: /content/drive/MyDrive/model/M18_improved_pika/test_eval_v2_safe

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python evaluate_m17_faithful_pika.py \
  --checkpoint /content/drive/MyDrive/model/M18_improved_pika/train_run_v2_safe/M18_improved_pika_best.pth \
  --test_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv \
  --graph_artifacts_dir /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts \
  --output_dir /content/drive/MyDrive/model/M18_improved_pika/test_eval_v2_safe \
  --batch_size 32 \
  2>&1 | tee /content/drive/MyDrive/model/M18_improved_pika/test_eval_v2_safe/test_log.txt

/content/vaipe-contextual-pill-recognition
=== EVALUATE M17 FAITHFUL PIKA ===
Using device: cuda
Checkpoint: /content/drive/MyDrive/model/M18_improved_pika/train_run_v2_safe/M18_improved_pika_best.pth
Test CSV  : /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv
Graph artifacts dir: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts
Output dir: /content/drive/MyDrive/model/M18_improved_pika/test_eval_v2_safe
Using graph embeddings: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_embeddings.npy
Num classes: 108
Max context len: 5
Graph embeddings shape: (108, 64)

Raw test rows: 4550
Raw test labels: 82
Raw test columns: ['pill_crop_path', 'pill_label', 'pill_json', 'prescription_json', 'prescription_image_path', 'context_labels', 'prescription_key', 'split', 'source_split', 'clean_split']
Test pill images existing: 4550 / 4550
Test prescription images existing: 4550 / 4550

Test rows after image check: 4550
Test labels present: 82
Test mapped label min: 1
Test mapped label max: 107
Model type        : M17FaithfulPIKAModel
Pill model        : tf_efficientnetv2_s.in21k_ft_in1k
Prescription model: resnet18.a1_in1k
Hidden dim        : 256
Graph dim         : 64
Num classes       : 108
Evaluating M17: 100%|██████████| 143/143 [01:52<00:00,  1.27it/s]

=== M17 TEST RESULTS ===
Test Accuracy                 : 0.682198
Test Macro Precision Present  : 0.413849
Test Macro Recall Present     : 0.399814
Test Macro F1 Present Classes : 0.393772
Test Macro Precision All      : 0.356370
Test Macro Recall All         : 0.344284
Test Macro F1 All Classes     : 0.339081
Test Weighted F1              : 0.673662

Saved files:
/content/drive/MyDrive/model/M18_improved_pika/test_eval_v2_safe/m17_test_metrics.json
/content/drive/MyDrive/model/M18_improved_pika/test_eval_v2_safe/m17_test_predictions.csv
/content/drive/MyDrive/model/M18_improved_pika/test_eval_v2_safe/m17_classification_report.csv
/content/drive/MyDrive/model/M18_improved_pika/test_eval_v2_safe/m17_per_class_metrics.csv
/content/drive/MyDrive/model/M18_improved_pika/test_eval_v2_safe/m17_confusion_matrix.csv

M19 vẫn giữ nền tảng PIKA:

pill image
prescription image
graph embedding
context labels

Nhưng cải tiến phần fusion/context:

M17 fusion:
[pill_z, pres_z, context_z] → classifier

M19 fusion:
[pill_z, pres_z, context_z,
 pill_z * context_z,
 pill_z * pres_z,
 |pill_z - context_z|,
 |pill_z - pres_z|]
→ deeper classifier

Thêm nữa:

context dropout

để model không quá phụ thuộc vào context/prescription và giảm overfit.

In [ ]:
!pip install -q timm kagglehub scikit-learn pandas numpy tqdm pillow

In [ ]:
from pathlib import Path

paths = {
    "Drive model folder": "/content/drive/MyDrive/model",
    "Processed zip": "/content/drive/MyDrive/VAIPE_FINAL_BACKUP/processed_pika_best.zip",

    "Split v2 folder": "/content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2",
    "Train clean v2": "/content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv",
    "Val clean v2": "/content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv",
    "Test clean v2": "/content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv",

    "M17 graph dir": "/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts",
    "M17 graph embeddings": "/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_embeddings.npy",
    "M17 label_to_idx": "/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/label_to_idx.json",
    "M17 idx_to_label": "/content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/idx_to_label.json",

    "M17 best ckpt": "/content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9/M17_faithful_pika_resume_best.pth",
    "M18 v2 best ckpt": "/content/drive/MyDrive/model/M18_improved_pika/train_run_v2_safe/M18_improved_pika_best.pth",
}

for name, p in paths.items():
    print(f"{name:24}:", Path(p).exists(), p)

Drive model folder      : True /content/drive/MyDrive/model
Processed zip           : True /content/drive/MyDrive/VAIPE_FINAL_BACKUP/processed_pika_best.zip
Split v2 folder         : True /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2
Train clean v2          : True /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv
Val clean v2            : True /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv
Test clean v2           : True /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv
M17 graph dir           : True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts
M17 graph embeddings    : True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_embeddings.npy
M17 label_to_idx        : True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/label_to_idx.json
M17 idx_to_label        : True /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/idx_to_label.json
M17 best ckpt           : True /content/drive/MyDrive/model/M17_faithful_pika/train_run_resume_from_best_ep9/M17_faithful_pika_resume_best.pth
M18 v2 best ckpt        : True /content/drive/MyDrive/model/M18_improved_pika/train_run_v2_safe/M18_improved_pika_best.pth

In [ ]:
from pathlib import Path

sample_paths = [
    "/root/.cache/kagglehub/datasets/tommyngx/vaipepill2022/versions/1/public_train/prescription/image/VAIPE_P_TRAIN_188.png",
    "/root/.cache/kagglehub/datasets/tommyngx/vaipepill2022/versions/1/public_train/prescription/image/VAIPE_P_TRAIN_711.png",
]

for p in sample_paths:
    print(Path(p).exists(), p)

True /root/.cache/kagglehub/datasets/tommyngx/vaipepill2022/versions/1/public_train/prescription/image/VAIPE_P_TRAIN_188.png
True /root/.cache/kagglehub/datasets/tommyngx/vaipepill2022/versions/1/public_train/prescription/image/VAIPE_P_TRAIN_711.png

In [ ]:
from pathlib import Path
import shutil

ZIP_PATH = "/content/drive/MyDrive/VAIPE_FINAL_BACKUP/processed_pika_best.zip"

print("Zip exists:", Path(ZIP_PATH).exists(), ZIP_PATH)

!rm -rf /content/processed_pika_best
!rm -rf /content/_processed_pika_unzip
!mkdir -p /content/_processed_pika_unzip

!unzip -q "$ZIP_PATH" -d /content/_processed_pika_unzip

tmp = Path("/content/_processed_pika_unzip")

print("Extracted top-level items:")
for p in list(tmp.glob("*"))[:30]:
    print(p)

graph_files = list(tmp.rglob("graph_labels.json"))
print("\nFound graph_labels.json:", graph_files[:5])

if len(graph_files) == 0:
    raise FileNotFoundError("Không tìm thấy graph_labels.json trong processed_pika_best.zip")

src_root = graph_files[0].parent
print("Detected processed root:", src_root)

shutil.copytree(src_root, "/content/processed_pika_best")

print("\nDone.")
print("Data root:", Path("/content/processed_pika_best").exists())
print("Graph labels:", Path("/content/processed_pika_best/graph_labels.json").exists())
print("Graph PMI:", Path("/content/processed_pika_best/graph_pmi.npy").exists())

Zip exists: True /content/drive/MyDrive/VAIPE_FINAL_BACKUP/processed_pika_best.zip
Extracted top-level items:
/content/_processed_pika_unzip/pill_crops
/content/_processed_pika_unzip/best_pika_metadata.csv
/content/_processed_pika_unzip/graph_pmi.npy
/content/_processed_pika_unzip/graph_labels.json

Found graph_labels.json: [PosixPath('/content/_processed_pika_unzip/graph_labels.json')]
Detected processed root: /content/_processed_pika_unzip

Done.
Data root: True
Graph labels: True
Graph PMI: True

In [ ]:
import pandas as pd
from pathlib import Path

csvs = {
    "train": "/content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv",
    "val": "/content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv",
    "test": "/content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv",
}

for name, csv_path in csvs.items():
    df = pd.read_csv(csv_path)

    print("\n====================")
    print("SPLIT:", name)
    print("====================")
    print("CSV rows:", len(df))
    print("Labels:", df["pill_label"].nunique())

    for col in ["pill_crop_path", "prescription_image_path"]:
        exists = df[col].apply(lambda p: Path(str(p)).exists())
        print(f"{col} existing:", int(exists.sum()), "/", len(df))
        print(f"{col} missing:", int((~exists).sum()))

        if (~exists).sum() > 0:
            missing_df = df[~exists]
            show_cols = [c for c in [col, "pill_label", "prescription_key", "source_split"] if c in missing_df.columns]
            print("Missing examples:")
            print(missing_df[show_cols].head(5).to_string(index=False))

====================
SPLIT: train
====================
CSV rows: 23189
Labels: 108
pill_crop_path existing: 23189 / 23189
pill_crop_path missing: 0
prescription_image_path existing: 23189 / 23189
prescription_image_path missing: 0

====================
SPLIT: val
====================
CSV rows: 4974
Labels: 89
pill_crop_path existing: 4974 / 4974
pill_crop_path missing: 0
prescription_image_path existing: 4974 / 4974
prescription_image_path missing: 0

====================
SPLIT: test
====================
CSV rows: 4550
Labels: 82
pill_crop_path existing: 4550 / 4550
pill_crop_path missing: 0
prescription_image_path existing: 4550 / 4550
prescription_image_path missing: 0

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh train_m17_faithful_pika.py
!ls -lh train_m18_improved_pika.py
!ls -lh evaluate_m17_faithful_pika.py
!ls -lh train_m19_arch_pika_v1.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 267, done.
remote: Counting objects: 100% (145/145), done.
remote: Compressing objects: 100% (123/123), done.
remote: Total 267 (delta 89), reused 22 (delta 22), pack-reused 122 (from 1)
Receiving objects: 100% (267/267), 2.60 MiB | 10.21 MiB/s, done.
Resolving deltas: 100% (144/144), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 25K May  5 10:58 train_m17_faithful_pika.py
-rw-r--r-- 1 root root 17K May  5 10:58 train_m18_improved_pika.py
-rw-r--r-- 1 root root 13K May  5 10:58 evaluate_m17_faithful_pika.py
-rw-r--r-- 1 root root 26K May  5 10:58 train_m19_arch_pika_v1.py

In [ ]:
import os

M19_DIR = "/content/drive/MyDrive/model/M19_arch_pika_v1/train_run"
os.makedirs(M19_DIR, exist_ok=True)

print("M19 output dir:", M19_DIR)

M19 output dir: /content/drive/MyDrive/model/M19_arch_pika_v1/train_run

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python train_m19_arch_pika_v1.py \
  --train_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv \
  --val_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv \
  --test_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv \
  --graph_artifacts_dir /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts \
  --output_dir /content/drive/MyDrive/model/M19_arch_pika_v1/train_run \
  --epochs 15 \
  --batch_size 16 \
  --lr 1e-4 \
  --class_weight_exponent 0.35 \
  --label_smoothing 0.02 \
  --pseudo_loss_weight 0.20 \
  --link_loss_weight 0.05 \
  --dropout_p 0.50 \
  --context_dropout_p 0.20 \
  --freeze_backbone_epochs 1 \
  --patience 5 \
  2>&1 | tee /content/drive/MyDrive/model/M19_arch_pika_v1/train_run/train_log.txt

/content/vaipe-contextual-pill-recognition
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
=== M19 ARCHITECTURE PIKA V1 TRAINING ===
Using device: cuda
Train CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv
Val CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv
Test CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv
Graph artifacts dir: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts
Output dir: /content/drive/MyDrive/model/M19_arch_pika_v1/train_run
Num classes: 108
Graph embeddings shape: (108, 64)
Train pill images existing: 23189 / 23189
Train prescription images existing: 23189 / 23189
Val pill images existing: 4974 / 4974
Val prescription images existing: 4974 / 4974
Train rows: 23189
Val rows: 4974
Train labels: 108
Val labels: 89
Labels in train but missing in val: 19
[np.int64(0), np.int64(3), np.int64(4), np.int64(9), np.int64(13), np.int64(16), np.int64(20), np.int64(25), np.int64(32), np.int64(35), np.int64(44), np.int64(49), np.int64(53), np.int64(66), np.int64(85), np.int64(86), np.int64(94), np.int64(96), np.int64(102)]
Created M19ArchitecturePIKA.
Pill model: tf_efficientnetv2_s.in21k_ft_in1k
Prescription model: resnet18.a1_in1k
Graph dim: 64
Hidden dim: 256
Dropout: 0.5
Context dropout: 0.2
Train graph embeddings: False
Visual backbones frozen: True

M19 Architecture PIKA Epoch [1/15]
Current LR: 0.00010000
Visual backbones frozen: True
Train Loss: 5.0342 | Main: 4.2303 | Pseudo: 4.0133 | Link: 0.0231 | Train Acc: 0.2774 | Train Macro F1: 0.0170
Val Loss  : 4.0952 | Val Acc  : 0.3848 | Val Macro Precision: 0.0553 | Val Macro Recall: 0.0459 | Val Macro F1: 0.0390
Saved best checkpoint: /content/drive/MyDrive/model/M19_arch_pika_v1/train_run/M19_arch_pika_v1_best.pth
Best Val Macro F1: 0.0390

M19 Architecture PIKA Epoch [2/15]
Current LR: 0.00009891
Visual backbones frozen: False
Rebuilt optimizer after unfreezing.
Train Loss: 3.9874 | Main: 3.3520 | Pseudo: 3.1722 | Link: 0.0197 | Train Acc: 0.4516 | Train Macro F1: 0.0938
Val Loss  : 3.0830 | Val Acc  : 0.5850 | Val Macro Precision: 0.2226 | Val Macro Recall: 0.2073 | Val Macro F1: 0.1950
Saved best checkpoint: /content/drive/MyDrive/model/M19_arch_pika_v1/train_run/M19_arch_pika_v1_best.pth
Best Val Macro F1: 0.1950

M19 Architecture PIKA Epoch [3/15]
Current LR: 0.00009875
Train Loss: 3.1162 | Main: 2.5809 | Pseudo: 2.6724 | Link: 0.0176 | Train Acc: 0.5909 | Train Macro F1: 0.2464
Val Loss  : 2.6577 | Val Acc  : 0.6510 | Val Macro Precision: 0.3462 | Val Macro Recall: 0.3003 | Val Macro F1: 0.2918
Saved best checkpoint: /content/drive/MyDrive/model/M19_arch_pika_v1/train_run/M19_arch_pika_v1_best.pth
Best Val Macro F1: 0.2918

M19 Architecture PIKA Epoch [4/15]
Current LR: 0.00009505
Train Loss: 2.5222 | Main: 2.0439 | Pseudo: 2.3875 | Link: 0.0165 | Train Acc: 0.6922 | Train Macro F1: 0.3999
Val Loss  : 2.4890 | Val Acc  : 0.6838 | Val Macro Precision: 0.4325 | Val Macro Recall: 0.3793 | Val Macro F1: 0.3827
Saved best checkpoint: /content/drive/MyDrive/model/M19_arch_pika_v1/train_run/M19_arch_pika_v1_best.pth
Best Val Macro F1: 0.3827

M19 Architecture PIKA Epoch [5/15]
Current LR: 0.00008909
Train Loss: 2.1191 | Main: 1.6822 | Pseudo: 2.1810 | Link: 0.0158 | Train Acc: 0.7560 | Train Macro F1: 0.5176
Val Loss  : 2.3074 | Val Acc  : 0.7308 | Val Macro Precision: 0.4832 | Val Macro Recall: 0.4460 | Val Macro F1: 0.4441
Saved best checkpoint: /content/drive/MyDrive/model/M19_arch_pika_v1/train_run/M19_arch_pika_v1_best.pth
Best Val Macro F1: 0.4441

M19 Architecture PIKA Epoch [6/15]
Current LR: 0.00008117
Train Loss: 1.8358 | Main: 1.4325 | Pseudo: 2.0125 | Link: 0.0152 | Train Acc: 0.8018 | Train Macro F1: 0.6082
Val Loss  : 2.2750 | Val Acc  : 0.7236 | Val Macro Precision: 0.4998 | Val Macro Recall: 0.4594 | Val Macro F1: 0.4517
Saved best checkpoint: /content/drive/MyDrive/model/M19_arch_pika_v1/train_run/M19_arch_pika_v1_best.pth
Best Val Macro F1: 0.4517

M19 Architecture PIKA Epoch [7/15]
Current LR: 0.00007169
Train Loss: 1.6321 | Main: 1.2551 | Pseudo: 1.8812 | Link: 0.0147 | Train Acc: 0.8329 | Train Macro F1: 0.6520
Val Loss  : 2.2167 | Val Acc  : 0.7334 | Val Macro Precision: 0.4693 | Val Macro Recall: 0.4527 | Val Macro F1: 0.4445
No significant improvement. bad_epochs=1/5

M19 Architecture PIKA Epoch [8/15]
Current LR: 0.00006113
Train Loss: 1.4663 | Main: 1.1151 | Pseudo: 1.7526 | Link: 0.0143 | Train Acc: 0.8614 | Train Macro F1: 0.7140
Val Loss  : 2.2087 | Val Acc  : 0.7390 | Val Macro Precision: 0.4855 | Val Macro Recall: 0.4805 | Val Macro F1: 0.4627
Saved best checkpoint: /content/drive/MyDrive/model/M19_arch_pika_v1/train_run/M19_arch_pika_v1_best.pth
Best Val Macro F1: 0.4627

M19 Architecture PIKA Epoch [9/15]
Current LR: 0.00005000
Train Loss: 1.3378 | Main: 1.0075 | Pseudo: 1.6479 | Link: 0.0139 | Train Acc: 0.8845 | Train Macro F1: 0.7493
Val Loss  : 2.2289 | Val Acc  : 0.7439 | Val Macro Precision: 0.4934 | Val Macro Recall: 0.4806 | Val Macro F1: 0.4717
Saved best checkpoint: /content/drive/MyDrive/model/M19_arch_pika_v1/train_run/M19_arch_pika_v1_best.pth
Best Val Macro F1: 0.4717

M19 Architecture PIKA Epoch [10/15]
Current LR: 0.00003887
Train Loss: 1.2315 | Main: 0.9214 | Pseudo: 1.5467 | Link: 0.0136 | Train Acc: 0.9028 | Train Macro F1: 0.7701
Val Loss  : 2.2266 | Val Acc  : 0.7431 | Val Macro Precision: 0.4928 | Val Macro Recall: 0.4826 | Val Macro F1: 0.4660
No significant improvement. bad_epochs=1/5

M19 Architecture PIKA Epoch [11/15]
Current LR: 0.00002831
Train Loss: 1.1430 | Main: 0.8526 | Pseudo: 1.4487 | Link: 0.0132 | Train Acc: 0.9187 | Train Macro F1: 0.8022
Val Loss  : 2.2242 | Val Acc  : 0.7503 | Val Macro Precision: 0.5034 | Val Macro Recall: 0.4984 | Val Macro F1: 0.4859
Saved best checkpoint: /content/drive/MyDrive/model/M19_arch_pika_v1/train_run/M19_arch_pika_v1_best.pth
Best Val Macro F1: 0.4859

M19 Architecture PIKA Epoch [12/15]
Current LR: 0.00001883
Train Loss: 1.0768 | Main: 0.8003 | Pseudo: 1.3797 | Link: 0.0130 | Train Acc: 0.9279 | Train Macro F1: 0.8148
Val Loss  : 2.2702 | Val Acc  : 0.7483 | Val Macro Precision: 0.4907 | Val Macro Recall: 0.4872 | Val Macro F1: 0.4731
No significant improvement. bad_epochs=1/5

M19 Architecture PIKA Epoch [13/15]
Current LR: 0.00001091
Train Loss: 1.0265 | Main: 0.7624 | Pseudo: 1.3173 | Link: 0.0127 | Train Acc: 0.9381 | Train Macro F1: 0.8302
Val Loss  : 2.2927 | Val Acc  : 0.7505 | Val Macro Precision: 0.5051 | Val Macro Recall: 0.4963 | Val Macro F1: 0.4852
No significant improvement. bad_epochs=2/5

M19 Architecture PIKA Epoch [14/15]
Current LR: 0.00000495
Train Loss: 1.0042 | Main: 0.7465 | Pseudo: 1.2853 | Link: 0.0126 | Train Acc: 0.9417 | Train Macro F1: 0.8365
Val Loss  : 2.2929 | Val Acc  : 0.7459 | Val Macro Precision: 0.4892 | Val Macro Recall: 0.4929 | Val Macro F1: 0.4784
No significant improvement. bad_epochs=3/5

M19 Architecture PIKA Epoch [15/15]
Current LR: 0.00000125
Train Loss: 0.9900 | Main: 0.7368 | Pseudo: 1.2629 | Link: 0.0125 | Train Acc: 0.9449 | Train Macro F1: 0.8452
Val Loss  : 2.2857 | Val Acc  : 0.7497 | Val Macro Precision: 0.5012 | Val Macro Recall: 0.5033 | Val Macro F1: 0.4907
Saved best checkpoint: /content/drive/MyDrive/model/M19_arch_pika_v1/train_run/M19_arch_pika_v1_best.pth
Best Val Macro F1: 0.4907

M19 training done.
Best checkpoint: /content/drive/MyDrive/model/M19_arch_pika_v1/train_run/M19_arch_pika_v1_best.pth
Best Val Macro F1: 0.4906840233902084
Last checkpoint: /content/drive/MyDrive/model/M19_arch_pika_v1/train_run/M19_arch_pika_v1_last.pth

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh evaluate_m19_arch_pika_v1.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 270, done.
remote: Counting objects: 100% (148/148), done.
remote: Compressing objects: 100% (126/126), done.
remote: Total 270 (delta 91), reused 22 (delta 22), pack-reused 122 (from 1)
Receiving objects: 100% (270/270), 2.61 MiB | 17.67 MiB/s, done.
Resolving deltas: 100% (146/146), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 14K May  5 14:28 evaluate_m19_arch_pika_v1.py

In [ ]:
import os

M19_EVAL_DIR = "/content/drive/MyDrive/model/M19_arch_pika_v1/test_eval"
os.makedirs(M19_EVAL_DIR, exist_ok=True)

print("M19 eval output dir:", M19_EVAL_DIR)

M19 eval output dir: /content/drive/MyDrive/model/M19_arch_pika_v1/test_eval

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python evaluate_m19_arch_pika_v1.py \
  --checkpoint /content/drive/MyDrive/model/M19_arch_pika_v1/train_run/M19_arch_pika_v1_best.pth \
  --test_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv \
  --graph_artifacts_dir /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts \
  --output_dir /content/drive/MyDrive/model/M19_arch_pika_v1/test_eval \
  --batch_size 32 \
  2>&1 | tee /content/drive/MyDrive/model/M19_arch_pika_v1/test_eval/test_log.txt

/content/vaipe-contextual-pill-recognition
=== EVALUATE M19 ARCHITECTURE PIKA V1 ===
Using device: cuda
Checkpoint: /content/drive/MyDrive/model/M19_arch_pika_v1/train_run/M19_arch_pika_v1_best.pth
Test CSV  : /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv
Graph artifacts dir: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts
Output dir: /content/drive/MyDrive/model/M19_arch_pika_v1/test_eval
Using graph embeddings: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_embeddings.npy
Num classes: 108
Max context len: 5
Graph embeddings shape: (108, 64)

Raw test rows: 4550
Raw test labels: 82
Raw test columns: ['pill_crop_path', 'pill_label', 'pill_json', 'prescription_json', 'prescription_image_path', 'context_labels', 'prescription_key', 'split', 'source_split', 'clean_split']
Test pill images existing: 4550 / 4550
Test prescription images existing: 4550 / 4550

Test rows after image check: 4550
Test labels present: 82
Test mapped label min: 1
Test mapped label max: 107
Model type        : M19ArchitecturePIKA
Pill model        : tf_efficientnetv2_s.in21k_ft_in1k
Prescription model: resnet18.a1_in1k
Hidden dim        : 256
Graph dim         : 64
Num classes       : 108
Dropout p         : 0.5
Context dropout p : 0.2
Train graph emb   : False
Evaluating M19: 100%|██████████| 143/143 [01:54<00:00,  1.24it/s]

=== M19 TEST RESULTS ===
Test Accuracy                 : 0.746813
Test Macro Precision Present  : 0.470671
Test Macro Recall Present     : 0.452737
Test Macro F1 Present Classes : 0.443011
Test Macro Precision All      : 0.422732
Test Macro Recall All         : 0.406625
Test Macro F1 All Classes     : 0.397890
Test Weighted F1              : 0.744192

Saved files:
/content/drive/MyDrive/model/M19_arch_pika_v1/test_eval/m19_test_metrics.json
/content/drive/MyDrive/model/M19_arch_pika_v1/test_eval/m19_test_predictions.csv
/content/drive/MyDrive/model/M19_arch_pika_v1/test_eval/m19_classification_report.csv
/content/drive/MyDrive/model/M19_arch_pika_v1/test_eval/m19_per_class_metrics.csv
/content/drive/MyDrive/model/M19_arch_pika_v1/test_eval/m19_confusion_matrix.csv

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh build_m20_pruned_graph_embeddings.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 273, done.
remote: Counting objects: 100% (151/151), done.
remote: Compressing objects: 100% (129/129), done.
remote: Total 273 (delta 92), reused 22 (delta 22), pack-reused 122 (from 1)
Receiving objects: 100% (273/273), 2.61 MiB | 18.69 MiB/s, done.
Resolving deltas: 100% (147/147), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 7.2K May  5 14:36 build_m20_pruned_graph_embeddings.py

Build graph prune 20%

In [ ]:
import os

M20_GRAPH_DIR = "/content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts"
os.makedirs(M20_GRAPH_DIR, exist_ok=True)

print("M20 graph output dir:", M20_GRAPH_DIR)

M20 graph output dir: /content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python build_m20_pruned_graph_embeddings.py \
  --base_graph_dir /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts \
  --output_dir /content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts \
  --prune_ratio 0.20 \
  --embedding_dim 64 \
  2>&1 | tee /content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts/build_log.txt

/content/vaipe-contextual-pill-recognition
=== M20 PRUNED GRAPH EMBEDDING BUILDER ===
Base graph dir: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts
Output dir: /content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts
Prune ratio: 0.2
Embedding dim: 64
Loaded PPMI: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_ppmi.npy
PPMI shape: (108, 108)
Num labels: 108

Pruning stats:
total_positive_offdiag_edges: 926
removed_edges: 186
remaining_positive_offdiag_edges: 740
threshold: 0.4838341772556305
prune_ratio: 0.2
keep_diagonal: True

Pruned PPMI shape: (108, 108)
Embeddings shape: (108, 64)

Saved artifacts:
/content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts/build_log.txt
/content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts/graph_edges_pruned.csv
/content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts/graph_embeddings.npy
/content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts/graph_labels.json
/content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts/graph_pmi.npy
/content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts/graph_ppmi.npy
/content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts/idx_to_label.json
/content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts/label_to_idx.json
/content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts/m20_pruned_graph_config.json
/content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts/m20_pruned_graph_summary.txt

Done.

In [ ]:
from pathlib import Path
import numpy as np
import json
import pandas as pd

gdir = Path("/content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts")

files = [
    "graph_labels.json",
    "label_to_idx.json",
    "idx_to_label.json",
    "graph_pmi.npy",
    "graph_ppmi.npy",
    "graph_embeddings.npy",
    "graph_edges_pruned.csv",
    "m20_pruned_graph_config.json",
]

for f in files:
    p = gdir / f
    print(f, "=>", p.exists(), p)

emb = np.load(gdir / "graph_embeddings.npy")
ppmi = np.load(gdir / "graph_ppmi.npy")
labels = json.load(open(gdir / "graph_labels.json", "r", encoding="utf-8"))

print("Num labels:", len(labels))
print("PPMI shape:", ppmi.shape)
print("Embedding shape:", emb.shape)

edge_df = pd.read_csv(gdir / "graph_edges_pruned.csv")
display(edge_df.head(20))

graph_labels.json => True /content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts/graph_labels.json
label_to_idx.json => True /content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts/label_to_idx.json
idx_to_label.json => True /content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts/idx_to_label.json
graph_pmi.npy => True /content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts/graph_pmi.npy
graph_ppmi.npy => True /content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts/graph_ppmi.npy
graph_embeddings.npy => True /content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts/graph_embeddings.npy
graph_edges_pruned.csv => True /content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts/graph_edges_pruned.csv
m20_pruned_graph_config.json => True /content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts/m20_pruned_graph_config.json
Num labels: 108
PPMI shape: (108, 108)
Embedding shape: (108, 64)

    src_idx  dst_idx  src_label  dst_label    weight
0        13       21         13         21  5.293305
1        35       93         35         93  5.293305
2        32       71         32         71  5.005623
3        49      101         49        101  5.005623
4        49       63         49         63  4.782479
5         5       35          5         35  4.782479
6        11       12         11         12  4.600158
7        82       98         82         98  4.600158
8         9      106          9        106  4.446007
9        22       52         22         52  4.312476
10       30       80         30         80  4.194693
11        6       30          6         30  4.194693
12       63      101         63        101  4.089332
13       11       41         11         41  3.994022
14        0      103          0        103  3.907011
15       71       82         71         82  3.907010
16        0       84          0         84  3.907010
17        3       24          3         24  3.907010
18       53       75         53         75  3.826968
19       40      100         40        100  3.801650

In [ ]:
import os

M20_TRAIN_DIR = "/content/drive/MyDrive/model/M20_graph_pruning/train_prune20"
os.makedirs(M20_TRAIN_DIR, exist_ok=True)

print("M20 train output dir:", M20_TRAIN_DIR)

M20 train output dir: /content/drive/MyDrive/model/M20_graph_pruning/train_prune20

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python train_m19_arch_pika_v1.py \
  --train_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv \
  --val_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv \
  --test_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv \
  --graph_artifacts_dir /content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts \
  --output_dir /content/drive/MyDrive/model/M20_graph_pruning/train_prune20 \
  --best_name M20_prune20_best.pth \
  --last_name M20_prune20_last.pth \
  --epochs 15 \
  --batch_size 16 \
  --lr 1e-4 \
  --class_weight_exponent 0.35 \
  --label_smoothing 0.02 \
  --pseudo_loss_weight 0.20 \
  --link_loss_weight 0.05 \
  --dropout_p 0.50 \
  --context_dropout_p 0.20 \
  --freeze_backbone_epochs 1 \
  --patience 5 \
  2>&1 | tee /content/drive/MyDrive/model/M20_graph_pruning/train_prune20/train_log.txt

/content/vaipe-contextual-pill-recognition
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
=== M19 ARCHITECTURE PIKA V1 TRAINING ===
Using device: cuda
Train CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv
Val CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv
Test CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv
Graph artifacts dir: /content/drive/MyDrive/model/M20_graph_pruning/prune20_graph_artifacts
Output dir: /content/drive/MyDrive/model/M20_graph_pruning/train_prune20
Num classes: 108
Graph embeddings shape: (108, 64)
Train pill images existing: 23189 / 23189
Train prescription images existing: 23189 / 23189
Val pill images existing: 4974 / 4974
Val prescription images existing: 4974 / 4974
Train rows: 23189
Val rows: 4974
Train labels: 108
Val labels: 89
Labels in train but missing in val: 19
[np.int64(0), np.int64(3), np.int64(4), np.int64(9), np.int64(13), np.int64(16), np.int64(20), np.int64(25), np.int64(32), np.int64(35), np.int64(44), np.int64(49), np.int64(53), np.int64(66), np.int64(85), np.int64(86), np.int64(94), np.int64(96), np.int64(102)]
Created M19ArchitecturePIKA.
Pill model: tf_efficientnetv2_s.in21k_ft_in1k
Prescription model: resnet18.a1_in1k
Graph dim: 64
Hidden dim: 256
Dropout: 0.5
Context dropout: 0.2
Train graph embeddings: False
Visual backbones frozen: True

M19 Architecture PIKA Epoch [1/15]
Current LR: 0.00010000
Visual backbones frozen: True
Train Loss: 5.0327 | Main: 4.2239 | Pseudo: 4.0380 | Link: 0.0239 | Train Acc: 0.2807 | Train Macro F1: 0.0180
Val Loss  : 4.1004 | Val Acc  : 0.3786 | Val Macro Precision: 0.0465 | Val Macro Recall: 0.0427 | Val Macro F1: 0.0367
Saved best checkpoint: /content/drive/MyDrive/model/M20_graph_pruning/train_prune20/M20_prune20_best.pth
Best Val Macro F1: 0.0367

M19 Architecture PIKA Epoch [2/15]
Current LR: 0.00009891
Visual backbones frozen: False
Rebuilt optimizer after unfreezing.
Train Loss: 3.9870 | Main: 3.3503 | Pseudo: 3.1788 | Link: 0.0201 | Train Acc: 0.4552 | Train Macro F1: 0.0947
Val Loss  : 3.1211 | Val Acc  : 0.5760 | Val Macro Precision: 0.2079 | Val Macro Recall: 0.2014 | Val Macro F1: 0.1845
Saved best checkpoint: /content/drive/MyDrive/model/M20_graph_pruning/train_prune20/M20_prune20_best.pth
Best Val Macro F1: 0.1845

M19 Architecture PIKA Epoch [3/15]
Current LR: 0.00009875
Train Loss: 3.1354 | Main: 2.5962 | Pseudo: 2.6916 | Link: 0.0181 | Train Acc: 0.5918 | Train Macro F1: 0.2405
Val Loss  : 2.6635 | Val Acc  : 0.6590 | Val Macro Precision: 0.3393 | Val Macro Recall: 0.2843 | Val Macro F1: 0.2763
Saved best checkpoint: /content/drive/MyDrive/model/M20_graph_pruning/train_prune20/M20_prune20_best.pth
Best Val Macro F1: 0.2763

M19 Architecture PIKA Epoch [4/15]
Current LR: 0.00009505
Train Loss: 2.5581 | Main: 2.0761 | Pseudo: 2.4060 | Link: 0.0170 | Train Acc: 0.6863 | Train Macro F1: 0.3818
Val Loss  : 2.4903 | Val Acc  : 0.6972 | Val Macro Precision: 0.4189 | Val Macro Recall: 0.3830 | Val Macro F1: 0.3794
Saved best checkpoint: /content/drive/MyDrive/model/M20_graph_pruning/train_prune20/M20_prune20_best.pth
Best Val Macro F1: 0.3794

M19 Architecture PIKA Epoch [5/15]
Current LR: 0.00008909
Train Loss: 2.1681 | Main: 1.7257 | Pseudo: 2.2075 | Link: 0.0162 | Train Acc: 0.7467 | Train Macro F1: 0.5011
Val Loss  : 2.3289 | Val Acc  : 0.7242 | Val Macro Precision: 0.4530 | Val Macro Recall: 0.4304 | Val Macro F1: 0.4208
Saved best checkpoint: /content/drive/MyDrive/model/M20_graph_pruning/train_prune20/M20_prune20_best.pth
Best Val Macro F1: 0.4208

M19 Architecture PIKA Epoch [6/15]
Current LR: 0.00008117
M19 Training:  66%|██████▌   | 958/1450 [08:03<03:12,  2.55it/s]

#Prune 10%

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
!pip install -q kagglehub

import kagglehub
from pathlib import Path

dataset_path = kagglehub.dataset_download("tommyngx/vaipepill2022")

print("Dataset path:", dataset_path)
print("Exists:", Path(dataset_path).exists())

Downloading to /root/.cache/kagglehub/datasets/tommyngx/vaipepill2022/1.archive...

100%|██████████| 25.2G/25.2G [23:54<00:00, 18.9MB/s]

Extracting files...

Dataset path: /root/.cache/kagglehub/datasets/tommyngx/vaipepill2022/versions/1
Exists: True

In [ ]:
from pathlib import Path
import shutil

ZIP_PATH = "/content/drive/MyDrive/VAIPE_FINAL_BACKUP/processed_pika_best.zip"

print("Zip exists:", Path(ZIP_PATH).exists(), ZIP_PATH)

!rm -rf /content/processed_pika_best
!rm -rf /content/_processed_pika_unzip
!mkdir -p /content/_processed_pika_unzip

!unzip -q "$ZIP_PATH" -d /content/_processed_pika_unzip

tmp = Path("/content/_processed_pika_unzip")

print("Extracted top-level items:")
for p in list(tmp.glob("*"))[:30]:
    print(p)

graph_files = list(tmp.rglob("graph_labels.json"))
print("\nFound graph_labels.json:", graph_files[:5])

if len(graph_files) == 0:
    raise FileNotFoundError("Không tìm thấy graph_labels.json trong processed_pika_best.zip")

src_root = graph_files[0].parent
print("Detected processed root:", src_root)

shutil.copytree(src_root, "/content/processed_pika_best")

print("\nDone.")
print("Data root:", Path("/content/processed_pika_best").exists())
print("Graph labels:", Path("/content/processed_pika_best/graph_labels.json").exists())
print("Graph PMI:", Path("/content/processed_pika_best/graph_pmi.npy").exists())

Zip exists: True /content/drive/MyDrive/VAIPE_FINAL_BACKUP/processed_pika_best.zip
error:  zipfile read error
Extracted top-level items:
/content/_processed_pika_unzip/pill_crops
/content/_processed_pika_unzip/best_pika_metadata.csv
/content/_processed_pika_unzip/graph_pmi.npy
/content/_processed_pika_unzip/graph_labels.json

Found graph_labels.json: [PosixPath('/content/_processed_pika_unzip/graph_labels.json')]
Detected processed root: /content/_processed_pika_unzip

Done.
Data root: True
Graph labels: True
Graph PMI: True

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 273, done.
remote: Counting objects: 100% (151/151), done.
remote: Compressing objects: 100% (129/129), done.
remote: Total 273 (delta 92), reused 22 (delta 22), pack-reused 122 (from 1)
Receiving objects: 100% (273/273), 2.61 MiB | 12.09 MiB/s, done.
Resolving deltas: 100% (147/147), done.
/content/vaipe-contextual-pill-recognition
total 4.3M
-rw-r--r-- 1 root root 9.0K May  6 10:56  analyze_m13_errors.py
-rw-r--r-- 1 root root 7.6K May  6 10:56  build_best_pika_data.py
-rw-r--r-- 1 root root  14K May  6 10:56  build_m17_pika_graph_embeddings.py
-rw-r--r-- 1 root root 7.2K May  6 10:56  build_m20_pruned_graph_embeddings.py
-rw-r--r-- 1 root root 5.4K May  6 10:56  build_pika_context_metadata.py
-rw-r--r-- 1 root root 6.6K May  6 10:56  build_pika_graph_data.py
-rw-r--r-- 1 root root 4.4K May  6 10:56  build_pika_metadata.py
-rw-r--r-- 1 root root 5.7K May  6 10:56  build_pika_v3_metadata.py
-rw-r--r-- 1 root root 2.9K May  6 10:56  build_split_metadata.py
-rw-r--r-- 1 root root  19K May  6 10:56  calibrate_m14_prior_corrected_ensemble.py
-rw-r--r-- 1 root root  18K May  6 10:56  create_clean_paper_like_split.py
-rw-r--r-- 1 root root 5.7K May  6 10:56  create_stratified_split_v2.py
-rw-r--r-- 1 root root 6.5K May  6 10:56  detect_public_test_faster_rcnn.py
-rw-r--r-- 1 root root  13K May  6 10:56  evaluate_best_pika_checkpoint_m12.py
-rw-r--r-- 1 root root  17K May  6 10:56  evaluate_ensemble_m10_m11.py
-rw-r--r-- 1 root root  13K May  6 10:56  evaluate_m17_faithful_pika.py
-rw-r--r-- 1 root root  14K May  6 10:56  evaluate_m19_arch_pika_v1.py
-rw-r--r-- 1 root root 7.0K May  6 10:56  evaluate_m2_split_test.py
-rw-r--r-- 1 root root 7.7K May  6 10:56  evaluate_m3_split_test.py
-rw-r--r-- 1 root root 7.6K May  6 10:56  evaluate_m4_split_test.py
-rw-r--r-- 1 root root 8.5K May  6 10:56  evaluate_m5_split_test.py
-rw-r--r-- 1 root root 8.6K May  6 10:56  evaluate_m6_split_test.py
-rw-r--r-- 1 root root  20K May  6 10:56  evaluate_public_test.py
-rw-r--r-- 1 root root  11K May  6 10:56  evaluate_split_test.py
-rw-r--r-- 1 root root  15K May  6 10:56  finetune_best_pika_model.py
-rw-r--r-- 1 root root  15K May  6 10:56  finetune_best_pika_model_v2.py
-rw-r--r-- 1 root root  15K May  6 10:56  finetune_best_pika_model_v3.py
-rw-r--r-- 1 root root  16K May  6 10:56  finetune_best_pika_model_v4.py
-rw-r--r-- 1 root root 2.3K May  6 10:56  finetune_best_pika_model_v5.py
-rw-r--r-- 1 root root  19K May  6 10:56  finetune_best_pika_model_v6_m12_stratified_balanced_focal.py
-rw-r--r-- 1 root root 1.2M May  6 10:56  history_ketqua_project.ipynb
-rw-r--r-- 1 root root 2.5M May  6 10:56 'history_ketqua_project_(update_to_13_4).ipynb'
-rw-r--r-- 1 root root  26K May  6 10:56  m15_pairwise_topk_correction.py
-rw-r--r-- 1 root root  16K May  6 10:56  make_prescription_split.py
-rw-r--r-- 1 root root  11K May  6 10:56  model_registry_m1_m9.py
-rw-r--r-- 1 root root 3.4K May  6 10:56  prepare_cropped_dataset.py
-rw-r--r-- 1 root root  16K May  6 10:56  README.md
-rw-r--r-- 1 root root   72 May  6 10:56  requirements.txt
-rw-r--r-- 1 root root  31K May  6 10:56  run_m1_m9_on_detected_crops.py
-rw-r--r-- 1 root root  14K May  6 10:56  train_baseline.py
-rw-r--r-- 1 root root  22K May  6 10:56  train_best_pika_model.py
-rw-r--r-- 1 root root 9.1K May  6 10:56  train_faster_rcnn_vaipe.py
-rw-r--r-- 1 root root  18K May  6 10:56  train_m16_clean_best_pika.py
-rw-r--r-- 1 root root  25K May  6 10:56  train_m17_faithful_pika.py
-rw-r--r-- 1 root root  15K May  6 10:56  train_m17_faithful_pika_resume.py
-rw-r--r-- 1 root root  17K May  6 10:56  train_m18_improved_pika.py
-rw-r--r-- 1 root root  26K May  6 10:56  train_m19_arch_pika_v1.py
-rw-r--r-- 1 root root  15K May  6 10:56  train_pika_baseline.py
-rw-r--r-- 1 root root  22K May  6 10:56  train_pika_graph.py
-rw-r--r-- 1 root root  11K May  6 10:56  train_pika_v1_1_improved.py
-rw-r--r-- 1 root root  19K May  6 10:56  train_pika_v2_context_labels.py
-rw-r--r-- 1 root root  18K May  6 10:56  train_pika_v3_triple_context.py
-rw-r--r-- 1 root root 7.2K May  6 10:56  vaipe_detection_dataset.py

In [ ]:
!ls -lh build_m20_pruned_graph_embeddings.py train_m19_arch_pika_v1.py

-rw-r--r-- 1 root root 7.2K May  6 10:56 build_m20_pruned_graph_embeddings.py
-rw-r--r-- 1 root root  26K May  6 10:56 train_m19_arch_pika_v1.py

In [ ]:
import pandas as pd
from pathlib import Path

train_csv = "/content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv"
val_csv = "/content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv"

for name, csv_path in [("train", train_csv), ("val", val_csv)]:
    df = pd.read_csv(csv_path)
    df["pill_exists"] = df["pill_crop_path"].apply(lambda p: Path(str(p)).exists())
    df["pres_exists"] = df["prescription_image_path"].apply(lambda p: Path(str(p)).exists())

    print("\n===", name, "===")
    print("rows:", len(df))
    print("pill existing:", int(df["pill_exists"].sum()), "/", len(df))
    print("pres existing:", int(df["pres_exists"].sum()), "/", len(df))

    missing = df[~df["pill_exists"]]
    print("\nMissing pill examples:")
    print(missing[["pill_crop_path", "pill_label", "prescription_key", "source_split"]].head(10).to_string(index=False))

    if "source_split" in df.columns:
        print("\nPill exists by source_split:")
        display(
            df.groupby("source_split")["pill_exists"]
            .agg(["count", "sum"])
            .assign(missing=lambda x: x["count"] - x["sum"])
        )

=== train ===
rows: 23189
pill existing: 9647 / 23189
pres existing: 23189 / 23189

Missing pill examples:
                                               pill_crop_path  pill_label prescription_key source_split
 /content/processed_pika_best/pill_crops/VAIPE_P_0_0_box1.jpg          64  VAIPE_P_TRAIN_0    old_train
 /content/processed_pika_best/pill_crops/VAIPE_P_0_1_box0.jpg          64  VAIPE_P_TRAIN_0    old_train
 /content/processed_pika_best/pill_crops/VAIPE_P_0_1_box1.jpg          64  VAIPE_P_TRAIN_0    old_train
/content/processed_pika_best/pill_crops/VAIPE_P_0_10_box1.jpg          64  VAIPE_P_TRAIN_0    old_train
/content/processed_pika_best/pill_crops/VAIPE_P_0_11_box0.jpg          64  VAIPE_P_TRAIN_0    old_train
/content/processed_pika_best/pill_crops/VAIPE_P_0_12_box0.jpg          64  VAIPE_P_TRAIN_0    old_train
/content/processed_pika_best/pill_crops/VAIPE_P_0_12_box1.jpg          64  VAIPE_P_TRAIN_0    old_train
/content/processed_pika_best/pill_crops/VAIPE_P_0_12_box2.jpg          47  VAIPE_P_TRAIN_0    old_train
/content/processed_pika_best/pill_crops/VAIPE_P_0_13_box0.jpg          64  VAIPE_P_TRAIN_0    old_train
/content/processed_pika_best/pill_crops/VAIPE_P_0_13_box1.jpg          64  VAIPE_P_TRAIN_0    old_train

Pill exists by source_split:

              count   sum  missing
source_split
old_test       4024  1676     2348
old_train     15785  6555     9230
old_val        3380  1416     1964

=== val ===
rows: 4974
pill existing: 2004 / 4974
pres existing: 4974 / 4974

Missing pill examples:
                                                 pill_crop_path  pill_label   prescription_key source_split
/content/processed_pika_best/pill_crops/VAIPE_P_1011_0_box0.jpg          19 VAIPE_P_TRAIN_1011    old_train
/content/processed_pika_best/pill_crops/VAIPE_P_1011_0_box3.jpg          91 VAIPE_P_TRAIN_1011    old_train
/content/processed_pika_best/pill_crops/VAIPE_P_1011_1_box0.jpg         104 VAIPE_P_TRAIN_1011    old_train
/content/processed_pika_best/pill_crops/VAIPE_P_1011_1_box1.jpg          19 VAIPE_P_TRAIN_1011    old_train
/content/processed_pika_best/pill_crops/VAIPE_P_1011_1_box2.jpg          71 VAIPE_P_TRAIN_1011    old_train
/content/processed_pika_best/pill_crops/VAIPE_P_1011_1_box3.jpg          91 VAIPE_P_TRAIN_1011    old_train
/content/processed_pika_best/pill_crops/VAIPE_P_1011_2_box1.jpg         104 VAIPE_P_TRAIN_1011    old_train
/content/processed_pika_best/pill_crops/VAIPE_P_1011_2_box2.jpg          91 VAIPE_P_TRAIN_1011    old_train
/content/processed_pika_best/pill_crops/VAIPE_P_1011_2_box3.jpg          71 VAIPE_P_TRAIN_1011    old_train
/content/processed_pika_best/pill_crops/VAIPE_P_1011_3_box1.jpg         104 VAIPE_P_TRAIN_1011    old_train

Pill exists by source_split:

              count   sum  missing
source_split
old_test       1128   488      640
old_train      3246  1270     1976
old_val         600   246      354

In [ ]:
from pathlib import Path

root = Path("/content/processed_pika_best")

print("processed exists:", root.exists())
print("graph_labels:", (root / "graph_labels.json").exists())
print("graph_pmi:", (root / "graph_pmi.npy").exists())

if root.exists():
    print("\nTop-level folders/files:")
    for p in list(root.iterdir())[:50]:
        print(p)

    print("\nTotal files:")
    !find /content/processed_pika_best -type f | wc -l

    print("\nExample crop files:")
    !find /content/processed_pika_best -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" \) | head -30

processed exists: True
graph_labels: True
graph_pmi: True

Top-level folders/files:
/content/processed_pika_best/pill_crops
/content/processed_pika_best/best_pika_metadata.csv
/content/processed_pika_best/graph_pmi.npy
/content/processed_pika_best/graph_labels.json

Total files:
13621

Example crop files:
/content/processed_pika_best/pill_crops/VAIPE_P_1092_2_box1.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_872_5_box0.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_595_5_box0.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_180_9_box0.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_482_21_box1.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_247_19_box1.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_233_0_box1.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_353_33_box3.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_107_1_box0.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_809_0_box3.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_893_5_box5.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_77_14_box0.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_270_2_box1.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_727_0_box0.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_487_4_box0.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_1081_2_box0.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_350_2_box0.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_753_1_box4.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_371_4_box0.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_1038_10_box2.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_543_0_box1.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_102_18_box1.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_528_1_box0.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_140_5_box1.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_464_18_box5.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_693_0_box5.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_174_3_box4.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_180_13_box1.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_313_26_box2.jpg
/content/processed_pika_best/pill_crops/VAIPE_P_2_5_box0.jpg

In [ ]:
from pathlib import Path
import shutil

ZIP_PATH = "/content/drive/MyDrive/VAIPE_FINAL_BACKUP/processed_pika_best.zip"

print("Zip exists:", Path(ZIP_PATH).exists(), ZIP_PATH)
print("Zip size GB:", round(Path(ZIP_PATH).stat().st_size / 1024**3, 3) if Path(ZIP_PATH).exists() else None)

!rm -rf /content/processed_pika_best
!rm -rf /content/_processed_pika_unzip
!mkdir -p /content/_processed_pika_unzip

!unzip -q "$ZIP_PATH" -d /content/_processed_pika_unzip

tmp = Path("/content/_processed_pika_unzip")

print("\nExtracted top-level items:")
for p in list(tmp.glob("*"))[:30]:
    print(p)

graph_files = list(tmp.rglob("graph_labels.json"))
print("\nFound graph_labels.json:")
for p in graph_files[:10]:
    print(p)

if len(graph_files) == 0:
    raise FileNotFoundError("Không tìm thấy graph_labels.json trong processed_pika_best.zip")

# Chọn root chứa graph_labels.json và nhiều file nhất
candidates = []
for gf in graph_files:
    parent = gf.parent
    num_files = sum(1 for _ in parent.rglob("*") if _.is_file())
    candidates.append((num_files, parent))

candidates = sorted(candidates, reverse=True)
src_root = candidates[0][1]

print("\nDetected processed root:", src_root)
print("Files under detected root:", candidates[0][0])

shutil.copytree(src_root, "/content/processed_pika_best")

print("\nDone.")
print("Data root:", Path("/content/processed_pika_best").exists())
print("Graph labels:", Path("/content/processed_pika_best/graph_labels.json").exists())
print("Graph PMI:", Path("/content/processed_pika_best/graph_pmi.npy").exists())

print("\nTotal files after restore:")
!find /content/processed_pika_best -type f | wc -l

Zip exists: True /content/drive/MyDrive/VAIPE_FINAL_BACKUP/processed_pika_best.zip
Zip size GB: 0.652

Extracted top-level items:
/content/_processed_pika_unzip/pill_crops
/content/_processed_pika_unzip/best_pika_metadata.csv
/content/_processed_pika_unzip/graph_pmi.npy
/content/_processed_pika_unzip/graph_labels.json

Found graph_labels.json:
/content/_processed_pika_unzip/graph_labels.json

Detected processed root: /content/_processed_pika_unzip
Files under detected root: 32716

Done.
Data root: True
Graph labels: True
Graph PMI: True

Total files after restore:
32716

In [ ]:
import pandas as pd
from pathlib import Path

csvs = {
    "train": "/content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv",
    "val": "/content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv",
    "test": "/content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv",
}

for name, csv_path in csvs.items():
    df = pd.read_csv(csv_path)

    print("\n====================")
    print("SPLIT:", name)
    print("====================")
    print("CSV rows:", len(df))
    print("Labels:", df["pill_label"].nunique())

    for col in ["pill_crop_path", "prescription_image_path"]:
        exists = df[col].apply(lambda p: Path(str(p)).exists())
        print(f"{col} existing:", int(exists.sum()), "/", len(df))
        print(f"{col} missing:", int((~exists).sum()))

====================
SPLIT: train
====================
CSV rows: 23189
Labels: 108
pill_crop_path existing: 23189 / 23189
pill_crop_path missing: 0
prescription_image_path existing: 23189 / 23189
prescription_image_path missing: 0

====================
SPLIT: val
====================
CSV rows: 4974
Labels: 89
pill_crop_path existing: 4974 / 4974
pill_crop_path missing: 0
prescription_image_path existing: 4974 / 4974
prescription_image_path missing: 0

====================
SPLIT: test
====================
CSV rows: 4550
Labels: 82
pill_crop_path existing: 4550 / 4550
pill_crop_path missing: 0
prescription_image_path existing: 4550 / 4550
prescription_image_path missing: 0

In [ ]:
import os

M20_GRAPH_DIR = "/content/drive/MyDrive/model/M20_graph_pruning/prune10_graph_artifacts"
os.makedirs(M20_GRAPH_DIR, exist_ok=True)

print("M20 prune10 graph output dir:", M20_GRAPH_DIR)

M20 prune10 graph output dir: /content/drive/MyDrive/model/M20_graph_pruning/prune10_graph_artifacts

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python build_m20_pruned_graph_embeddings.py \
  --base_graph_dir /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts \
  --output_dir /content/drive/MyDrive/model/M20_graph_pruning/prune10_graph_artifacts \
  --prune_ratio 0.10 \
  --embedding_dim 64 \
  2>&1 | tee /content/drive/MyDrive/model/M20_graph_pruning/prune10_graph_artifacts/build_log.txt

/content/vaipe-contextual-pill-recognition
=== M20 PRUNED GRAPH EMBEDDING BUILDER ===
Base graph dir: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts
Output dir: /content/drive/MyDrive/model/M20_graph_pruning/prune10_graph_artifacts
Prune ratio: 0.1
Embedding dim: 64
Loaded PPMI: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_ppmi.npy
PPMI shape: (108, 108)
Num labels: 108

Pruning stats:
total_positive_offdiag_edges: 926
removed_edges: 96
remaining_positive_offdiag_edges: 830
threshold: 0.18735934793949127
prune_ratio: 0.1
keep_diagonal: True

Pruned PPMI shape: (108, 108)
Embeddings shape: (108, 64)

Saved artifacts:
/content/drive/MyDrive/model/M20_graph_pruning/prune10_graph_artifacts/build_log.txt
/content/drive/MyDrive/model/M20_graph_pruning/prune10_graph_artifacts/graph_edges_pruned.csv
/content/drive/MyDrive/model/M20_graph_pruning/prune10_graph_artifacts/graph_embeddings.npy
/content/drive/MyDrive/model/M20_graph_pruning/prune10_graph_artifacts/graph_labels.json
/content/drive/MyDrive/model/M20_graph_pruning/prune10_graph_artifacts/graph_pmi.npy
/content/drive/MyDrive/model/M20_graph_pruning/prune10_graph_artifacts/graph_ppmi.npy
/content/drive/MyDrive/model/M20_graph_pruning/prune10_graph_artifacts/idx_to_label.json
/content/drive/MyDrive/model/M20_graph_pruning/prune10_graph_artifacts/label_to_idx.json
/content/drive/MyDrive/model/M20_graph_pruning/prune10_graph_artifacts/m20_pruned_graph_config.json
/content/drive/MyDrive/model/M20_graph_pruning/prune10_graph_artifacts/m20_pruned_graph_summary.txt

Done.

In [ ]:
import os

M20_TRAIN_DIR = "/content/drive/MyDrive/model/M20_graph_pruning/train_prune10"
os.makedirs(M20_TRAIN_DIR, exist_ok=True)

print("M20 prune10 train output dir:", M20_TRAIN_DIR)

M20 prune10 train output dir: /content/drive/MyDrive/model/M20_graph_pruning/train_prune10

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python train_m19_arch_pika_v1.py \
  --train_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv \
  --val_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv \
  --test_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv \
  --graph_artifacts_dir /content/drive/MyDrive/model/M20_graph_pruning/prune10_graph_artifacts \
  --output_dir /content/drive/MyDrive/model/M20_graph_pruning/train_prune10 \
  --best_name M20_prune10_best.pth \
  --last_name M20_prune10_last.pth \
  --epochs 15 \
  --batch_size 16 \
  --lr 1e-4 \
  --class_weight_exponent 0.35 \
  --label_smoothing 0.02 \
  --pseudo_loss_weight 0.20 \
  --link_loss_weight 0.05 \
  --dropout_p 0.50 \
  --context_dropout_p 0.20 \
  --freeze_backbone_epochs 1 \
  --patience 5 \
  2>&1 | tee /content/drive/MyDrive/model/M20_graph_pruning/train_prune10/train_log.txt

/content/vaipe-contextual-pill-recognition
=== M19 ARCHITECTURE PIKA V1 TRAINING ===
Using device: cuda
Train CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv
Val CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv
Test CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv
Graph artifacts dir: /content/drive/MyDrive/model/M20_graph_pruning/prune10_graph_artifacts
Output dir: /content/drive/MyDrive/model/M20_graph_pruning/train_prune10
Num classes: 108
Graph embeddings shape: (108, 64)
Train pill images existing: 23189 / 23189
Train prescription images existing: 23189 / 23189
Val pill images existing: 4974 / 4974
Val prescription images existing: 4974 / 4974
Train rows: 23189
Val rows: 4974
Train labels: 108
Val labels: 89
Labels in train but missing in val: 19
[np.int64(0), np.int64(3), np.int64(4), np.int64(9), np.int64(13), np.int64(16), np.int64(20), np.int64(25), np.int64(32), np.int64(35), np.int64(44), np.int64(49), np.int64(53), np.int64(66), np.int64(85), np.int64(86), np.int64(94), np.int64(96), np.int64(102)]
Created M19ArchitecturePIKA.
Pill model: tf_efficientnetv2_s.in21k_ft_in1k
Prescription model: resnet18.a1_in1k
Graph dim: 64
Hidden dim: 256
Dropout: 0.5
Context dropout: 0.2
Train graph embeddings: False
Visual backbones frozen: True

M19 Architecture PIKA Epoch [1/15]
Current LR: 0.00010000
Visual backbones frozen: True
Train Loss: 5.0288 | Main: 4.2217 | Pseudo: 4.0293 | Link: 0.0234 | Train Acc: 0.2769 | Train Macro F1: 0.0185
Val Loss  : 4.1069 | Val Acc  : 0.3820 | Val Macro Precision: 0.0573 | Val Macro Recall: 0.0474 | Val Macro F1: 0.0434
Saved best checkpoint: /content/drive/MyDrive/model/M20_graph_pruning/train_prune10/M20_prune10_best.pth
Best Val Macro F1: 0.0434

M19 Architecture PIKA Epoch [2/15]
Current LR: 0.00009891
Visual backbones frozen: False
Rebuilt optimizer after unfreezing.
Train Loss: 3.9668 | Main: 3.3310 | Pseudo: 3.1737 | Link: 0.0200 | Train Acc: 0.4593 | Train Macro F1: 0.1003
Val Loss  : 3.1004 | Val Acc  : 0.5804 | Val Macro Precision: 0.1873 | Val Macro Recall: 0.1913 | Val Macro F1: 0.1779
Saved best checkpoint: /content/drive/MyDrive/model/M20_graph_pruning/train_prune10/M20_prune10_best.pth
Best Val Macro F1: 0.1779

M19 Architecture PIKA Epoch [3/15]
Current LR: 0.00009875
Train Loss: 3.1030 | Main: 2.5685 | Pseudo: 2.6681 | Link: 0.0178 | Train Acc: 0.5960 | Train Macro F1: 0.2488
Val Loss  : 2.6902 | Val Acc  : 0.6562 | Val Macro Precision: 0.3609 | Val Macro Recall: 0.3030 | Val Macro F1: 0.2983
Saved best checkpoint: /content/drive/MyDrive/model/M20_graph_pruning/train_prune10/M20_prune10_best.pth
Best Val Macro F1: 0.2983

M19 Architecture PIKA Epoch [4/15]
Current LR: 0.00009505
Train Loss: 2.5249 | Main: 2.0476 | Pseudo: 2.3825 | Link: 0.0167 | Train Acc: 0.6877 | Train Macro F1: 0.3970
Val Loss  : 2.5115 | Val Acc  : 0.6755 | Val Macro Precision: 0.4407 | Val Macro Recall: 0.3677 | Val Macro F1: 0.3734
Saved best checkpoint: /content/drive/MyDrive/model/M20_graph_pruning/train_prune10/M20_prune10_best.pth
Best Val Macro F1: 0.3734

M19 Architecture PIKA Epoch [5/15]
Current LR: 0.00008909
Train Loss: 2.1276 | Main: 1.6920 | Pseudo: 2.1737 | Link: 0.0159 | Train Acc: 0.7501 | Train Macro F1: 0.5100
Val Loss  : 2.3341 | Val Acc  : 0.7145 | Val Macro Precision: 0.4612 | Val Macro Recall: 0.4111 | Val Macro F1: 0.4136
Saved best checkpoint: /content/drive/MyDrive/model/M20_graph_pruning/train_prune10/M20_prune10_best.pth
Best Val Macro F1: 0.4136

M19 Architecture PIKA Epoch [6/15]
Current LR: 0.00008117
M19 Training:  10%|▉         | 142/1450 [01:15<09:07,  2.39it/s]

Ý tưởng M21:

Giữ hướng PIKA/context/graph của M19
Nhưng thay kiến trúc mạnh hơn:
- Pill encoder mạnh hơn: convnext_tiny.in12k_ft_in1k
- Projection lớn hơn: common_dim = 128
- Fusion giàu hơn M19
- Multi-sample dropout classifier
- Context attention mạnh hơn
- Context length tăng từ 5 lên 8
- Có pseudo loss + graph alignment loss

Mục tiêu: vượt M19 validation 0.4907 trước, sau đó mới test.

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh train_m21_strong_visual_pika.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 276, done.
remote: Counting objects: 100% (154/154), done.
remote: Compressing objects: 100% (132/132), done.
remote: Total 276 (delta 93), reused 22 (delta 22), pack-reused 122 (from 1)
Receiving objects: 100% (276/276), 2.61 MiB | 11.79 MiB/s, done.
Resolving deltas: 100% (148/148), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 28K May  6 12:16 train_m21_strong_visual_pika.py

In [ ]:
import os

M21_DIR = "/content/drive/MyDrive/model/M21_strong_visual_pika/train_run"
os.makedirs(M21_DIR, exist_ok=True)

print("M21 output dir:", M21_DIR)

M21 output dir: /content/drive/MyDrive/model/M21_strong_visual_pika/train_run

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python train_m21_strong_visual_pika.py \
  --train_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv \
  --val_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv \
  --test_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv \
  --graph_artifacts_dir /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts \
  --output_dir /content/drive/MyDrive/model/M21_strong_visual_pika/train_run \
  --epochs 15 \
  --batch_size 12 \
  --lr 8e-5 \
  --class_weight_exponent 0.35 \
  --label_smoothing 0.02 \
  --pseudo_loss_weight 0.20 \
  --link_loss_weight 0.05 \
  --dropout_p 0.50 \
  --context_dropout_p 0.25 \
  --max_context_len 8 \
  --common_dim 128 \
  --hidden_dim 384 \
  --freeze_backbone_epochs 1 \
  --patience 5 \
  2>&1 | tee /content/drive/MyDrive/model/M21_strong_visual_pika/train_run/train_log.txt

/content/vaipe-contextual-pill-recognition
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
=== M21 STRONG VISUAL PIKA TRAINING ===
Using device: cuda
Train CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv
Val CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv
Test CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv
Graph artifacts dir: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts
Output dir: /content/drive/MyDrive/model/M21_strong_visual_pika/train_run
Num classes: 108
Graph embeddings shape: (108, 64)
Train pill images existing: 23189 / 23189
Train prescription images existing: 23189 / 23189
Val pill images existing: 4974 / 4974
Val prescription images existing: 4974 / 4974
Train rows: 23189
Val rows: 4974
Train labels: 108
Val labels: 89
Labels in train but missing in val: 19
[np.int64(0), np.int64(3), np.int64(4), np.int64(9), np.int64(13), np.int64(16), np.int64(20), np.int64(25), np.int64(32), np.int64(35), np.int64(44), np.int64(49), np.int64(53), np.int64(66), np.int64(85), np.int64(86), np.int64(94), np.int64(96), np.int64(102)]
Created M21StrongVisualPIKA.
Pill model: convnext_tiny.in12k_ft_in1k
Prescription model: resnet18.a1_in1k
Common dim: 128
Hidden dim: 384
Dropout: 0.5
Context dropout: 0.25
Max context len: 8
Train graph embeddings: False
Visual backbones frozen: True
Total params: 41324557
Trainable params: 2321005

M21 Strong Visual PIKA Epoch [1/15]
Current LR: 0.00008000
Visual backbones frozen: True
Train Loss: 4.4678 | Main: 3.6642 | Pseudo: 4.0143 | Link: 0.0132 | Train Acc: 0.3663 | Train Macro F1: 0.0690
Val Loss  : 3.4671 | Val Acc  : 0.4962 | Val Macro Precision: 0.1973 | Val Macro Recall: 0.1551 | Val Macro F1: 0.1482
Saved best checkpoint: /content/drive/MyDrive/model/M21_strong_visual_pika/train_run/M21_strong_visual_pika_best.pth
Best Val Macro F1: 0.1482

M21 Strong Visual PIKA Epoch [2/15]
Current LR: 0.00007913
Visual backbones frozen: False
Rebuilt optimizer after unfreezing.
Train Loss: 3.2335 | Main: 2.5708 | Pseudo: 3.3106 | Link: 0.0113 | Train Acc: 0.5430 | Train Macro F1: 0.2639
Val Loss  : 2.8703 | Val Acc  : 0.6078 | Val Macro Precision: 0.3426 | Val Macro Recall: 0.2936 | Val Macro F1: 0.2869
Saved best checkpoint: /content/drive/MyDrive/model/M21_strong_visual_pika/train_run/M21_strong_visual_pika_best.pth
Best Val Macro F1: 0.2869

M21 Strong Visual PIKA Epoch [3/15]
Current LR: 0.00007900
Train Loss: 2.2830 | Main: 1.7398 | Pseudo: 2.7135 | Link: 0.0097 | Train Acc: 0.6958 | Train Macro F1: 0.4946
Val Loss  : 2.4382 | Val Acc  : 0.6566 | Val Macro Precision: 0.4091 | Val Macro Recall: 0.3641 | Val Macro F1: 0.3636
Saved best checkpoint: /content/drive/MyDrive/model/M21_strong_visual_pika/train_run/M21_strong_visual_pika_best.pth
Best Val Macro F1: 0.3636

M21 Strong Visual PIKA Epoch [4/15]
Current LR: 0.00007604
Train Loss: 1.8086 | Main: 1.3294 | Pseudo: 2.3938 | Link: 0.0089 | Train Acc: 0.7733 | Train Macro F1: 0.6364
Val Loss  : 2.3435 | Val Acc  : 0.7016 | Val Macro Precision: 0.4719 | Val Macro Recall: 0.4315 | Val Macro F1: 0.4174
Saved best checkpoint: /content/drive/MyDrive/model/M21_strong_visual_pika/train_run/M21_strong_visual_pika_best.pth
Best Val Macro F1: 0.4174

M21 Strong Visual PIKA Epoch [5/15]
Current LR: 0.00007127
Train Loss: 1.5287 | Main: 1.0954 | Pseudo: 2.1645 | Link: 0.0083 | Train Acc: 0.8258 | Train Macro F1: 0.7107
Val Loss  : 2.2862 | Val Acc  : 0.7023 | Val Macro Precision: 0.5109 | Val Macro Recall: 0.4298 | Val Macro F1: 0.4350
Saved best checkpoint: /content/drive/MyDrive/model/M21_strong_visual_pika/train_run/M21_strong_visual_pika_best.pth
Best Val Macro F1: 0.4350

M21 Strong Visual PIKA Epoch [6/15]
Current LR: 0.00006494
Train Loss: 1.3168 | Main: 0.9201 | Pseudo: 1.9816 | Link: 0.0078 | Train Acc: 0.8652 | Train Macro F1: 0.7685
Val Loss  : 2.2705 | Val Acc  : 0.7153 | Val Macro Precision: 0.4782 | Val Macro Recall: 0.4086 | Val Macro F1: 0.4134
No significant improvement. bad_epochs=1/5

M21 Strong Visual PIKA Epoch [7/15]
Current LR: 0.00005736
Train Loss: 1.1716 | Main: 0.8072 | Pseudo: 1.8200 | Link: 0.0073 | Train Acc: 0.8936 | Train Macro F1: 0.8121
Val Loss  : 2.1927 | Val Acc  : 0.7407 | Val Macro Precision: 0.5069 | Val Macro Recall: 0.4730 | Val Macro F1: 0.4683
Saved best checkpoint: /content/drive/MyDrive/model/M21_strong_visual_pika/train_run/M21_strong_visual_pika_best.pth
Best Val Macro F1: 0.4683

M21 Strong Visual PIKA Epoch [8/15]
Current LR: 0.00004890
Train Loss: 1.0444 | Main: 0.7103 | Pseudo: 1.6688 | Link: 0.0069 | Train Acc: 0.9170 | Train Macro F1: 0.8497
Val Loss  : 2.2234 | Val Acc  : 0.7467 | Val Macro Precision: 0.5070 | Val Macro Recall: 0.4535 | Val Macro F1: 0.4592
No significant improvement. bad_epochs=1/5

M21 Strong Visual PIKA Epoch [9/15]
Current LR: 0.00004000
Train Loss: 0.9319 | Main: 0.6279 | Pseudo: 1.5186 | Link: 0.0065 | Train Acc: 0.9399 | Train Macro F1: 0.8907
Val Loss  : 2.1579 | Val Acc  : 0.7616 | Val Macro Precision: 0.5355 | Val Macro Recall: 0.5043 | Val Macro F1: 0.4972
Saved best checkpoint: /content/drive/MyDrive/model/M21_strong_visual_pika/train_run/M21_strong_visual_pika_best.pth
Best Val Macro F1: 0.4972

M21 Strong Visual PIKA Epoch [10/15]
Current LR: 0.00003110
Train Loss: 0.8540 | Main: 0.5798 | Pseudo: 1.3698 | Link: 0.0061 | Train Acc: 0.9514 | Train Macro F1: 0.9081
Val Loss  : 2.1364 | Val Acc  : 0.7672 | Val Macro Precision: 0.5467 | Val Macro Recall: 0.5095 | Val Macro F1: 0.5110
Saved best checkpoint: /content/drive/MyDrive/model/M21_strong_visual_pika/train_run/M21_strong_visual_pika_best.pth
Best Val Macro F1: 0.5110

M21 Strong Visual PIKA Epoch [11/15]
Current LR: 0.00002264
Train Loss: 0.7707 | Main: 0.5243 | Pseudo: 1.2308 | Link: 0.0058 | Train Acc: 0.9674 | Train Macro F1: 0.9300
Val Loss  : 2.1819 | Val Acc  : 0.7618 | Val Macro Precision: 0.5218 | Val Macro Recall: 0.5131 | Val Macro F1: 0.5014
No significant improvement. bad_epochs=1/5

M21 Strong Visual PIKA Epoch [12/15]
Current LR: 0.00001506
Train Loss: 0.7071 | Main: 0.4880 | Pseudo: 1.0940 | Link: 0.0055 | Train Acc: 0.9766 | Train Macro F1: 0.9416
Val Loss  : 2.2180 | Val Acc  : 0.7604 | Val Macro Precision: 0.5351 | Val Macro Recall: 0.5164 | Val Macro F1: 0.5102
No significant improvement. bad_epochs=2/5

M21 Strong Visual PIKA Epoch [13/15]
Current LR: 0.00000873
Train Loss: 0.6592 | Main: 0.4622 | Pseudo: 0.9835 | Link: 0.0052 | Train Acc: 0.9832 | Train Macro F1: 0.9667
Val Loss  : 2.2693 | Val Acc  : 0.7565 | Val Macro Precision: 0.5418 | Val Macro Recall: 0.5137 | Val Macro F1: 0.5153
Saved best checkpoint: /content/drive/MyDrive/model/M21_strong_visual_pika/train_run/M21_strong_visual_pika_best.pth
Best Val Macro F1: 0.5153

M21 Strong Visual PIKA Epoch [14/15]
Current LR: 0.00000396
Train Loss: 0.6255 | Main: 0.4447 | Pseudo: 0.9029 | Link: 0.0050 | Train Acc: 0.9885 | Train Macro F1: 0.9729
Val Loss  : 2.2865 | Val Acc  : 0.7515 | Val Macro Precision: 0.5144 | Val Macro Recall: 0.5007 | Val Macro F1: 0.4946
No significant improvement. bad_epochs=1/5

M21 Strong Visual PIKA Epoch [15/15]
Current LR: 0.00000100
Train Loss: 0.6062 | Main: 0.4352 | Pseudo: 0.8540 | Link: 0.0049 | Train Acc: 0.9911 | Train Macro F1: 0.9769
Val Loss  : 2.3080 | Val Acc  : 0.7485 | Val Macro Precision: 0.5198 | Val Macro Recall: 0.4987 | Val Macro F1: 0.4962
No significant improvement. bad_epochs=2/5

M21 training done.
Best checkpoint: /content/drive/MyDrive/model/M21_strong_visual_pika/train_run/M21_strong_visual_pika_best.pth
Best Val Macro F1: 0.5153245979549582
Last checkpoint: /content/drive/MyDrive/model/M21_strong_visual_pika/train_run/M21_strong_visual_pika_last.pth

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python evaluate_m21_strong_visual_pika.py \
  --checkpoint /content/drive/MyDrive/model/M21_strong_visual_pika/train_run/M21_strong_visual_pika_best.pth \
  --test_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv \
  --graph_artifacts_dir /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts \
  --output_dir /content/drive/MyDrive/model/M21_strong_visual_pika/test_eval \
  --batch_size 24 \
  2>&1 | tee /content/drive/MyDrive/model/M21_strong_visual_pika/test_eval/test_log.txt

/content/vaipe-contextual-pill-recognition
=== EVALUATE M21 STRONG VISUAL PIKA ===
Using device: cuda
Checkpoint: /content/drive/MyDrive/model/M21_strong_visual_pika/train_run/M21_strong_visual_pika_best.pth
Test CSV  : /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv
Graph artifacts dir: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts
Output dir: /content/drive/MyDrive/model/M21_strong_visual_pika/test_eval
Using graph embeddings: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_embeddings.npy
Num classes: 108
Max context len: 8
Graph embeddings shape: (108, 64)

Raw test rows: 4550
Raw test labels: 82
Raw test columns: ['pill_crop_path', 'pill_label', 'pill_json', 'prescription_json', 'prescription_image_path', 'context_labels', 'prescription_key', 'split', 'source_split', 'clean_split']
Test pill images existing: 4550 / 4550
Test prescription images existing: 4550 / 4550

Test rows after image check: 4550
Test labels present: 82
Test mapped label min: 1
Test mapped label max: 107
Model type        : M21StrongVisualPIKA
Pill model        : convnext_tiny.in12k_ft_in1k
Prescription model: resnet18.a1_in1k
Common dim        : 128
Hidden dim        : 384
Num classes       : 108
Dropout p         : 0.5
Context dropout p : 0.25
Train graph emb   : False
Evaluating M21: 100%|██████████| 190/190 [02:02<00:00,  1.55it/s]

=== M21 TEST RESULTS ===
Test Accuracy                 : 0.741319
Test Macro Precision Present  : 0.448921
Test Macro Recall Present     : 0.430207
Test Macro F1 Present Classes : 0.423311
Test Macro Precision All      : 0.415667
Test Macro Recall All         : 0.398340
Test Macro F1 All Classes     : 0.391954
Test Weighted F1              : 0.735270

Saved files:
/content/drive/MyDrive/model/M21_strong_visual_pika/test_eval/m21_test_metrics.json
/content/drive/MyDrive/model/M21_strong_visual_pika/test_eval/m21_test_predictions.csv
/content/drive/MyDrive/model/M21_strong_visual_pika/test_eval/m21_classification_report.csv
/content/drive/MyDrive/model/M21_strong_visual_pika/test_eval/m21_per_class_metrics.csv
/content/drive/MyDrive/model/M21_strong_visual_pika/test_eval/m21_confusion_matrix.csv

Chuyển sang hướng lớn:
1. Diagnose split + hard classes.
2. Nếu cần, tạo split v3/cross-val.
3. Train crop-only visual classifier thật mạnh.
4. Đưa visual backbone đã học vào PIKA.
5. Fine-tune PIKA.
6. Cuối cùng mới TTA/ensemble.

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh diagnose_split_and_errors.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 282, done.
remote: Counting objects: 100% (160/160), done.
remote: Compressing objects: 100% (138/138), done.
remote: Total 282 (delta 97), reused 22 (delta 22), pack-reused 122 (from 1)
Receiving objects: 100% (282/282), 2.62 MiB | 6.65 MiB/s, done.
Resolving deltas: 100% (152/152), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 23K May  7 06:54 diagnose_split_and_errors.py

In [ ]:
import os

DIAG_DIR = "/content/drive/MyDrive/model/diagnosis_split_errors_v1"
os.makedirs(DIAG_DIR, exist_ok=True)

print("Diagnosis output dir:", DIAG_DIR)

Diagnosis output dir: /content/drive/MyDrive/model/diagnosis_split_errors_v1

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python diagnose_split_and_errors.py \
  --train_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv \
  --val_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv \
  --test_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv \
  --m19_predictions /content/drive/MyDrive/model/M19_arch_pika_v1/test_eval/m19_test_predictions.csv \
  --m21_predictions /content/drive/MyDrive/model/M21_strong_visual_pika/test_eval/m21_test_predictions.csv \
  --output_dir /content/drive/MyDrive/model/diagnosis_split_errors_v1 \
  2>&1 | tee /content/drive/MyDrive/model/diagnosis_split_errors_v1/diagnosis_log.txt

/content/vaipe-contextual-pill-recognition
=== DIAGNOSE SPLIT AND ERRORS ===
Train CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv
Val CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv
Test CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv
M19 predictions: /content/drive/MyDrive/model/M19_arch_pika_v1/test_eval/m19_test_predictions.csv
M21 predictions: /content/drive/MyDrive/model/M21_strong_visual_pika/test_eval/m21_test_predictions.csv
Output dir: /content/drive/MyDrive/model/diagnosis_split_errors_v1

=== SPLIT SUMMARY ===
split  rows  labels_present  min_class_count  max_class_count
train 23189             108                1             5736
  val  4974              89                1             1345
 test  4550              82                1             1296

=== LABEL COVERAGE ===
{
  "train_labels": 108,
  "val_labels": 89,
  "test_labels": 82,
  "train_missing_in_val_count": 19,
  "train_missing_in_val": [
    "0",
    "3",
    "4",
    "9",
    "13",
    "16",
    "20",
    "25",
    "32",
    "35",
    "44",
    "49",
    "53",
    "66",
    "85",
    "86",
    "94",
    "96",
    "102"
  ],
  "train_missing_in_test_count": 26,
  "train_missing_in_test": [
    "0",
    "3",
    "4",
    "6",
    "9",
    "11",
    "13",
    "16",
    "20",
    "25",
    "32",
    "35",
    "39",
    "44",
    "49",
    "53",
    "58",
    "66",
    "69",
    "77",
    "85",
    "86",
    "94",
    "96",
    "98",
    "102"
  ],
  "test_labels_not_in_train_count": 0,
  "test_labels_not_in_train": []
}

Saved split files:
/content/drive/MyDrive/model/diagnosis_split_errors_v1/class_distribution_train_val_test.csv
/content/drive/MyDrive/model/diagnosis_split_errors_v1/split_summary.csv
/content/drive/MyDrive/model/diagnosis_split_errors_v1/label_coverage.json

=== M19 METRICS ===
prediction_file: /content/drive/MyDrive/model/M19_arch_pika_v1/test_eval/m19_test_predictions.csv
true_column: true_original_label
pred_column: pred_original_label
num_rows: 4550
num_present_labels: 82
accuracy: 0.746813
macro_precision_present: 0.470671
macro_recall_present: 0.452737
macro_f1_present: 0.443011
macro_precision_all_train_labels: 0.422732
macro_recall_all_train_labels: 0.406625
macro_f1_all_train_labels: 0.397890
weighted_precision: 0.762281
weighted_recall: 0.746813
weighted_f1: 0.744192
Saved: /content/drive/MyDrive/model/diagnosis_split_errors_v1/m19_metrics.json
Saved: /content/drive/MyDrive/model/diagnosis_split_errors_v1/m19_per_class_metrics.csv
Saved: /content/drive/MyDrive/model/diagnosis_split_errors_v1/m19_hard_classes.csv
Saved: /content/drive/MyDrive/model/diagnosis_split_errors_v1/m19_confusion_pairs.csv

=== M21 METRICS ===
prediction_file: /content/drive/MyDrive/model/M21_strong_visual_pika/test_eval/m21_test_predictions.csv
true_column: true_original_label
pred_column: pred_original_label
num_rows: 4550
num_present_labels: 82
accuracy: 0.741319
macro_precision_present: 0.448921
macro_recall_present: 0.430207
macro_f1_present: 0.423311
macro_precision_all_train_labels: 0.415667
macro_recall_all_train_labels: 0.398340
macro_f1_all_train_labels: 0.391954
weighted_precision: 0.745801
weighted_recall: 0.741319
weighted_f1: 0.735270
Saved: /content/drive/MyDrive/model/diagnosis_split_errors_v1/m21_metrics.json
Saved: /content/drive/MyDrive/model/diagnosis_split_errors_v1/m21_per_class_metrics.csv
Saved: /content/drive/MyDrive/model/diagnosis_split_errors_v1/m21_hard_classes.csv
Saved: /content/drive/MyDrive/model/diagnosis_split_errors_v1/m21_confusion_pairs.csv

=== COMPARE M19 VS M21 ===
                           case  count    ratio
                   both_correct   3104 0.682198
both_wrong_different_prediction    503 0.110549
     both_wrong_same_prediction    380 0.083516
               m19_only_correct    294 0.064615
               m21_only_correct    269 0.059121
Saved comparison files to: /content/drive/MyDrive/model/diagnosis_split_errors_v1

Saved markdown report: /content/drive/MyDrive/model/diagnosis_split_errors_v1/diagnosis_report.md

=== DONE ===
Main report: /content/drive/MyDrive/model/diagnosis_split_errors_v1/diagnosis_report.md

In [ ]:
import pandas as pd
from pathlib import Path

diag_dir = Path("/content/drive/MyDrive/model/diagnosis_split_errors_v1")

files = {
    "class_distribution": diag_dir / "class_distribution_train_val_test.csv",
    "m19_hard_classes": diag_dir / "m19_hard_classes.csv",
    "m19_confusion_pairs": diag_dir / "m19_confusion_pairs.csv",
    "m21_hard_classes": diag_dir / "m21_hard_classes.csv",
    "m21_confusion_pairs": diag_dir / "m21_confusion_pairs.csv",
    "compare_per_class": diag_dir / "compare_m19_vs_m21_per_class.csv",
    "m19_correct_m21_wrong": diag_dir / "m19_correct_m21_wrong.csv",
    "m21_correct_m19_wrong": diag_dir / "m21_correct_m19_wrong.csv",
}

for name, path in files.items():
    print(name, "=>", path.exists(), path)

class_distribution => True /content/drive/MyDrive/model/diagnosis_split_errors_v1/class_distribution_train_val_test.csv
m19_hard_classes => True /content/drive/MyDrive/model/diagnosis_split_errors_v1/m19_hard_classes.csv
m19_confusion_pairs => True /content/drive/MyDrive/model/diagnosis_split_errors_v1/m19_confusion_pairs.csv
m21_hard_classes => True /content/drive/MyDrive/model/diagnosis_split_errors_v1/m21_hard_classes.csv
m21_confusion_pairs => True /content/drive/MyDrive/model/diagnosis_split_errors_v1/m21_confusion_pairs.csv
compare_per_class => True /content/drive/MyDrive/model/diagnosis_split_errors_v1/compare_m19_vs_m21_per_class.csv
m19_correct_m21_wrong => True /content/drive/MyDrive/model/diagnosis_split_errors_v1/m19_correct_m21_wrong.csv
m21_correct_m19_wrong => True /content/drive/MyDrive/model/diagnosis_split_errors_v1/m21_correct_m19_wrong.csv

In [ ]:
import pandas as pd
from pathlib import Path

diag_dir = Path("/content/drive/MyDrive/model/diagnosis_split_errors_v1")

m19_hard = pd.read_csv(diag_dir / "m19_hard_classes.csv")
m19_conf = pd.read_csv(diag_dir / "m19_confusion_pairs.csv")
compare_cls = pd.read_csv(diag_dir / "compare_m19_vs_m21_per_class.csv")

print("\n====================")
print("1. M19 HARDEST CLASSES WITH TEST SUPPORT")
print("====================")
cols1 = [c for c in [
    "label", "support", "precision", "recall", "f1",
    "train_count", "val_count", "test_count",
    "pred_count", "error_count_est"
] if c in m19_hard.columns]

print(
    m19_hard[m19_hard["support"] > 0]
    .sort_values(["f1", "support"], ascending=[True, False])
    .head(30)[cols1]
    .to_string(index=False)
)

print("\n====================")
print("2. M19 TOP CONFUSION PAIRS")
print("====================")
cols2 = [c for c in [
    "true_norm", "pred_norm", "wrong_count",
    "true_support", "pred_support"
] if c in m19_conf.columns]

print(
    m19_conf.head(30)[cols2]
    .to_string(index=False)
)

print("\n====================")
print("3. CLASSES WHERE M21 IMPROVES OVER M19")
print("====================")
cols3 = [c for c in [
    "label", "samples", "a_correct", "b_correct",
    "a_acc", "b_acc", "b_minus_a_acc"
] if c in compare_cls.columns]

print(
    compare_cls.sort_values(["b_minus_a_acc", "samples"], ascending=[False, False])
    .head(30)[cols3]
    .to_string(index=False)
)

print("\n====================")
print("4. CLASSES WHERE M21 IS WORSE THAN M19")
print("====================")
print(
    compare_cls.sort_values(["b_minus_a_acc", "samples"], ascending=[True, False])
    .head(30)[cols3]
    .to_string(index=False)
)

====================
1. M19 HARDEST CLASSES WITH TEST SUPPORT
====================
 label  support  precision   recall       f1  train_count  val_count  test_count  pred_count  error_count_est
    47       16   0.000000 0.000000 0.000000           73         17          16          16             16.0
    18       10   0.000000 0.000000 0.000000           84          8          10           3             10.0
    50       10   0.000000 0.000000 0.000000           67         11          10           4             10.0
    81        8   0.000000 0.000000 0.000000           69         20           8           2              8.0
     5        7   0.000000 0.000000 0.000000           38          8           7           4              7.0
    63        6   0.000000 0.000000 0.000000           26          6           6           1              6.0
    71        4   0.000000 0.000000 0.000000           26          8           4           0              4.0
    76        4   0.000000 0.000000 0.000000           12          4           4           8              4.0
    21        3   0.000000 0.000000 0.000000           13          3           3           2              3.0
    42        3   0.000000 0.000000 0.000000           20          5           3           2              3.0
    88        1   0.000000 0.000000 0.000000            6          1           1           0              1.0
    68       16   0.033333 0.062500 0.043478           93         16          16          30             15.0
    95       22   0.047619 0.045455 0.046512           99         21          22          21             21.0
    72       14   0.083333 0.071429 0.076923           62         14          14          12             13.0
   105       10   0.100000 0.100000 0.100000           45         10          10          10              9.0
    75       10   0.093750 0.300000 0.142857           78         16          10          32              7.0
    90       13   0.181818 0.153846 0.166667           60         13          13          11             11.0
    80       16   0.285714 0.125000 0.173913           64         12          16           7             14.0
    48        7   0.333333 0.142857 0.200000           50         12           7           3              6.0
    74       42   0.714286 0.119048 0.204082          199         41          42           7             37.0
    52       24   0.750000 0.125000 0.214286           96         19          24           4             21.0
    24       30   0.275862 0.266667 0.271186          141         30          30          29             22.0
   106        6   0.200000 0.500000 0.285714          132         18           6          15              3.0
    15       14   0.600000 0.214286 0.315789           64         14          14           5             11.0
    14       16   0.571429 0.250000 0.347826           87         18          16           7             12.0
    41       13   0.400000 0.307692 0.347826           81         21          13          10              9.0
    73       59   0.343750 0.372881 0.357724          229         37          59          64             37.0
   103       29   0.533333 0.275862 0.363636          133         30          29          15             21.0
    89      180   0.495327 0.294444 0.369338         1168        256         180         107            127.0
   104       84   0.353535 0.416667 0.382514          410         88          84          99             49.0

====================
2. M19 TOP CONFUSION PAIRS
====================
 true_norm  pred_norm  wrong_count  true_support  pred_support
        89          0           27           180            31
        89         60           26           180            56
        59         73           26            85            64
        52        104           19            24            99
        36         51           17            31           158
        73         75           17            59            32
        91         89           17           198           107
        89         99           15           180            90
        24         10           15            30           246
       104         68           12            84            30
         7         28           12            69            27
        99         10           12           117           246
        89        104           10           180            99
        80         59           10            16            65
        84         47           10            30            16
         7         73            9            69            64
        89         24            9           180            29
        89         90            8           180            11
        41         72            8            13            12
        18         68            8            10            30
        90         89            8            13           107
        19         43            8            72           180
        74         76            8            42             8
         8         99            7            80            90
       103         95            7            29            21
        74         64            7            42           359
        47         39            7            16             9
        89          2            7           180           107
       104         19            7            84            75
        51         96            7           147             7

====================
3. CLASSES WHERE M21 IMPROVES OVER M19
====================
 label  samples  a_correct  b_correct    a_acc    b_acc  b_minus_a_acc
    50       10          0          4 0.000000 0.400000       0.400000
    63        6          0          2 0.000000 0.333333       0.333333
    21        3          0          1 0.000000 0.333333       0.333333
    31       16         11         16 0.687500 1.000000       0.312500
    68       16          1          6 0.062500 0.375000       0.312500
    84       30         17         25 0.566667 0.833333       0.266667
   100        4          2          3 0.500000 0.750000       0.250000
    72       14          1          4 0.071429 0.285714       0.214286
    79       19         13         17 0.684211 0.894737       0.210526
     5        7          0          1 0.000000 0.142857       0.142857
    17       15         13         15 0.866667 1.000000       0.133333
     7       69         26         35 0.376812 0.507246       0.130435
    47       16          0          2 0.000000 0.125000       0.125000
    89      180         53         73 0.294444 0.405556       0.111111
    38       19          8         10 0.421053 0.526316       0.105263
    41       13          4          5 0.307692 0.384615       0.076923
    74       42          5          8 0.119048 0.190476       0.071429
    65       18         17         18 0.944444 1.000000       0.055556
    73       59         22         25 0.372881 0.423729       0.050847
   104       84         35         39 0.416667 0.464286       0.047619
    51      147        122        129 0.829932 0.877551       0.047619
    64      375        330        346 0.880000 0.922667       0.042667
    27       25         15         16 0.600000 0.640000       0.040000
    99      117         50         54 0.427350 0.461538       0.034188
    37       33         23         24 0.696970 0.727273       0.030303
    91      198        147        152 0.742424 0.767677       0.025253
    34       24         24         24 1.000000 1.000000       0.000000
    56       24         19         19 0.791667 0.791667       0.000000
    14       16          4          4 0.250000 0.250000       0.000000
    15       14          3          3 0.214286 0.214286       0.000000

====================
4. CLASSES WHERE M21 IS WORSE THAN M19
====================
 label  samples  a_correct  b_correct    a_acc    b_acc  b_minus_a_acc
   106        6          3          0 0.500000 0.000000      -0.500000
    83        6          6          4 1.000000 0.666667      -0.333333
    92       28         28         21 1.000000 0.750000      -0.250000
   101        4          3          2 0.750000 0.500000      -0.250000
     2       81         62         42 0.765432 0.518519      -0.246914
    78        9          7          5 0.777778 0.555556      -0.222222
    67       15         13         10 0.866667 0.666667      -0.200000
    36       31         11          5 0.354839 0.161290      -0.193548
     1       21          9          5 0.428571 0.238095      -0.190476
    61       84         77         62 0.916667 0.738095      -0.178571
    30       29         29         24 1.000000 0.827586      -0.172414
    40       18          8          5 0.444444 0.277778      -0.166667
    48        7          1          0 0.142857 0.000000      -0.142857
    19       72         54         44 0.750000 0.611111      -0.138889
    80       16          2          0 0.125000 0.000000      -0.125000
    62        9          9          8 1.000000 0.888889      -0.111111
    12        9          8          7 0.888889 0.777778      -0.111111
    70       37         14         10 0.378378 0.270270      -0.108108
    60       19         19         17 1.000000 0.894737      -0.105263
    24       30          8          5 0.266667 0.166667      -0.100000
    55       20         12         10 0.600000 0.500000      -0.100000
    75       10          3          2 0.300000 0.200000      -0.100000
    29       35         23         20 0.657143 0.571429      -0.085714
    28       12         12         11 1.000000 0.916667      -0.083333
    59       85         39         33 0.458824 0.388235      -0.070588
   103       29          8          6 0.275862 0.206897      -0.068966
    45       15         14         13 0.933333 0.866667      -0.066667
    46       76         66         62 0.868421 0.815789      -0.052632
    54       60         59         56 0.983333 0.933333      -0.050000
    87       21          9          8 0.428571 0.380952      -0.047619

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh evaluate_m19_m21_val_predictions.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 285, done.
remote: Counting objects: 100% (163/163), done.
remote: Compressing objects: 100% (141/141), done.
remote: Total 285 (delta 98), reused 22 (delta 22), pack-reused 122 (from 1)
Receiving objects: 100% (285/285), 2.62 MiB | 5.53 MiB/s, done.
Resolving deltas: 100% (153/153), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 17K May  7 07:04 evaluate_m19_m21_val_predictions.py

In [ ]:
import os

M22_VAL_DIR = "/content/drive/MyDrive/model/M22_selective_ensemble/val_predictions"
os.makedirs(M22_VAL_DIR, exist_ok=True)

print("M22 val prediction output dir:", M22_VAL_DIR)

M22 val prediction output dir: /content/drive/MyDrive/model/M22_selective_ensemble/val_predictions

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python evaluate_m19_m21_val_predictions.py \
  --eval_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv \
  --m19_checkpoint /content/drive/MyDrive/model/M19_arch_pika_v1/train_run/M19_arch_pika_v1_best.pth \
  --m21_checkpoint /content/drive/MyDrive/model/M21_strong_visual_pika/train_run/M21_strong_visual_pika_best.pth \
  --graph_artifacts_dir /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts \
  --output_dir /content/drive/MyDrive/model/M22_selective_ensemble/val_predictions \
  --batch_size 24 \
  2>&1 | tee /content/drive/MyDrive/model/M22_selective_ensemble/val_predictions/val_prediction_log.txt

/content/vaipe-contextual-pill-recognition
=== EVALUATE M19 + M21 ON VALIDATION ===
Using device: cuda
Eval CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv
M19 checkpoint: /content/drive/MyDrive/model/M19_arch_pika_v1/train_run/M19_arch_pika_v1_best.pth
M21 checkpoint: /content/drive/MyDrive/model/M21_strong_visual_pika/train_run/M21_strong_visual_pika_best.pth
Graph artifacts dir: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts
Output dir: /content/drive/MyDrive/model/M22_selective_ensemble/val_predictions
Using graph embeddings: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_embeddings.npy
Using graph embeddings: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_embeddings.npy

Graph M19 shape: (108, 64)
Graph M21 shape: (108, 64)

Raw eval rows: 4974
Raw eval labels: 89
Raw eval columns: ['pill_crop_path', 'pill_label', 'pill_json', 'prescription_json', 'prescription_image_path', 'context_labels', 'prescription_key', 'split', 'source_split', 'clean_split']
Eval pill images existing: 4974 / 4974
Eval prescription images existing: 4974 / 4974

Eval rows after image check: 4974
Eval labels present: 89
Eval mapped label min: 1
Eval mapped label max: 107

M19 max_context_len: 5
M21 max_context_len: 8

=== Build M19 ===
Model type        : M19ArchitecturePIKA
Pill model        : tf_efficientnetv2_s.in21k_ft_in1k
Prescription model: resnet18.a1_in1k
Hidden dim        : 256
Graph dim         : 64
Num classes       : 108
Dropout p         : 0.5
Context dropout p : 0.2
Train graph emb   : False

=== Build M21 ===
Model type        : M21StrongVisualPIKA
Pill model        : convnext_tiny.in12k_ft_in1k
Prescription model: resnet18.a1_in1k
Common dim        : 128
Hidden dim        : 384
Num classes       : 108
Dropout p         : 0.5
Context dropout p : 0.25
Train graph emb   : False

Collecting M19 validation probabilities...
M19 val: 100%|██████████| 208/208 [02:07<00:00,  1.63it/s]

Collecting M21 validation probabilities...
M21 val: 100%|██████████| 208/208 [02:05<00:00,  1.66it/s]

=== M19 VAL METRICS ===
Accuracy           : 0.749698
Macro F1 Present   : 0.490893
Macro F1 All       : 0.445440
Weighted F1        : 0.748022

Saved files:
/content/drive/MyDrive/model/M22_selective_ensemble/val_predictions/m19_val_predictions.csv
/content/drive/MyDrive/model/M22_selective_ensemble/val_predictions/m19_val_probs.npy
/content/drive/MyDrive/model/M22_selective_ensemble/val_predictions/m19_val_y_true.npy
/content/drive/MyDrive/model/M22_selective_ensemble/val_predictions/m19_val_y_pred.npy
/content/drive/MyDrive/model/M22_selective_ensemble/val_predictions/m19_val_metrics.json

=== M21 VAL METRICS ===
Accuracy           : 0.756534
Macro F1 Present   : 0.515325
Macro F1 All       : 0.472381
Weighted F1        : 0.750121

Saved files:
/content/drive/MyDrive/model/M22_selective_ensemble/val_predictions/m21_val_predictions.csv
/content/drive/MyDrive/model/M22_selective_ensemble/val_predictions/m21_val_probs.npy
/content/drive/MyDrive/model/M22_selective_ensemble/val_predictions/m21_val_y_true.npy
/content/drive/MyDrive/model/M22_selective_ensemble/val_predictions/m21_val_y_pred.npy
/content/drive/MyDrive/model/M22_selective_ensemble/val_predictions/m21_val_metrics.json

=== SUMMARY ===
model  accuracy  macro_f1_present  macro_f1_all  weighted_f1  checkpoint_epoch  checkpoint_val_macro_f1
  m19  0.749698          0.490893      0.445440     0.748022                15                 0.490684
  m21  0.756534          0.515325      0.472381     0.750121                13                 0.515325

Saved summary: /content/drive/MyDrive/model/M22_selective_ensemble/val_predictions/val_metrics_summary.csv

Done.

Điều này xác nhận: trên validation, M21 thật sự tốt hơn M19. Nhưng vì M21 test thấp hơn M19, bước M22 phải làm cẩn thận: chỉ tune ensemble trên val, sau đó apply lên test, không dùng test để chọn rule.

In [ ]:
import os

M22_TEST_DIR = "/content/drive/MyDrive/model/M22_selective_ensemble/test_predictions"
os.makedirs(M22_TEST_DIR, exist_ok=True)

print("M22 test prediction output dir:", M22_TEST_DIR)

M22 test prediction output dir: /content/drive/MyDrive/model/M22_selective_ensemble/test_predictions

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python evaluate_m19_m21_val_predictions.py \
  --eval_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv \
  --m19_checkpoint /content/drive/MyDrive/model/M19_arch_pika_v1/train_run/M19_arch_pika_v1_best.pth \
  --m21_checkpoint /content/drive/MyDrive/model/M21_strong_visual_pika/train_run/M21_strong_visual_pika_best.pth \
  --graph_artifacts_dir /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts \
  --output_dir /content/drive/MyDrive/model/M22_selective_ensemble/test_predictions \
  --batch_size 24 \
  2>&1 | tee /content/drive/MyDrive/model/M22_selective_ensemble/test_predictions/test_prediction_log.txt

/content/vaipe-contextual-pill-recognition
=== EVALUATE M19 + M21 ON VALIDATION ===
Using device: cuda
Eval CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv
M19 checkpoint: /content/drive/MyDrive/model/M19_arch_pika_v1/train_run/M19_arch_pika_v1_best.pth
M21 checkpoint: /content/drive/MyDrive/model/M21_strong_visual_pika/train_run/M21_strong_visual_pika_best.pth
Graph artifacts dir: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts
Output dir: /content/drive/MyDrive/model/M22_selective_ensemble/test_predictions
Using graph embeddings: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_embeddings.npy
Using graph embeddings: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/graph_embeddings.npy

Graph M19 shape: (108, 64)
Graph M21 shape: (108, 64)

Raw eval rows: 4550
Raw eval labels: 82
Raw eval columns: ['pill_crop_path', 'pill_label', 'pill_json', 'prescription_json', 'prescription_image_path', 'context_labels', 'prescription_key', 'split', 'source_split', 'clean_split']
Eval pill images existing: 4550 / 4550
Eval prescription images existing: 4550 / 4550

Eval rows after image check: 4550
Eval labels present: 82
Eval mapped label min: 1
Eval mapped label max: 107

M19 max_context_len: 5
M21 max_context_len: 8

=== Build M19 ===
Model type        : M19ArchitecturePIKA
Pill model        : tf_efficientnetv2_s.in21k_ft_in1k
Prescription model: resnet18.a1_in1k
Hidden dim        : 256
Graph dim         : 64
Num classes       : 108
Dropout p         : 0.5
Context dropout p : 0.2
Train graph emb   : False

=== Build M21 ===
Model type        : M21StrongVisualPIKA
Pill model        : convnext_tiny.in12k_ft_in1k
Prescription model: resnet18.a1_in1k
Common dim        : 128
Hidden dim        : 384
Num classes       : 108
Dropout p         : 0.5
Context dropout p : 0.25
Train graph emb   : False

Collecting M19 validation probabilities...
M19 val: 100%|██████████| 190/190 [01:56<00:00,  1.63it/s]

Collecting M21 validation probabilities...
M21 val: 100%|██████████| 190/190 [02:00<00:00,  1.58it/s]

=== M19 VAL METRICS ===
Accuracy           : 0.746813
Macro F1 Present   : 0.443011
Macro F1 All       : 0.397890
Weighted F1        : 0.744192

Saved files:
/content/drive/MyDrive/model/M22_selective_ensemble/test_predictions/m19_val_predictions.csv
/content/drive/MyDrive/model/M22_selective_ensemble/test_predictions/m19_val_probs.npy
/content/drive/MyDrive/model/M22_selective_ensemble/test_predictions/m19_val_y_true.npy
/content/drive/MyDrive/model/M22_selective_ensemble/test_predictions/m19_val_y_pred.npy
/content/drive/MyDrive/model/M22_selective_ensemble/test_predictions/m19_val_metrics.json

=== M21 VAL METRICS ===
Accuracy           : 0.741319
Macro F1 Present   : 0.423311
Macro F1 All       : 0.391954
Weighted F1        : 0.735270

Saved files:
/content/drive/MyDrive/model/M22_selective_ensemble/test_predictions/m21_val_predictions.csv
/content/drive/MyDrive/model/M22_selective_ensemble/test_predictions/m21_val_probs.npy
/content/drive/MyDrive/model/M22_selective_ensemble/test_predictions/m21_val_y_true.npy
/content/drive/MyDrive/model/M22_selective_ensemble/test_predictions/m21_val_y_pred.npy
/content/drive/MyDrive/model/M22_selective_ensemble/test_predictions/m21_val_metrics.json

=== SUMMARY ===
model  accuracy  macro_f1_present  macro_f1_all  weighted_f1  checkpoint_epoch  checkpoint_val_macro_f1
  m19  0.746813          0.443011      0.397890     0.744192                15                 0.490684
  m21  0.741319          0.423311      0.391954     0.735270                13                 0.515325

Saved summary: /content/drive/MyDrive/model/M22_selective_ensemble/test_predictions/val_metrics_summary.csv

Done.

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh build_m22_selective_ensemble.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 288, done.
remote: Counting objects: 100% (166/166), done.
remote: Compressing objects: 100% (144/144), done.
remote: Total 288 (delta 99), reused 22 (delta 22), pack-reused 122 (from 1)
Receiving objects: 100% (288/288), 2.63 MiB | 7.10 MiB/s, done.
Resolving deltas: 100% (154/154), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 15K May  7 07:19 build_m22_selective_ensemble.py

In [ ]:
import os

M22_OUT = "/content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1"
os.makedirs(M22_OUT, exist_ok=True)

print("M22 output dir:", M22_OUT)

M22 output dir: /content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python build_m22_selective_ensemble.py \
  --val_dir /content/drive/MyDrive/model/M22_selective_ensemble/val_predictions \
  --test_dir /content/drive/MyDrive/model/M22_selective_ensemble/test_predictions \
  --output_dir /content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1 \
  --grid_step 0.02 \
  --min_support 5 \
  --min_f1_gain 0.05 \
  2>&1 | tee /content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1/ensemble_log.txt

/content/vaipe-contextual-pill-recognition
/content/vaipe-contextual-pill-recognition/build_m22_selective_ensemble.py:403: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_candidates = pd.concat([global_grid, selective_grid], ignore_index=True)
=== BUILD M22 SELECTIVE ENSEMBLE ===
Val prediction dir : /content/drive/MyDrive/model/M22_selective_ensemble/val_predictions
Test prediction dir: /content/drive/MyDrive/model/M22_selective_ensemble/test_predictions
Output dir         : /content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1
Num classes: 108
Val rows: 4974
Test rows: 4550

=== BASE VAL METRICS ===
M19 Val Macro F1: 0.490893
M21 Val Macro F1: 0.515325

Trusted M21 classes: [2, 5, 6, 10, 15, 22, 28, 29, 31, 33, 36, 40, 50, 54, 59, 63, 68, 72, 74, 82, 83, 87, 89, 92, 100, 106]
Num trusted M21 classes: 26

=== BEST GLOBAL VAL ===
           mode  w_m19  w_m21 threshold margin  num_switched  accuracy  macro_precision_present  macro_recall_present  macro_f1_present  macro_precision_all  macro_recall_all  macro_f1_all  weighted_precision  weighted_recall  weighted_f1
global_weighted   0.30   0.70      None   None             0  0.774025                 0.578469              0.542708          0.548417             0.514194          0.482408      0.487482            0.771581         0.774025     0.766684
global_weighted   0.28   0.72      None   None             0  0.773020                 0.576525              0.539943          0.545963             0.512467          0.479949      0.485300            0.770337         0.773020     0.765403
global_weighted   0.26   0.74      None   None             0  0.772216                 0.575939              0.538997          0.545183             0.511946          0.479109      0.484607            0.769860         0.772216     0.764865
global_weighted   0.24   0.76      None   None             0  0.771612                 0.575156              0.538091          0.544296             0.511249          0.478303      0.483818            0.769261         0.771612     0.764234
global_weighted   0.22   0.78      None   None             0  0.769803                 0.572570              0.537593          0.542417             0.508952          0.477861      0.482149            0.767598         0.769803     0.762427
global_weighted   0.20   0.80      None   None             0  0.767591                 0.569623              0.535554          0.539534             0.506332          0.476048      0.479585            0.765263         0.767591     0.760055
global_weighted   0.32   0.68      None   None             0  0.775834                 0.569013              0.533217          0.539290             0.516327          0.483845      0.489356            0.773108         0.775834     0.768420
global_weighted   0.44   0.56      None   None             0  0.782871                 0.562724              0.533722          0.537243             0.515830          0.489245      0.492473            0.777878         0.782871     0.774860
global_weighted   0.46   0.54      None   None             0  0.783675                 0.561854              0.533451          0.536562             0.515033          0.488996      0.491848            0.778680         0.783675     0.775503
global_weighted   0.42   0.58      None   None             0  0.779855                 0.561291              0.531258          0.535281             0.514517          0.486986      0.490674            0.775588         0.779855     0.772109

=== BEST SELECTIVE VAL ===
                         mode  w_m19  w_m21  threshold  margin  num_switched  accuracy  macro_precision_present  macro_recall_present  macro_f1_present  macro_precision_all  macro_recall_all  macro_f1_all  weighted_precision  weighted_recall  weighted_f1
selective_m21_on_trusted_pred    0.3    0.7        0.4    0.00           903  0.774829                 0.579794              0.544365          0.550088             0.515372          0.483880      0.488967            0.771839         0.774829     0.767312
selective_m21_on_trusted_pred    0.3    0.7        0.4    0.05           899  0.775030                 0.579897              0.543910          0.549869             0.515464          0.483476      0.488773            0.772255         0.775030     0.767620
selective_m21_on_trusted_pred    0.3    0.7        0.4    0.10           896  0.775030                 0.579897              0.543910          0.549869             0.515464          0.483476      0.488773            0.772255         0.775030     0.767620
selective_m21_on_trusted_pred    0.3    0.7        0.4    0.15           889  0.774829                 0.579836              0.543736          0.549760             0.515410          0.483321      0.488676            0.772082         0.774829     0.767433
selective_m21_on_trusted_pred    0.3    0.7        0.4    0.20           882  0.774628                 0.579722              0.543482          0.549541             0.515309          0.483095      0.488481            0.771998         0.774628     0.767263
selective_m21_on_trusted_pred    0.3    0.7        0.2    0.20           913  0.774628                 0.579516              0.543465          0.549461             0.515125          0.483080      0.488410            0.772056         0.774628     0.767309
selective_m21_on_trusted_pred    0.3    0.7        0.3    0.20           913  0.774628                 0.579516              0.543465          0.549461             0.515125          0.483080      0.488410            0.772056         0.774628     0.767309
selective_m21_on_trusted_pred    0.3    0.7        0.5    0.00           843  0.774427                 0.579019              0.543478          0.549147             0.514684          0.483091      0.488130            0.771959         0.774427     0.767123
selective_m21_on_trusted_pred    0.3    0.7        0.5    0.05           843  0.774427                 0.579019              0.543478          0.549147             0.514684          0.483091      0.488130            0.771959         0.774427     0.767123
selective_m21_on_trusted_pred    0.3    0.7        0.5    0.10           842  0.774427                 0.579019              0.543478          0.549147             0.514684          0.483091      0.488130            0.771959         0.774427     0.767123

=== SELECTED CONFIG BY VAL ===
mode: selective_m21_on_trusted_pred
w_m19: 0.3
w_m21: 0.7
threshold: 0.4
margin: 0.0
num_switched: 903
accuracy: 0.7748291113791717
macro_precision_present: 0.5797935231704129
macro_recall_present: 0.5443649027004485
macro_f1_present: 0.550088142007032
macro_precision_all: 0.5153720205959227
macro_recall_all: 0.48387991351150983
macro_f1_all: 0.48896723733958397
weighted_precision: 0.7718386430294516
weighted_recall: 0.7748291113791717
weighted_f1: 0.7673121056843748

=== VAL ENSEMBLE RESULTS ===
Mode             : selective_m21_on_trusted_pred
w_m19 / w_m21    : 0.3 / 0.7
threshold        : 0.4
margin           : 0.0
num switched     : 903
Accuracy         : 0.774829
Macro F1 Present : 0.550088
Macro F1 All     : 0.488967
Weighted F1      : 0.767312

=== TEST ENSEMBLE RESULTS ===
Mode             : selective_m21_on_trusted_pred
w_m19 / w_m21    : 0.3 / 0.7
threshold        : 0.4
margin           : 0.0
num switched     : 708
Accuracy         : 0.758022
Macro F1 Present : 0.462450
Macro F1 All     : 0.411067
Weighted F1      : 0.750668

Saved summary: /content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1/m22_ensemble_summary.csv
Done.

phân tích lỗi còn lại của M22

In [ ]:
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.metrics import precision_recall_fscore_support

m22_dir = Path("/content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1")
diag_dir = Path("/content/drive/MyDrive/model/diagnosis_split_errors_v1")

m22_pred_path = m22_dir / "test_ensemble_predictions.csv"
m19_pred_path = Path("/content/drive/MyDrive/model/M22_selective_ensemble/test_predictions/m19_val_predictions.csv")
m21_pred_path = Path("/content/drive/MyDrive/model/M22_selective_ensemble/test_predictions/m21_val_predictions.csv")
class_dist_path = diag_dir / "class_distribution_train_val_test.csv"

print("M22 pred exists:", m22_pred_path.exists(), m22_pred_path)
print("M19 pred exists:", m19_pred_path.exists(), m19_pred_path)
print("M21 pred exists:", m21_pred_path.exists(), m21_pred_path)
print("Class dist exists:", class_dist_path.exists(), class_dist_path)

m22 = pd.read_csv(m22_pred_path)
m19 = pd.read_csv(m19_pred_path)
m21 = pd.read_csv(m21_pred_path)
class_dist = pd.read_csv(class_dist_path)

print("\nM22 columns:")
print(m22.columns.tolist())

print("\nRows:")
print("M22:", len(m22))
print("M19:", len(m19))
print("M21:", len(m21))

M22 pred exists: True /content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1/test_ensemble_predictions.csv
M19 pred exists: True /content/drive/MyDrive/model/M22_selective_ensemble/test_predictions/m19_val_predictions.csv
M21 pred exists: True /content/drive/MyDrive/model/M22_selective_ensemble/test_predictions/m21_val_predictions.csv
Class dist exists: True /content/drive/MyDrive/model/diagnosis_split_errors_v1/class_distribution_train_val_test.csv

M22 columns:
['pill_crop_path', 'pill_label', 'pill_json', 'prescription_json', 'prescription_image_path', 'context_labels', 'prescription_key', 'split', 'source_split', 'clean_split', 'mapped_label', 'context_labels_mapped', 'true_mapped_label', 'pred_mapped_label', 'confidence', 'true_original_label', 'pred_original_label', 'is_correct', 'ensemble_pred_mapped_label', 'ensemble_pred_original_label', 'ensemble_confidence', 'ensemble_switched_to_m21', 'ensemble_is_correct']

Rows:
M22: 4550
M19: 4550
M21: 4550

In [ ]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def compute_metrics(y_true, y_pred, labels=None):
    acc = accuracy_score(y_true, y_pred)

    p, r, f1, _ = precision_recall_fscore_support(
        y_true, y_pred,
        labels=labels,
        average="macro",
        zero_division=0
    )

    wp, wr, wf1, _ = precision_recall_fscore_support(
        y_true, y_pred,
        average="weighted",
        zero_division=0
    )

    return acc, p, r, f1, wf1

# Chuẩn hóa label
m22["true_label"] = m22["true_mapped_label"].astype(int)
m22["pred_label"] = m22["ensemble_pred_mapped_label"].astype(int)
m22["correct"] = m22["true_label"] == m22["pred_label"]

num_classes = 108
labels_all = list(range(num_classes))

acc, p, r, f1, wf1 = compute_metrics(
    m22["true_label"],
    m22["pred_label"],
    labels=None
)

acc_all, p_all, r_all, f1_all, wf1_all = compute_metrics(
    m22["true_label"],
    m22["pred_label"],
    labels=labels_all
)

print("=== M22 TEST METRICS RECHECK ===")
print("Accuracy:", round(acc, 6))
print("Macro Precision Present:", round(p, 6))
print("Macro Recall Present:", round(r, 6))
print("Macro F1 Present:", round(f1, 6))
print("Macro F1 All:", round(f1_all, 6))
print("Weighted F1:", round(wf1, 6))

# Per-class metrics
precision, recall, f1s, support = precision_recall_fscore_support(
    m22["true_label"],
    m22["pred_label"],
    labels=labels_all,
    zero_division=0
)

per_class = pd.DataFrame({
    "label": labels_all,
    "support": support,
    "precision": precision,
    "recall": recall,
    "f1": f1s,
})

pred_count = m22["pred_label"].value_counts().rename("pred_count")
per_class = per_class.merge(
    pred_count,
    left_on="label",
    right_index=True,
    how="left"
)
per_class["pred_count"] = per_class["pred_count"].fillna(0).astype(int)

# Add train/val/test count
class_dist["label"] = class_dist["label"].astype(int)
per_class = per_class.merge(
    class_dist[["label", "train_count", "val_count", "test_count"]],
    on="label",
    how="left"
)

per_class["error_count"] = per_class["support"] - (per_class["recall"] * per_class["support"])

print("\n====================")
print("1. M22 HARDEST CLASSES")
print("====================")
print(
    per_class[per_class["support"] > 0]
    .sort_values(["f1", "support"], ascending=[True, False])
    .head(30)
    .to_string(index=False)
)

# Confusion pairs
wrong = m22[m22["true_label"] != m22["pred_label"]].copy()

conf_pairs = (
    wrong.groupby(["true_label", "pred_label"])
    .size()
    .reset_index(name="wrong_count")
    .sort_values("wrong_count", ascending=False)
)

true_support = m22["true_label"].value_counts().rename("true_support")
pred_support = m22["pred_label"].value_counts().rename("pred_support")

conf_pairs = conf_pairs.merge(
    true_support,
    left_on="true_label",
    right_index=True,
    how="left"
)

conf_pairs = conf_pairs.merge(
    pred_support,
    left_on="pred_label",
    right_index=True,
    how="left"
)

print("\n====================")
print("2. M22 TOP CONFUSION PAIRS")
print("====================")
print(conf_pairs.head(30).to_string(index=False))

# Save files
out_dir = Path("/content/drive/MyDrive/model/M22_selective_ensemble/diagnosis_after_m22")
out_dir.mkdir(parents=True, exist_ok=True)

per_class.to_csv(out_dir / "m22_per_class_metrics.csv", index=False)
conf_pairs.to_csv(out_dir / "m22_confusion_pairs.csv", index=False)

print("\nSaved:")
print(out_dir / "m22_per_class_metrics.csv")
print(out_dir / "m22_confusion_pairs.csv")

=== M22 TEST METRICS RECHECK ===
Accuracy: 0.758022
Macro Precision Present: 0.491424
Macro Recall Present: 0.466117
Macro F1 Present: 0.46245
Macro F1 All: 0.411067
Weighted F1: 0.750668

====================
1. M22 HARDEST CLASSES
====================
 label  support  precision   recall       f1  pred_count  train_count  val_count  test_count  error_count
    80       16   0.000000 0.000000 0.000000           3           64         12          16         16.0
    18       10   0.000000 0.000000 0.000000           2           84          8          10         10.0
    81        8   0.000000 0.000000 0.000000           2           69         20           8          8.0
     5        7   0.000000 0.000000 0.000000           2           38          8           7          7.0
    48        7   0.000000 0.000000 0.000000           3           50         12           7          7.0
    71        4   0.000000 0.000000 0.000000           1           26          8           4          4.0
    76        4   0.000000 0.000000 0.000000           8           12          4           4          4.0
    42        3   0.000000 0.000000 0.000000           1           20          5           3          3.0
    88        1   0.000000 0.000000 0.000000           1            6          1           1          1.0
    95       22   0.090909 0.045455 0.060606          11           99         21          22         21.0
   105       10   0.111111 0.100000 0.105263           9           45         10          10          9.0
    75       10   0.076923 0.200000 0.111111          26           78         16          10          8.0
    52       24   0.666667 0.083333 0.148148           3           96         19          24         22.0
    90       13   0.200000 0.153846 0.173913          10           60         13          13         11.0
    47       16   0.400000 0.125000 0.190476           5           73         17          16         14.0
    24       30   0.500000 0.133333 0.210526           8          141         30          30         26.0
    36       31   0.260870 0.193548 0.222222          23          151         31          31         25.0
    63        6   0.333333 0.166667 0.222222           3           26          6           6          5.0
    74       42   0.450000 0.214286 0.290323          20          199         41          42         33.0
    40       18   0.312500 0.277778 0.294118          16           97         20          18         13.0
    72       14   0.307692 0.285714 0.296296          13           62         14          14         10.0
    15       14   0.500000 0.214286 0.300000           6           64         14          14         11.0
    14       16   0.571429 0.250000 0.347826           7           87         18          16         12.0
    50       10   0.428571 0.300000 0.352941           7           67         11          10          7.0
    68       16   0.318182 0.437500 0.368421          22           93         16          16          9.0
    70       37   0.428571 0.324324 0.369231          28          204         44          37         25.0
   106        6   0.300000 0.500000 0.375000          10          132         18           6          3.0
    87       21   0.380952 0.380952 0.380952          21          121         26          21         13.0
     1       21   0.600000 0.285714 0.387097          10           99         21          21         15.0
   103       29   0.562500 0.310345 0.400000          16          133         30          29         20.0

====================
2. M22 TOP CONFUSION PAIRS
====================
 true_label  pred_label  wrong_count  true_support  pred_support
         89           0           25           180            26
         36          51           22            31           178
         59          73           22            85            62
         24          10           20            30           254
         52         104           20            24            89
         89          99           17           180           109
         73          75           16            59            26
         89          60           14           180            38
        104          19           10            84            66
         91          89           10           198           129
         99          85           10           117            24
         99          10            9           117           254
         18         104            9            10            89
        104          68            8            84            22
         74          76            8            42             8
         10          99            7           248           109
         80          59            7            16            59
         46          31            7            76            27
         61          43            7            84           172
          7          28            7            69            27
         47          46            7            16            88
         74          28            7            42            27
         99           8            7           117            84
         26         107            7            89          1357
          2          91            7            81           204
         95          64            7            22           398
         26          43            7            89           172
         64           8            6           375            84
         91          99            6           198           109
         68          99            6            16           109

Saved:
/content/drive/MyDrive/model/M22_selective_ensemble/diagnosis_after_m22/m22_per_class_metrics.csv
/content/drive/MyDrive/model/M22_selective_ensemble/diagnosis_after_m22/m22_confusion_pairs.csv

In [ ]:
# Align M19 and M22 by pill_crop_path
m19_small = m19[[
    "pill_crop_path",
    "true_mapped_label",
    "pred_mapped_label",
    "is_correct"
]].copy()

m19_small = m19_small.rename(columns={
    "pred_mapped_label": "m19_pred",
    "is_correct": "m19_correct"
})

m22_small = m22[[
    "pill_crop_path",
    "true_mapped_label",
    "ensemble_pred_mapped_label",
    "ensemble_is_correct",
    "ensemble_switched_to_m21"
]].copy()

m22_small = m22_small.rename(columns={
    "ensemble_pred_mapped_label": "m22_pred",
    "ensemble_is_correct": "m22_correct"
})

cmp = m19_small.merge(
    m22_small,
    on=["pill_crop_path", "true_mapped_label"],
    how="inner"
)

cmp["case"] = "unknown"
cmp.loc[cmp["m19_correct"] & cmp["m22_correct"], "case"] = "both_correct"
cmp.loc[cmp["m19_correct"] & ~cmp["m22_correct"], "case"] = "m19_only_correct"
cmp.loc[~cmp["m19_correct"] & cmp["m22_correct"], "case"] = "m22_only_correct"
cmp.loc[~cmp["m19_correct"] & ~cmp["m22_correct"], "case"] = "both_wrong"

case_summary = (
    cmp["case"]
    .value_counts()
    .rename_axis("case")
    .reset_index(name="count")
)

case_summary["ratio"] = case_summary["count"] / len(cmp)

print("====================")
print("3. M19 VS M22 CASE SUMMARY")
print("====================")
print(case_summary.to_string(index=False))

per_class_cmp = (
    cmp.groupby("true_mapped_label")
    .agg(
        samples=("pill_crop_path", "count"),
        m19_correct=("m19_correct", "sum"),
        m22_correct=("m22_correct", "sum"),
        m22_switched=("ensemble_switched_to_m21", "sum")
    )
    .reset_index()
    .rename(columns={"true_mapped_label": "label"})
)

per_class_cmp["m19_acc"] = per_class_cmp["m19_correct"] / per_class_cmp["samples"]
per_class_cmp["m22_acc"] = per_class_cmp["m22_correct"] / per_class_cmp["samples"]
per_class_cmp["m22_minus_m19"] = per_class_cmp["m22_acc"] - per_class_cmp["m19_acc"]

print("\n====================")
print("4. CLASSES WHERE M22 IMPROVES OVER M19")
print("====================")
print(
    per_class_cmp
    .sort_values(["m22_minus_m19", "samples"], ascending=[False, False])
    .head(30)
    .to_string(index=False)
)

print("\n====================")
print("5. CLASSES WHERE M22 IS WORSE THAN M19")
print("====================")
print(
    per_class_cmp
    .sort_values(["m22_minus_m19", "samples"], ascending=[True, False])
    .head(30)
    .to_string(index=False)
)

out_dir = Path("/content/drive/MyDrive/model/M22_selective_ensemble/diagnosis_after_m22")
cmp.to_csv(out_dir / "m19_vs_m22_row_level.csv", index=False)
case_summary.to_csv(out_dir / "m19_vs_m22_case_summary.csv", index=False)
per_class_cmp.to_csv(out_dir / "m19_vs_m22_per_class_compare.csv", index=False)

print("\nSaved:")
print(out_dir / "m19_vs_m22_row_level.csv")
print(out_dir / "m19_vs_m22_case_summary.csv")
print(out_dir / "m19_vs_m22_per_class_compare.csv")

====================
3. M19 VS M22 CASE SUMMARY
====================
            case  count    ratio
    both_correct   3194 0.701978
      both_wrong    897 0.197143
m22_only_correct    255 0.056044
m19_only_correct    204 0.044835

====================
4. CLASSES WHERE M22 IMPROVES OVER M19
====================
 label  samples  m19_correct  m22_correct  m22_switched  m19_acc  m22_acc  m22_minus_m19
    68       16            1            7             3 0.062500 0.437500       0.375000
    21        3            0            1             2 0.000000 0.333333       0.333333
    31       16           11           16            16 0.687500 1.000000       0.312500
    50       10            0            3             1 0.000000 0.300000       0.300000
    84       30           17           25             0 0.566667 0.833333       0.266667
   100        4            2            3             3 0.500000 0.750000       0.250000
    72       14            1            4             4 0.071429 0.285714       0.214286
    63        6            0            1             3 0.000000 0.166667       0.166667
    38       19            8           11             2 0.421053 0.578947       0.157895
    17       15           13           15             0 0.866667 1.000000       0.133333
    47       16            0            2             0 0.000000 0.125000       0.125000
     7       69           26           34            11 0.376812 0.492754       0.115942
    89      180           53           73            73 0.294444 0.405556       0.111111
    79       19           13           15             1 0.684211 0.789474       0.105263
    74       42            5            9            15 0.119048 0.214286       0.095238
    41       13            4            5             2 0.307692 0.384615       0.076923
     8       80           44           49             3 0.550000 0.612500       0.062500
    91      198          147          158             9 0.742424 0.797980       0.055556
    65       18           17           18             0 0.944444 1.000000       0.055556
    73       59           22           25             5 0.372881 0.423729       0.050847
    64      375          330          349             5 0.880000 0.930667       0.050667
   104       84           35           39            10 0.416667 0.464286       0.047619
    99      117           50           55            17 0.427350 0.470085       0.042735
    51      147          122          128             3 0.829932 0.870748       0.040816
    27       25           15           16             1 0.600000 0.640000       0.040000
   103       29            8            9             3 0.275862 0.310345       0.034483
    37       33           23           24             2 0.696970 0.727273       0.030303
   107     1296         1278         1278             3 0.986111 0.986111       0.000000
    43      160          137          137             2 0.856250 0.856250       0.000000
    54       60           59           59            56 0.983333 0.983333       0.000000

====================
5. CLASSES WHERE M22 IS WORSE THAN M19
====================
 label  samples  m19_correct  m22_correct  m22_switched  m19_acc  m22_acc  m22_minus_m19
    40       18            8            5             4 0.444444 0.277778      -0.166667
    83        6            6            5             4 1.000000 0.833333      -0.166667
    36       31           11            6             6 0.354839 0.193548      -0.161290
    92       28           28           24            20 1.000000 0.857143      -0.142857
     1       21            9            6             2 0.428571 0.285714      -0.142857
    48        7            1            0             0 0.142857 0.000000      -0.142857
    30       29           29           25             0 1.000000 0.862069      -0.137931
    67       15           13           11             1 0.866667 0.733333      -0.133333
    24       30            8            4            20 0.266667 0.133333      -0.133333
    80       16            2            0             8 0.125000 0.000000      -0.125000
    62        9            9            8             1 1.000000 0.888889      -0.111111
    78        9            7            6             0 0.777778 0.666667      -0.111111
    12        9            8            7             0 0.888889 0.777778      -0.111111
    60       19           19           17             0 1.000000 0.894737      -0.105263
    55       20           12           10             1 0.600000 0.500000      -0.100000
    75       10            3            2             1 0.300000 0.200000      -0.100000
    61       84           77           69             3 0.916667 0.821429      -0.095238
     2       81           62           55            44 0.765432 0.679012      -0.086420
    28       12           12           11             8 1.000000 0.916667      -0.083333
    19       72           54           49             4 0.750000 0.680556      -0.069444
    45       15           14           13             0 0.933333 0.866667      -0.066667
    29       35           23           21            20 0.657143 0.600000      -0.057143
    70       37           14           12             7 0.378378 0.324324      -0.054054
    87       21            9            8             8 0.428571 0.380952      -0.047619
    52       24            3            2             0 0.125000 0.083333      -0.041667
    97       26           26           25             0 1.000000 0.961538      -0.038462
    59       85           39           36            35 0.458824 0.423529      -0.035294
    26       89           77           75             0 0.865169 0.842697      -0.022472
    10      248          206          202           206 0.830645 0.814516      -0.016129
    46       76           66           65             4 0.868421 0.855263      -0.013158

Saved:
/content/drive/MyDrive/model/M22_selective_ensemble/diagnosis_after_m22/m19_vs_m22_row_level.csv
/content/drive/MyDrive/model/M22_selective_ensemble/diagnosis_after_m22/m19_vs_m22_case_summary.csv
/content/drive/MyDrive/model/M22_selective_ensemble/diagnosis_after_m22/m19_vs_m22_per_class_compare.csv

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh train_m23_stage1_visual_classifier.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 291, done.
remote: Counting objects: 100% (169/169), done.
remote: Compressing objects: 100% (147/147), done.
remote: Total 291 (delta 100), reused 22 (delta 22), pack-reused 122 (from 1)
Receiving objects: 100% (291/291), 2.63 MiB | 4.18 MiB/s, done.
Resolving deltas: 100% (155/155), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 23K May  7 07:32 train_m23_stage1_visual_classifier.py

In [ ]:
import os

M23_STAGE1_DIR = "/content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run"
os.makedirs(M23_STAGE1_DIR, exist_ok=True)

print("M23 Stage1 output dir:", M23_STAGE1_DIR)

M23 Stage1 output dir: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run

Mốc để theo dõi

M23 Stage 1 là crop-only visual classifier, nên chưa so trực tiếp với M22 context ensemble. Nhưng nó phải đạt validation đủ tốt để đáng dùng làm backbone cho M24.

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python train_m23_stage1_visual_classifier.py \
  --train_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv \
  --val_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv \
  --test_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv \
  --graph_artifacts_dir /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts \
  --output_dir /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run \
  --backbone_name convnext_tiny.in12k_ft_in1k \
  --epochs 20 \
  --batch_size 32 \
  --lr 5e-5 \
  --class_weight_exponent 0.35 \
  --focal_gamma 1.5 \
  --label_smoothing 0.02 \
  --use_weighted_sampler \
  --sampler_exponent 0.5 \
  --max_sample_weight_ratio 20.0 \
  --freeze_backbone_epochs 1 \
  --patience 5 \
  2>&1 | tee /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run/train_log.txt

/content/vaipe-contextual-pill-recognition
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
=== M23 STAGE 1 VISUAL PRETRAINING ===
Using device: cuda
Train CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv
Val CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv
Test CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv
Graph artifacts dir: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts
Output dir: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run
Num classes: 108
Train pill images existing: 23189 / 23189
Val pill images existing: 4974 / 4974
Train rows: 23189
Val rows: 4974
Train labels: 108
Val labels: 89
Labels in train but missing in val: 19
[np.int64(0), np.int64(3), np.int64(4), np.int64(9), np.int64(13), np.int64(16), np.int64(20), np.int64(25), np.int64(32), np.int64(35), np.int64(44), np.int64(49), np.int64(53), np.int64(66), np.int64(85), np.int64(86), np.int64(94), np.int64(96), np.int64(102)]
Using WeightedRandomSampler
Sampler exponent: 0.5
Max weight ratio: 20.0
Sample weight min: 0.013203693325496157
Sample weight max: 0.26407386650992315
Created M23VisualClassifier
Backbone: convnext_tiny.in12k_ft_in1k
Hidden dim: 512
Dropout: 0.45
Visual backbone frozen: True
Total params: 28797644
Trainable params: 977516
Class weight exponent: 0.35
Class weight min: 0.19293473660945892
Class weight max: 3.98954701423645

M23 Stage1 Visual Epoch [1/20]
Current LR: 0.00005000
Visual backbone frozen: True
Train Loss: 2.7262 | Train Acc: 0.1529 | Train Macro F1: 0.1375
Val Loss  : 1.6063 | Val Acc  : 0.1679 | Val Macro Precision: 0.1391 | Val Macro Recall: 0.2114 | Val Macro F1 Present: 0.1246 | Val Macro F1 All: 0.1165
Saved best checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run/M23_stage1_visual_best.pth
Best Val Macro F1 Present: 0.1246

M23 Stage1 Visual Epoch [2/20]
Current LR: 0.00004969
Visual backbone frozen: False
Rebuilt optimizer after unfreezing.
Train Loss: 1.7297 | Train Acc: 0.4008 | Train Macro F1: 0.3949
Val Loss  : 1.0866 | Val Acc  : 0.4218 | Val Macro Precision: 0.2820 | Val Macro Recall: 0.3514 | Val Macro F1 Present: 0.2839 | Val Macro F1 All: 0.2707
Saved best checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run/M23_stage1_visual_best.pth
Best Val Macro F1 Present: 0.2839

M23 Stage1 Visual Epoch [3/20]
Current LR: 0.00004966
Train Loss: 0.9811 | Train Acc: 0.6043 | Train Macro F1: 0.6252
Val Loss  : 0.9190 | Val Acc  : 0.5310 | Val Macro Precision: 0.3747 | Val Macro Recall: 0.3977 | Val Macro F1 Present: 0.3536 | Val Macro F1 All: 0.3438
Saved best checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run/M23_stage1_visual_best.pth
Best Val Macro F1 Present: 0.3536

M23 Stage1 Visual Epoch [4/20]
Current LR: 0.00004865
Train Loss: 0.6504 | Train Acc: 0.6993 | Train Macro F1: 0.7316
Val Loss  : 0.8683 | Val Acc  : 0.5728 | Val Macro Precision: 0.3955 | Val Macro Recall: 0.4136 | Val Macro F1 Present: 0.3771 | Val Macro F1 All: 0.3596
Saved best checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run/M23_stage1_visual_best.pth
Best Val Macro F1 Present: 0.3771

M23 Stage1 Visual Epoch [5/20]
Current LR: 0.00004699
Train Loss: 0.4765 | Train Acc: 0.7532 | Train Macro F1: 0.7880
Val Loss  : 0.8814 | Val Acc  : 0.5581 | Val Macro Precision: 0.3678 | Val Macro Recall: 0.4141 | Val Macro F1 Present: 0.3710 | Val Macro F1 All: 0.3538
No significant improvement. bad_epochs=1/5

M23 Stage1 Visual Epoch [6/20]
Current LR: 0.00004473
Train Loss: 0.3517 | Train Acc: 0.8015 | Train Macro F1: 0.8399
Val Loss  : 0.8774 | Val Acc  : 0.5722 | Val Macro Precision: 0.3934 | Val Macro Recall: 0.3907 | Val Macro F1 Present: 0.3662 | Val Macro F1 All: 0.3526
No significant improvement. bad_epochs=2/5

M23 Stage1 Visual Epoch [7/20]
Current LR: 0.00004193
Train Loss: 0.2732 | Train Acc: 0.8366 | Train Macro F1: 0.8724
Val Loss  : 0.8652 | Val Acc  : 0.5881 | Val Macro Precision: 0.3973 | Val Macro Recall: 0.4105 | Val Macro F1 Present: 0.3884 | Val Macro F1 All: 0.3632
Saved best checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run/M23_stage1_visual_best.pth
Best Val Macro F1 Present: 0.3884

M23 Stage1 Visual Epoch [8/20]
Current LR: 0.00003867
Train Loss: 0.2095 | Train Acc: 0.8665 | Train Macro F1: 0.8999
Val Loss  : 0.8740 | Val Acc  : 0.6140 | Val Macro Precision: 0.4182 | Val Macro Recall: 0.4124 | Val Macro F1 Present: 0.3972 | Val Macro F1 All: 0.3678
Saved best checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run/M23_stage1_visual_best.pth
Best Val Macro F1 Present: 0.3972

M23 Stage1 Visual Epoch [9/20]
Current LR: 0.00003504
Train Loss: 0.1604 | Train Acc: 0.8911 | Train Macro F1: 0.9231
Val Loss  : 0.8693 | Val Acc  : 0.6144 | Val Macro Precision: 0.4359 | Val Macro Recall: 0.4115 | Val Macro F1 Present: 0.4021 | Val Macro F1 All: 0.3797
Saved best checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run/M23_stage1_visual_best.pth
Best Val Macro F1 Present: 0.4021

M23 Stage1 Visual Epoch [10/20]
Current LR: 0.00003114
Train Loss: 0.1280 | Train Acc: 0.9106 | Train Macro F1: 0.9376
Val Loss  : 0.9111 | Val Acc  : 0.6138 | Val Macro Precision: 0.4080 | Val Macro Recall: 0.3923 | Val Macro F1 Present: 0.3809 | Val Macro F1 All: 0.3597
No significant improvement. bad_epochs=1/5

M23 Stage1 Visual Epoch [11/20]
Current LR: 0.00002706
Train Loss: 0.0954 | Train Acc: 0.9310 | Train Macro F1: 0.9535
Val Loss  : 0.9295 | Val Acc  : 0.6182 | Val Macro Precision: 0.4158 | Val Macro Recall: 0.3963 | Val Macro F1 Present: 0.3900 | Val Macro F1 All: 0.3611
No significant improvement. bad_epochs=2/5

M23 Stage1 Visual Epoch [12/20]
Current LR: 0.00002294
Train Loss: 0.0740 | Train Acc: 0.9443 | Train Macro F1: 0.9624
Val Loss  : 0.9264 | Val Acc  : 0.6397 | Val Macro Precision: 0.4556 | Val Macro Recall: 0.4204 | Val Macro F1 Present: 0.4214 | Val Macro F1 All: 0.3863
Saved best checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run/M23_stage1_visual_best.pth
Best Val Macro F1 Present: 0.4214

M23 Stage1 Visual Epoch [13/20]
Current LR: 0.00001886
Train Loss: 0.0532 | Train Acc: 0.9593 | Train Macro F1: 0.9752
Val Loss  : 0.9435 | Val Acc  : 0.6450 | Val Macro Precision: 0.4539 | Val Macro Recall: 0.4209 | Val Macro F1 Present: 0.4206 | Val Macro F1 All: 0.3894
No significant improvement. bad_epochs=1/5

M23 Stage1 Visual Epoch [14/20]
Current LR: 0.00001496
Train Loss: 0.0372 | Train Acc: 0.9711 | Train Macro F1: 0.9835
Val Loss  : 0.9548 | Val Acc  : 0.6558 | Val Macro Precision: 0.4712 | Val Macro Recall: 0.4244 | Val Macro F1 Present: 0.4309 | Val Macro F1 All: 0.3910
Saved best checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run/M23_stage1_visual_best.pth
Best Val Macro F1 Present: 0.4309

M23 Stage1 Visual Epoch [15/20]
Current LR: 0.00001133
Train Loss: 0.0287 | Train Acc: 0.9783 | Train Macro F1: 0.9877
Val Loss  : 0.9747 | Val Acc  : 0.6594 | Val Macro Precision: 0.4759 | Val Macro Recall: 0.4171 | Val Macro F1 Present: 0.4253 | Val Macro F1 All: 0.3859
No significant improvement. bad_epochs=1/5

M23 Stage1 Visual Epoch [16/20]
Current LR: 0.00000807
Train Loss: 0.0202 | Train Acc: 0.9843 | Train Macro F1: 0.9914
Val Loss  : 0.9847 | Val Acc  : 0.6560 | Val Macro Precision: 0.4542 | Val Macro Recall: 0.4087 | Val Macro F1 Present: 0.4142 | Val Macro F1 All: 0.3797
No significant improvement. bad_epochs=2/5

M23 Stage1 Visual Epoch [17/20]
Current LR: 0.00000527
Train Loss: 0.0144 | Train Acc: 0.9897 | Train Macro F1: 0.9946
Val Loss  : 1.0025 | Val Acc  : 0.6600 | Val Macro Precision: 0.4757 | Val Macro Recall: 0.4105 | Val Macro F1 Present: 0.4216 | Val Macro F1 All: 0.3904
No significant improvement. bad_epochs=3/5

M23 Stage1 Visual Epoch [18/20]
Current LR: 0.00000301
Train Loss: 0.0126 | Train Acc: 0.9909 | Train Macro F1: 0.9954
Val Loss  : 0.9910 | Val Acc  : 0.6649 | Val Macro Precision: 0.4797 | Val Macro Recall: 0.4165 | Val Macro F1 Present: 0.4278 | Val Macro F1 All: 0.3961
No significant improvement. bad_epochs=4/5

M23 Stage1 Visual Epoch [19/20]
Current LR: 0.00000135
Train Loss: 0.0099 | Train Acc: 0.9938 | Train Macro F1: 0.9967
Val Loss  : 0.9936 | Val Acc  : 0.6667 | Val Macro Precision: 0.4799 | Val Macro Recall: 0.4193 | Val Macro F1 Present: 0.4300 | Val Macro F1 All: 0.3981
No significant improvement. bad_epochs=5/5
Early stopping triggered after 5 non-improving epochs.

M23 Stage1 training done.
Best checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run/M23_stage1_visual_best.pth
Best Val Macro F1 Present: 0.43093027809323986
Last checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run/M23_stage1_visual_last.pth

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh train_m23_stage1_visual_classifier_v2.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 294, done.
remote: Counting objects: 100% (172/172), done.
remote: Compressing objects: 100% (150/150), done.
remote: Total 294 (delta 101), reused 22 (delta 22), pack-reused 122 (from 1)
Receiving objects: 100% (294/294), 2.64 MiB | 5.68 MiB/s, done.
Resolving deltas: 100% (156/156), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 16K May  7 08:35 train_m23_stage1_visual_classifier_v2.py

In [ ]:
import os

M23_STAGE1_V2_DIR = "/content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run_v2_ce"
os.makedirs(M23_STAGE1_V2_DIR, exist_ok=True)

print("M23 Stage1 v2 output dir:", M23_STAGE1_V2_DIR)

M23 Stage1 v2 output dir: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run_v2_ce

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python train_m23_stage1_visual_classifier_v2.py \
  --train_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv \
  --val_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv \
  --test_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv \
  --graph_artifacts_dir /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts \
  --output_dir /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run_v2_ce \
  --backbone_name convnext_tiny.in12k_ft_in1k \
  --epochs 20 \
  --batch_size 32 \
  --lr 3e-5 \
  --class_weight_exponent 0.20 \
  --label_smoothing 0.05 \
  --dropout_p 0.55 \
  --freeze_backbone_epochs 1 \
  --patience 5 \
  2>&1 | tee /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run_v2_ce/train_log.txt

/content/vaipe-contextual-pill-recognition
=== M23 STAGE 1 VISUAL PRETRAINING V2 ===
Using device: cuda
Train CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv
Val CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv
Test CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv
Graph artifacts dir: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts
Output dir: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run_v2_ce
Num classes: 108
Train pill images existing: 23189 / 23189
Val pill images existing: 4974 / 4974
Train rows: 23189
Val rows: 4974
Train labels: 108
Val labels: 89
Labels in train but missing in val: 19
[np.int64(0), np.int64(3), np.int64(4), np.int64(9), np.int64(13), np.int64(16), np.int64(20), np.int64(25), np.int64(32), np.int64(35), np.int64(44), np.int64(49), np.int64(53), np.int64(66), np.int64(85), np.int64(86), np.int64(94), np.int64(96), np.int64(102)]
Created M23VisualClassifier v2
Backbone: convnext_tiny.in12k_ft_in1k
Hidden dim: 512
Dropout: 0.55
Loss: CrossEntropyLoss
Weighted sampler: False
Visual backbone frozen: True
Total params: 28797644
Trainable params: 977516
Class weight exponent: 0.2
Class weight min: 0.40375038981437683
Class weight max: 2.279474973678589

M23 Stage1 v2 Visual Epoch [1/20]
Current LR: 0.00003000
Visual backbone frozen: True
Train Loss: 3.9975 | Train Acc: 0.2916 | Train Macro F1: 0.0173
Val Loss  : 3.4396 | Val Acc  : 0.3542 | Val Macro Precision: 0.0677 | Val Macro Recall: 0.0390 | Val Macro F1 Present: 0.0340 | Val Macro F1 All: 0.0280
Saved best checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run_v2_ce/M23_stage1_v2_visual_best.pth
Best Val Macro F1 Present: 0.0340

M23 Stage1 v2 Visual Epoch [2/20]
Current LR: 0.00002982
Visual backbone frozen: False
Rebuilt optimizer after unfreezing.
Train Loss: 3.1577 | Train Acc: 0.4684 | Train Macro F1: 0.1206
Val Loss  : 2.6413 | Val Acc  : 0.5643 | Val Macro Precision: 0.2610 | Val Macro Recall: 0.2114 | Val Macro F1 Present: 0.2060 | Val Macro F1 All: 0.1736
Saved best checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run_v2_ce/M23_stage1_v2_visual_best.pth
Best Val Macro F1 Present: 0.2060

M23 Stage1 v2 Visual Epoch [3/20]
Current LR: 0.00002980
Train Loss: 2.5009 | Train Acc: 0.6070 | Train Macro F1: 0.2936
Val Loss  : 2.3097 | Val Acc  : 0.6309 | Val Macro Precision: 0.4144 | Val Macro Recall: 0.3347 | Val Macro F1 Present: 0.3423 | Val Macro F1 All: 0.2884
Saved best checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run_v2_ce/M23_stage1_v2_visual_best.pth
Best Val Macro F1 Present: 0.3423

M23 Stage1 v2 Visual Epoch [4/20]
Current LR: 0.00002919
Train Loss: 2.1130 | Train Acc: 0.6782 | Train Macro F1: 0.4185
Val Loss  : 2.1489 | Val Acc  : 0.6568 | Val Macro Precision: 0.4657 | Val Macro Recall: 0.3796 | Val Macro F1 Present: 0.3834 | Val Macro F1 All: 0.3302
Saved best checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run_v2_ce/M23_stage1_v2_visual_best.pth
Best Val Macro F1 Present: 0.3834

M23 Stage1 v2 Visual Epoch [5/20]
Current LR: 0.00002819
Train Loss: 1.8732 | Train Acc: 0.7241 | Train Macro F1: 0.5046
Val Loss  : 2.1387 | Val Acc  : 0.6512 | Val Macro Precision: 0.4945 | Val Macro Recall: 0.3929 | Val Macro F1 Present: 0.4086 | Val Macro F1 All: 0.3480
Saved best checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run_v2_ce/M23_stage1_v2_visual_best.pth
Best Val Macro F1 Present: 0.4086

M23 Stage1 v2 Visual Epoch [6/20]
Current LR: 0.00002684
Train Loss: 1.6869 | Train Acc: 0.7551 | Train Macro F1: 0.5569
Val Loss  : 2.1074 | Val Acc  : 0.6614 | Val Macro Precision: 0.4827 | Val Macro Recall: 0.4085 | Val Macro F1 Present: 0.4054 | Val Macro F1 All: 0.3566
No significant improvement. bad_epochs=1/5

M23 Stage1 v2 Visual Epoch [7/20]
Current LR: 0.00002516
Train Loss: 1.5269 | Train Acc: 0.7883 | Train Macro F1: 0.5975
Val Loss  : 2.1528 | Val Acc  : 0.6614 | Val Macro Precision: 0.4719 | Val Macro Recall: 0.4221 | Val Macro F1 Present: 0.4131 | Val Macro F1 All: 0.3672
Saved best checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run_v2_ce/M23_stage1_v2_visual_best.pth
Best Val Macro F1 Present: 0.4131

M23 Stage1 v2 Visual Epoch [8/20]
Current LR: 0.00002320
Train Loss: 1.4060 | Train Acc: 0.8152 | Train Macro F1: 0.6370
Val Loss  : 2.1496 | Val Acc  : 0.6628 | Val Macro Precision: 0.4833 | Val Macro Recall: 0.4076 | Val Macro F1 Present: 0.4173 | Val Macro F1 All: 0.3748
Saved best checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run_v2_ce/M23_stage1_v2_visual_best.pth
Best Val Macro F1 Present: 0.4173

M23 Stage1 v2 Visual Epoch [9/20]
Current LR: 0.00002103
Train Loss: 1.2863 | Train Acc: 0.8453 | Train Macro F1: 0.6813
Val Loss  : 2.2280 | Val Acc  : 0.6492 | Val Macro Precision: 0.4736 | Val Macro Recall: 0.4212 | Val Macro F1 Present: 0.4172 | Val Macro F1 All: 0.3747
No significant improvement. bad_epochs=1/5

M23 Stage1 v2 Visual Epoch [10/20]
Current LR: 0.00001868
Train Loss: 1.1889 | Train Acc: 0.8683 | Train Macro F1: 0.7062
Val Loss  : 2.2032 | Val Acc  : 0.6709 | Val Macro Precision: 0.4589 | Val Macro Recall: 0.4160 | Val Macro F1 Present: 0.4135 | Val Macro F1 All: 0.3790
No significant improvement. bad_epochs=2/5

M23 Stage1 v2 Visual Epoch [11/20]
Current LR: 0.00001624
Train Loss: 1.0982 | Train Acc: 0.8942 | Train Macro F1: 0.7622
Val Loss  : 2.2411 | Val Acc  : 0.6649 | Val Macro Precision: 0.4606 | Val Macro Recall: 0.4178 | Val Macro F1 Present: 0.4181 | Val Macro F1 All: 0.3755
Saved best checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run_v2_ce/M23_stage1_v2_visual_best.pth
Best Val Macro F1 Present: 0.4181

M23 Stage1 v2 Visual Epoch [12/20]
Current LR: 0.00001376
Train Loss: 1.0145 | Train Acc: 0.9174 | Train Macro F1: 0.8018
Val Loss  : 2.2619 | Val Acc  : 0.6661 | Val Macro Precision: 0.4508 | Val Macro Recall: 0.4241 | Val Macro F1 Present: 0.4166 | Val Macro F1 All: 0.3781
No significant improvement. bad_epochs=1/5

M23 Stage1 v2 Visual Epoch [13/20]
Current LR: 0.00001132
Train Loss: 0.9443 | Train Acc: 0.9352 | Train Macro F1: 0.8228
Val Loss  : 2.3072 | Val Acc  : 0.6572 | Val Macro Precision: 0.4430 | Val Macro Recall: 0.4182 | Val Macro F1 Present: 0.4098 | Val Macro F1 All: 0.3719
No significant improvement. bad_epochs=2/5

M23 Stage1 v2 Visual Epoch [14/20]
Current LR: 0.00000897
Train Loss: 0.8881 | Train Acc: 0.9498 | Train Macro F1: 0.8528
Val Loss  : 2.3194 | Val Acc  : 0.6667 | Val Macro Precision: 0.4809 | Val Macro Recall: 0.4346 | Val Macro F1 Present: 0.4327 | Val Macro F1 All: 0.3806
Saved best checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run_v2_ce/M23_stage1_v2_visual_best.pth
Best Val Macro F1 Present: 0.4327

M23 Stage1 v2 Visual Epoch [15/20]
Current LR: 0.00000680
Train Loss: 0.8450 | Train Acc: 0.9615 | Train Macro F1: 0.8738
Val Loss  : 2.3382 | Val Acc  : 0.6649 | Val Macro Precision: 0.4535 | Val Macro Recall: 0.4163 | Val Macro F1 Present: 0.4134 | Val Macro F1 All: 0.3789
No significant improvement. bad_epochs=1/5

M23 Stage1 v2 Visual Epoch [16/20]
Current LR: 0.00000484
Train Loss: 0.8059 | Train Acc: 0.9719 | Train Macro F1: 0.9072
Val Loss  : 2.3715 | Val Acc  : 0.6683 | Val Macro Precision: 0.4454 | Val Macro Recall: 0.4229 | Val Macro F1 Present: 0.4157 | Val Macro F1 All: 0.3811
No significant improvement. bad_epochs=2/5

M23 Stage1 v2 Visual Epoch [17/20]
Current LR: 0.00000316
Train Loss: 0.7804 | Train Acc: 0.9796 | Train Macro F1: 0.9240
Val Loss  : 2.3684 | Val Acc  : 0.6679 | Val Macro Precision: 0.4569 | Val Macro Recall: 0.4298 | Val Macro F1 Present: 0.4249 | Val Macro F1 All: 0.3816
No significant improvement. bad_epochs=3/5

M23 Stage1 v2 Visual Epoch [18/20]
Current LR: 0.00000181
Train Loss: 0.7638 | Train Acc: 0.9828 | Train Macro F1: 0.9327
Val Loss  : 2.3756 | Val Acc  : 0.6697 | Val Macro Precision: 0.4640 | Val Macro Recall: 0.4298 | Val Macro F1 Present: 0.4282 | Val Macro F1 All: 0.3885
No significant improvement. bad_epochs=4/5

M23 Stage1 v2 Visual Epoch [19/20]
Current LR: 0.00000081
Train Loss: 0.7524 | Train Acc: 0.9867 | Train Macro F1: 0.9387
Val Loss  : 2.3796 | Val Acc  : 0.6699 | Val Macro Precision: 0.4640 | Val Macro Recall: 0.4271 | Val Macro F1 Present: 0.4238 | Val Macro F1 All: 0.3846
No significant improvement. bad_epochs=5/5
Early stopping triggered after 5 non-improving epochs.

M23 Stage1 v2 training done.
Best checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run_v2_ce/M23_stage1_v2_visual_best.pth
Best Val Macro F1 Present: 0.43270142577402326
Last checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run_v2_ce/M23_stage1_v2_visual_last.pth

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh evaluate_m23_stage1_visual_classifier.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 297, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 297 (delta 23), reused 22 (delta 22), pack-reused 271 (from 2)
Receiving objects: 100% (297/297), 2.64 MiB | 4.33 MiB/s, done.
Resolving deltas: 100% (158/158), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 9.8K May  7 09:41 evaluate_m23_stage1_visual_classifier.py

In [ ]:
import os

M23_V2_TEST_DIR = "/content/drive/MyDrive/model/M23_stage1_visual_pretraining/test_eval_v2_ce"
os.makedirs(M23_V2_TEST_DIR, exist_ok=True)

print("M23 v2 test output dir:", M23_V2_TEST_DIR)

M23 v2 test output dir: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/test_eval_v2_ce

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python evaluate_m23_stage1_visual_classifier.py \
  --checkpoint /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run_v2_ce/M23_stage1_v2_visual_best.pth \
  --eval_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv \
  --output_dir /content/drive/MyDrive/model/M23_stage1_visual_pretraining/test_eval_v2_ce \
  --batch_size 32 \
  2>&1 | tee /content/drive/MyDrive/model/M23_stage1_visual_pretraining/test_eval_v2_ce/test_log.txt

/content/vaipe-contextual-pill-recognition
=== EVALUATE M23 STAGE1 VISUAL CLASSIFIER ===
Using device: cuda
Checkpoint: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/train_run_v2_ce/M23_stage1_v2_visual_best.pth
Eval CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv
Output dir: /content/drive/MyDrive/model/M23_stage1_visual_pretraining/test_eval_v2_ce
Model type: M23VisualClassifier
Stage: M23_stage1_visual_pretraining_v2
Epoch: 14
Checkpoint Val Macro F1 Present: 0.43270142577402326
Num classes: 108
Backbone: convnext_tiny.in12k_ft_in1k
Hidden dim: 512
Dropout: 0.55
Image size: 224
Eval pill images existing: 4550 / 4550

Eval rows: 4550
Eval labels: 82
Mapped label min: 1
Mapped label max: 107
Evaluating M23 visual: 100%|██████████| 143/143 [00:34<00:00,  4.20it/s]

=== M23 VISUAL EVAL RESULTS ===
Accuracy                 : 0.660879
Macro Precision Present  : 0.415024
Macro Recall Present     : 0.382786
Macro F1 Present Classes : 0.379619
Macro F1 All Classes     : 0.333925
Weighted F1              : 0.653568

Saved files:
/content/drive/MyDrive/model/M23_stage1_visual_pretraining/test_eval_v2_ce/m23_visual_eval_metrics.json
/content/drive/MyDrive/model/M23_stage1_visual_pretraining/test_eval_v2_ce/m23_visual_eval_predictions.csv
/content/drive/MyDrive/model/M23_stage1_visual_pretraining/test_eval_v2_ce/m23_visual_eval_probs.npy
/content/drive/MyDrive/model/M23_stage1_visual_pretraining/test_eval_v2_ce/m23_visual_per_class_metrics.csv
/content/drive/MyDrive/model/M23_stage1_visual_pretraining/test_eval_v2_ce/m23_visual_confusion_pairs.csv

Dọn repo và benchmark:
- README tách old validation result và clean test result.
- Tạo EXPERIMENTS_M17_M23.md.
- Tạo audit_pika_paper_protocol.py.

Tạo paper-compatible benchmark:
- Nếu mục tiêu báo cáo là vượt paper, phải có track này.

M24 metric visual training:
- CE + SupCon + ArcFace/CosFace.
- hard pair sampler.
- backbone DINOv2/ConvNeXtV2/EVA/ConvNeXt base.

Evaluate M24 trên val/test:
- Nếu M24 visual-only không vượt M23 rõ rệt, chỉnh metric learning.
- Nếu M24 cứu hard classes, đưa vào ensemble.

M26 context PIKA với M24 pretrained visual:
- Kế thừa M19 architecture.
- Thêm hard-pair auxiliary loss.

M27 stacked ensemble:
- M19 + M21 + M24 + M26.
- Tune bằng validation only.
- Apply test once.

Nếu cần full pipeline:
- train detector hiện đại.
- đánh giá end-to-end.

In [ ]:
import os

AUDIT_DIR = "/content/drive/MyDrive/model/audit_pika_protocol_v1"
os.makedirs(AUDIT_DIR, exist_ok=True)

print("Audit output dir:", AUDIT_DIR)

Audit output dir: /content/drive/MyDrive/model/audit_pika_protocol_v1

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python audit_pika_paper_protocol.py \
  --train_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv \
  --val_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv \
  --test_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv \
  --m19_predictions /content/drive/MyDrive/model/M22_selective_ensemble/test_predictions/m19_val_predictions.csv \
  --m22_predictions /content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1/test_ensemble_predictions.csv \
  --output_dir /content/drive/MyDrive/model/audit_pika_protocol_v1 \
  2>&1 | tee /content/drive/MyDrive/model/audit_pika_protocol_v1/audit_log.txt

/content/vaipe-contextual-pill-recognition
=== AUDIT PIKA PAPER PROTOCOL / CLEAN SPLIT ===
Train CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv
Val CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv
Test CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv
Output dir: /content/drive/MyDrive/model/audit_pika_protocol_v1

=== SPLIT SUMMARY ===
split  rows  groups  labels_present  min_class_count  max_class_count  median_class_count  mean_class_count
train 23189     597             108                1             5736                75.5        214.712963
  val  4974     219              89                1             1345                20.0         55.887640
 test  4550     357              82                1             1296                18.5         55.487805

=== PATH CHECK ===
split  pill_crop_path_existing  pill_crop_path_missing  pill_crop_path_total  prescription_image_path_existing  prescription_image_path_missing  prescription_image_path_total
train                    23189                       0                 23189                             23189                                0                          23189
  val                     4974                       0                  4974                              4974                                0                           4974
 test                     4550                       0                  4550                              4550                                0                           4550

=== LEAKAGE CHECK ===
Group leakage rows: 0
Pill path leakage rows: 0
Prescription path leakage rows: 0

=== LABEL COVERAGE ===
Train labels: 108
Val labels: 89
Test labels: 82
Labels in all splits: 82
Train labels missing in val: 19
Train labels missing in test: 26
Test labels not in train: 0

=== SUPPORT BINS ===
           bin  num_labels  train_rows  val_rows  test_rows  labels_in_all_splits  labels_missing_in_val  labels_missing_in_test
       train_1           2           2         0          0                     0                      2                       2
     train_2_5           2           6         0          0                     0                      2                       2
    train_6_10           4          28         3          1                     1                      2                       3
   train_11_30          15         325        70         31                     8                      4                       7
  train_31_100          46        3069       588        450                    35                      8                      11
 train_101_500          31        6896      1432       1347                    30                      1                       1
train_501_plus           8       12863      2881       2721                     8                      0                       0

=== CANDIDATE BENCHMARKS ===
                         candidate  num_labels  train_rows  val_rows  test_rows  min_train_count  max_train_count
                  all_train_labels         108       23189      4974       4550                1             5736
       labels_present_in_train_val          89       22501      4974       4550                6             5736
      labels_present_in_train_test          82       22264      4897       4550                6             5736
      labels_present_in_all_splits          82       22264      4897       4550                6             5736
    train_support_ge_5_and_in_test          82       22264      4897       4550                6             5736
   train_support_ge_10_and_in_test          81       22258      4896       4549               12             5736
   train_support_ge_30_and_in_test          73       22094      4849       4518               36             5736
   train_support_ge_50_and_in_test          66       21800      4784       4467               50             5736
  train_support_ge_100_and_in_test          38       19627      4313       4068              109             5736
train_support_ge_30_and_all_splits          73       22094      4849       4518               36             5736
train_support_ge_50_and_all_splits          66       21800      4784       4467               50             5736

=== OPTIONAL PREDICTION METRICS ===
model  rows  accuracy  macro_f1_present  macro_f1_all  weighted_f1
  m19  4550  0.746813          0.443011      0.397890     0.744192
  m22  4550  0.758022          0.462450      0.411067     0.750668
Saved report: /content/drive/MyDrive/model/audit_pika_protocol_v1/audit_report.md

=== DONE ===
Main report: /content/drive/MyDrive/model/audit_pika_protocol_v1/audit_report.md

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh evaluate_candidate_benchmarks.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 303, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 303 (delta 25), reused 22 (delta 22), pack-reused 271 (from 2)
Receiving objects: 100% (303/303), 2.64 MiB | 4.84 MiB/s, done.
Resolving deltas: 100% (160/160), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 6.3K May  7 11:12 evaluate_candidate_benchmarks.py

In [ ]:
import os

CANDIDATE_EVAL_DIR = "/content/drive/MyDrive/model/audit_pika_protocol_v1/candidate_eval"
os.makedirs(CANDIDATE_EVAL_DIR, exist_ok=True)

print("Candidate eval output dir:", CANDIDATE_EVAL_DIR)

Candidate eval output dir: /content/drive/MyDrive/model/audit_pika_protocol_v1/candidate_eval

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python evaluate_candidate_benchmarks.py \
  --candidates_csv /content/drive/MyDrive/model/audit_pika_protocol_v1/audit_candidate_benchmarks.csv \
  --m19_predictions /content/drive/MyDrive/model/M22_selective_ensemble/test_predictions/m19_val_predictions.csv \
  --m22_predictions /content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1/test_ensemble_predictions.csv \
  --output_dir /content/drive/MyDrive/model/audit_pika_protocol_v1/candidate_eval \
  2>&1 | tee /content/drive/MyDrive/model/audit_pika_protocol_v1/candidate_eval/candidate_eval_log.txt

/content/vaipe-contextual-pill-recognition
=== EVALUATE CANDIDATE BENCHMARKS ===
Candidate file: /content/drive/MyDrive/model/audit_pika_protocol_v1/audit_candidate_benchmarks.csv
M19 predictions: /content/drive/MyDrive/model/M22_selective_ensemble/test_predictions/m19_val_predictions.csv
M22 predictions: /content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1/test_ensemble_predictions.csv
Output dir: /content/drive/MyDrive/model/audit_pika_protocol_v1/candidate_eval

=== CANDIDATE BENCHMARK RESULTS ===
model                          candidate  candidate_num_labels  eval_rows  accuracy  macro_f1_present  macro_f1_all_candidate  weighted_f1
  M19                   all_train_labels                   108       4550  0.746813          0.443011                0.397890     0.744192
  M22                   all_train_labels                   108       4550  0.758022          0.462450                0.411067     0.750668
  M19        labels_present_in_train_val                    89       4550  0.746813          0.443011                0.482832     0.744192
  M22        labels_present_in_train_val                    89       4550  0.758022          0.462450                0.498822     0.750668
  M19       labels_present_in_train_test                    82       4550  0.746813          0.443011                0.524050     0.744192
  M19       labels_present_in_all_splits                    82       4550  0.746813          0.443011                0.524050     0.744192
  M19     train_support_ge_5_and_in_test                    82       4550  0.746813          0.443011                0.524050     0.744192
  M22       labels_present_in_train_test                    82       4550  0.758022          0.462450                0.541405     0.750668
  M22       labels_present_in_all_splits                    82       4550  0.758022          0.462450                0.541405     0.750668
  M22     train_support_ge_5_and_in_test                    82       4550  0.758022          0.462450                0.541405     0.750668
  M19    train_support_ge_10_and_in_test                    81       4549  0.746977          0.447697                0.530604     0.744384
  M22    train_support_ge_10_and_in_test                    81       4549  0.758189          0.462584                0.548248     0.750893
  M19    train_support_ge_30_and_in_test                    73       4518  0.750332          0.438215                0.558274     0.749155
  M19 train_support_ge_30_and_all_splits                    73       4518  0.750332          0.438215                0.558274     0.749155
  M22    train_support_ge_30_and_in_test                    73       4518  0.760956          0.436202                0.573636     0.755233
  M22 train_support_ge_30_and_all_splits                    73       4518  0.760956          0.436202                0.573636     0.755233
  M19    train_support_ge_50_and_in_test                    66       4467  0.752407          0.405085                0.558526     0.752864
  M19 train_support_ge_50_and_all_splits                    66       4467  0.752407          0.405085                0.558526     0.752864
  M22    train_support_ge_50_and_in_test                    66       4467  0.763824          0.408477                0.575581     0.759428
  M22 train_support_ge_50_and_all_splits                    66       4467  0.763824          0.408477                0.575581     0.759428
  M19   train_support_ge_100_and_in_test                    38       4068  0.781465          0.303411                0.670697     0.797137
  M22   train_support_ge_100_and_in_test                    38       4068  0.792773          0.303648                0.679213     0.803958

Saved:
/content/drive/MyDrive/model/audit_pika_protocol_v1/candidate_eval/candidate_benchmark_results.csv
/content/drive/MyDrive/model/audit_pika_protocol_v1/candidate_eval/candidate_benchmark_results_pivot.csv


Tạo hard-pair metadata từ M22 confusion.


Train M24 metric visual model:
- backbone mạnh hơn
- CE + SupCon / ArcFace
- hard-pair sampler


Evaluate M24 visual-only:
- tổng metric
- hard classes
- M24 đúng/M22 sai


Nếu M24 cứu được hard classes:
- đưa M24 vào ensemble hoặc PIKA context model.


Nếu M24 không cứu hard classes:
- đổi backbone lên DINOv2 / EVA / ConvNeXt Base.

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh build_m24_hard_pair_metadata.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 306, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 306 (delta 26), reused 22 (delta 22), pack-reused 271 (from 2)
Receiving objects: 100% (306/306), 2.65 MiB | 6.51 MiB/s, done.
Resolving deltas: 100% (161/161), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 17K May  7 11:20 build_m24_hard_pair_metadata.py

In [ ]:
import os

M24_META_DIR = "/content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata"
os.makedirs(M24_META_DIR, exist_ok=True)

print("M24 metadata output dir:", M24_META_DIR)

M24 metadata output dir: /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python build_m24_hard_pair_metadata.py \
  --train_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv \
  --val_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv \
  --test_csv /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv \
  --graph_artifacts_dir /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts \
  --m22_confusion_pairs /content/drive/MyDrive/model/M22_selective_ensemble/diagnosis_after_m22/m22_confusion_pairs.csv \
  --m22_per_class_metrics /content/drive/MyDrive/model/M22_selective_ensemble/diagnosis_after_m22/m22_per_class_metrics.csv \
  --output_dir /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata \
  --min_wrong_count 5 \
  --top_k_per_true 3 \
  --make_symmetric \
  --f1_threshold 0.45 \
  --recall_threshold 0.35 \
  --min_support 3 \
  --min_error_count 7 \
  --hard_weight_boost 1.5 \
  2>&1 | tee /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/build_log.txt

/content/vaipe-contextual-pill-recognition
=== BUILD M24 HARD PAIR METADATA ===
Train CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/train_clean.csv
Val CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/val_clean.csv
Test CSV: /content/drive/MyDrive/vaipe_splits/clean_paper_like_split_v2/test_clean.csv
Graph artifacts dir: /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts
M22 confusion pairs: /content/drive/MyDrive/model/M22_selective_ensemble/diagnosis_after_m22/m22_confusion_pairs.csv
M22 per-class metrics: /content/drive/MyDrive/model/M22_selective_ensemble/diagnosis_after_m22/m22_per_class_metrics.csv
Output dir: /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata

=== HARD PAIR EDGES TOP 30 ===
 true_label  pred_label  wrong_count  true_support  pred_support
         89           0           25           180            26
         59          73           22            85            62
         36          51           22            31           178
         24          10           20            30           254
         52         104           20            24            89
         89          99           17           180           109
         73          75           16            59            26
         89          60           14           180            38
         91          89           10           198           129
        104          19           10            84            66
         99          85           10           117            24
         99          10            9           117           254
         18         104            9            10            89
         74          76            8            42             8
        104          68            8            84            22
         26         107            7            89          1357
         10          99            7           248           109
         47          46            7            16            88
         26          43            7            89           172
          7          28            7            69            27
          2          91            7            81           204
         99           8            7           117            84
         80          59            7            16            59
         61          43            7            84           172
         46          31            7            76            27
         74          28            7            42            27
         95          64            7            22           398
         91          99            6           198           109
         64           8            6           375            84
         40          39            6            18            10

=== HARD CLASS SUMMARY TOP 40 ===
 mapped_label  support  precision   recall       f1  error_count  is_hard_class                                                                                           hard_class_reason hard_negative_labels  num_hard_negatives  hard_class_weight
           80       16   0.000000 0.000000 0.000000         16.0           True                              low_f1<=0.45|low_recall<=0.35|high_error_count>=7|appears_as_true_in_confusion                   59                   1           3.250000
           18       10   0.000000 0.000000 0.000000         10.0           True                              low_f1<=0.45|low_recall<=0.35|high_error_count>=7|appears_as_true_in_confusion                  104                   1           3.250000
           81        8   0.000000 0.000000 0.000000          8.0           True                              low_f1<=0.45|low_recall<=0.35|high_error_count>=7|appears_as_true_in_confusion                   64                   1           3.250000
            5        7   0.000000 0.000000 0.000000          7.0           True                              low_f1<=0.45|low_recall<=0.35|high_error_count>=7|appears_as_true_in_confusion                   70                   1           3.250000
           76        4   0.000000 0.000000 0.000000          4.0           True                                                  low_f1<=0.45|low_recall<=0.35|appears_as_pred_in_confusion                   74                   1           3.250000
           95       22   0.090909 0.045455 0.060606         21.0           True                              low_f1<=0.45|low_recall<=0.35|high_error_count>=7|appears_as_true_in_confusion                44,64                   2           3.159091
           75       10   0.076923 0.200000 0.111111          8.0           True low_f1<=0.45|low_recall<=0.35|high_error_count>=7|appears_as_true_in_confusion|appears_as_pred_in_confusion                73,91                   2           3.083333
           52       24   0.666667 0.083333 0.148148         22.0           True                              low_f1<=0.45|low_recall<=0.35|high_error_count>=7|appears_as_true_in_confusion                  104                   1           3.027778
           48        7   0.000000 0.000000 0.000000          7.0           True                                                           low_f1<=0.45|low_recall<=0.35|high_error_count>=7                                        0           3.000000
           71        4   0.000000 0.000000 0.000000          4.0           True                                                                               low_f1<=0.45|low_recall<=0.35                                        0           3.000000
           42        3   0.000000 0.000000 0.000000          3.0           True                                                                               low_f1<=0.45|low_recall<=0.35                                        0           3.000000
           90       13   0.200000 0.153846 0.173913         11.0           True                              low_f1<=0.45|low_recall<=0.35|high_error_count>=7|appears_as_true_in_confusion                   89                   1           2.989130
           47       16   0.400000 0.125000 0.190476         14.0           True                              low_f1<=0.45|low_recall<=0.35|high_error_count>=7|appears_as_true_in_confusion                   46                   1           2.964286
           24       30   0.500000 0.133333 0.210526         26.0           True                              low_f1<=0.45|low_recall<=0.35|high_error_count>=7|appears_as_true_in_confusion                   10                   1           2.934211
           36       31   0.260870 0.193548 0.222222         25.0           True low_f1<=0.45|low_recall<=0.35|high_error_count>=7|appears_as_true_in_confusion|appears_as_pred_in_confusion                51,59                   2           2.916667
          105       10   0.111111 0.100000 0.105263          9.0           True                                                           low_f1<=0.45|low_recall<=0.35|high_error_count>=7                                        0           2.842105
           74       42   0.450000 0.214286 0.290323         33.0           True                              low_f1<=0.45|low_recall<=0.35|high_error_count>=7|appears_as_true_in_confusion             28,40,76                   3           2.814516
           40       18   0.312500 0.277778 0.294118         13.0           True low_f1<=0.45|low_recall<=0.35|high_error_count>=7|appears_as_true_in_confusion|appears_as_pred_in_confusion                39,74                   2           2.808824
            0        0   0.000000 0.000000 0.000000          0.0           True                                                                                appears_as_pred_in_confusion                   89                   1           2.750000
           39        0   0.000000 0.000000 0.000000          0.0           True                                                                                appears_as_pred_in_confusion                   40                   1           2.750000
           44        0   0.000000 0.000000 0.000000          0.0           True                                                                                appears_as_pred_in_confusion                   95                   1           2.750000
           85        0   0.000000 0.000000 0.000000          0.0           True                                                                                appears_as_pred_in_confusion                   99                   1           2.750000
           68       16   0.318182 0.437500 0.368421          9.0           True                  low_f1<=0.45|high_error_count>=7|appears_as_true_in_confusion|appears_as_pred_in_confusion               99,104                   2           2.697368
           70       37   0.428571 0.324324 0.369231         25.0           True low_f1<=0.45|low_recall<=0.35|high_error_count>=7|appears_as_true_in_confusion|appears_as_pred_in_confusion           5,7,59,107                   4           2.696154
           63        6   0.333333 0.166667 0.222222          5.0           True                                                                               low_f1<=0.45|low_recall<=0.35                                        0           2.666667
           73       59   0.403226 0.423729 0.413223         34.0           True                  low_f1<=0.45|high_error_count>=7|appears_as_true_in_confusion|appears_as_pred_in_confusion           7,29,59,75                   4           2.630165
          104       84   0.438202 0.464286 0.450867         45.0           True                               high_error_count>=7|appears_as_true_in_confusion|appears_as_pred_in_confusion       10,18,19,52,68                   5           2.573699
           72       14   0.307692 0.285714 0.296296         10.0           True                                                           low_f1<=0.45|low_recall<=0.35|high_error_count>=7                                        0           2.555556
           15       14   0.500000 0.214286 0.300000         11.0           True                                                           low_f1<=0.45|low_recall<=0.35|high_error_count>=7                                        0           2.550000
           89      180   0.565891 0.405556 0.472492        107.0           True                               high_error_count>=7|appears_as_true_in_confusion|appears_as_pred_in_confusion      0,2,60,90,91,99                   6           2.541262
           99      117   0.504587 0.470085 0.486726         62.0           True                               high_error_count>=7|appears_as_true_in_confusion|appears_as_pred_in_confusion     8,10,68,85,89,91                   6           2.519912
           59       85   0.610169 0.423529 0.500000         49.0           True                               high_error_count>=7|appears_as_true_in_confusion|appears_as_pred_in_confusion        7,36,70,73,80                   5           2.500000
           14       16   0.571429 0.250000 0.347826         12.0           True                                                           low_f1<=0.45|low_recall<=0.35|high_error_count>=7                                        0           2.478261
           50       10   0.428571 0.300000 0.352941          7.0           True                                                           low_f1<=0.45|low_recall<=0.35|high_error_count>=7                                        0           2.470588
          106        6   0.300000 0.500000 0.375000          3.0           True                                                                                                low_f1<=0.45                                        0           2.437500
           87       21   0.380952 0.380952 0.380952         13.0           True                                                                            low_f1<=0.45|high_error_count>=7                                        0           2.428571
            1       21   0.600000 0.285714 0.387097         15.0           True                                                           low_f1<=0.45|low_recall<=0.35|high_error_count>=7                                        0           2.419355
            7       69   0.666667 0.492754 0.566667         35.0           True                               high_error_count>=7|appears_as_true_in_confusion|appears_as_pred_in_confusion          28,59,70,73                   4           2.400000
          103       29   0.562500 0.310345 0.400000         20.0           True                                                           low_f1<=0.45|low_recall<=0.35|high_error_count>=7                                        0           2.400000
           21        3   0.500000 0.333333 0.400000          2.0           True                                                                               low_f1<=0.45|low_recall<=0.35                                        0           2.400000

=== SPLIT SUMMARY ===
split  rows  labels  hard_rows  hard_labels  mean_hard_weight  max_hard_weight
train 23189     108      20809           63          1.786271             3.25
  val  4974      89       4515           60          1.767496             3.25
 test  4550      82       4250           59          1.774714             3.25

Saved files:
/content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_train_hard_metadata.csv
/content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_val_hard_metadata.csv
/content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_test_hard_metadata.csv
/content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_hard_pair_edges.csv
/content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_hard_class_summary.csv
/content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_hard_negative_map.json
/content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_hard_metadata_split_summary.csv
/content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_hard_metadata_config.json

Done.

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh train_m24_metric_visual.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 309, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 309 (delta 27), reused 22 (delta 22), pack-reused 271 (from 2)
Receiving objects: 100% (309/309), 2.66 MiB | 5.72 MiB/s, done.
Resolving deltas: 100% (162/162), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 32K May  7 11:30 train_m24_metric_visual.py

In [ ]:
import os

M24_RUN_DIR = "/content/drive/MyDrive/model/M24_metric_learning/train_run_v1"
os.makedirs(M24_RUN_DIR, exist_ok=True)

print("M24 run output dir:", M24_RUN_DIR)

M24 run output dir: /content/drive/MyDrive/model/M24_metric_learning/train_run_v1

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python train_m24_metric_visual.py \
  --train_metadata /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_train_hard_metadata.csv \
  --val_metadata /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_val_hard_metadata.csv \
  --test_metadata /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_test_hard_metadata.csv \
  --hard_negative_map /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_hard_negative_map.json \
  --idx_to_label /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/idx_to_label.json \
  --output_dir /content/drive/MyDrive/model/M24_metric_learning/train_run_v1 \
  --backbone_name convnext_tiny.in12k_ft_in1k \
  --epochs 20 \
  --classes_per_batch 16 \
  --samples_per_class 2 \
  --eval_batch_size 32 \
  --lr 3e-5 \
  --class_weight_exponent 0.15 \
  --hard_weight_max 1.8 \
  --label_smoothing 0.03 \
  --cosface_margin 0.15 \
  --supcon_weight 0.10 \
  --hardpair_weight 0.05 \
  --freeze_backbone_epochs 1 \
  --patience 5 \
  2>&1 | tee /content/drive/MyDrive/model/M24_metric_learning/train_run_v1/train_log.txt

/content/vaipe-contextual-pill-recognition
=== M24 METRIC VISUAL TRAINING ===
Using device: cuda
Train metadata: /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_train_hard_metadata.csv
Val metadata: /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_val_hard_metadata.csv
Test metadata: /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_test_hard_metadata.csv
Hard negative map: /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_hard_negative_map.json
Output dir: /content/drive/MyDrive/model/M24_metric_learning/train_run_v1
Train pill images existing: 23189 / 23189
Val pill images existing: 4974 / 4974
Num classes: 108
Train rows: 23189
Val rows: 4974
Train labels: 108
Val labels: 89
Labels in train but missing in val: 19
[np.int64(0), np.int64(3), np.int64(4), np.int64(9), np.int64(13), np.int64(16), np.int64(20), np.int64(25), np.int64(32), np.int64(35), np.int64(44), np.int64(49), np.int64(53), np.int64(66), np.int64(85), np.int64(86), np.int64(94), np.int64(96), np.int64(102)]
Created M24MetricVisualModel
Backbone: convnext_tiny.in12k_ft_in1k
Embedding dim: 512
Dropout: 0.35
CosFace scale: 30.0
CosFace margin: 0.15
Batch design: 16 classes x 2 samples
Visual backbone frozen: True
Total params: 28533856
Trainable params: 713728
Class weight exponent: 0.15
Class weight min: 0.5105232000350952
Class weight max: 1.8698502779006958
Hard pair matrix pairs: 52

M24 Metric Visual Epoch [1/20]
Current LR: 0.00003000
Visual backbone frozen: True
Train Loss: 10.1990 | CE: 9.8990 | SupCon: 2.7769 | HardPair: 0.4473 | Train Acc: 0.1614 | Train Macro F1: 0.0522
Val Loss  : 6.6361 | Val Acc  : 0.0478 | Val Macro Precision: 0.0833 | Val Macro Recall: 0.1573 | Val Macro F1 Present: 0.0668 | Val Macro F1 All: 0.0662
Saved best checkpoint: /content/drive/MyDrive/model/M24_metric_learning/train_run_v1/M24_metric_visual_best.pth
Best Val Macro F1 Present: 0.0668

M24 Metric Visual Epoch [2/20]
Current LR: 0.00002982
Visual backbone frozen: False
Rebuilt optimizer after unfreezing.
Train Loss: 5.4945 | CE: 5.3151 | SupCon: 1.6390 | HardPair: 0.3095 | Train Acc: 0.4963 | Train Macro F1: 0.3266
Val Loss  : 5.7786 | Val Acc  : 0.2069 | Val Macro Precision: 0.2479 | Val Macro Recall: 0.3639 | Val Macro F1 Present: 0.2299 | Val Macro F1 All: 0.2235
Saved best checkpoint: /content/drive/MyDrive/model/M24_metric_learning/train_run_v1/M24_metric_visual_best.pth
Best Val Macro F1 Present: 0.2299

M24 Metric Visual Epoch [3/20]
Current LR: 0.00002980
Train Loss: 3.0937 | CE: 2.9906 | SupCon: 0.9288 | HardPair: 0.2044 | Train Acc: 0.7028 | Train Macro F1: 0.5638
Val Loss  : 5.6611 | Val Acc  : 0.2589 | Val Macro Precision: 0.2488 | Val Macro Recall: 0.3771 | Val Macro F1 Present: 0.2532 | Val Macro F1 All: 0.2485
Saved best checkpoint: /content/drive/MyDrive/model/M24_metric_learning/train_run_v1/M24_metric_visual_best.pth
Best Val Macro F1 Present: 0.2532

M24 Metric Visual Epoch [4/20]
Current LR: 0.00002919
Train Loss: 2.2585 | CE: 2.1813 | SupCon: 0.6594 | HardPair: 0.2241 | Train Acc: 0.7907 | Train Macro F1: 0.6697
Val Loss  : 5.5995 | Val Acc  : 0.3040 | Val Macro Precision: 0.2687 | Val Macro Recall: 0.4011 | Val Macro F1 Present: 0.2883 | Val Macro F1 All: 0.2856
Saved best checkpoint: /content/drive/MyDrive/model/M24_metric_learning/train_run_v1/M24_metric_visual_best.pth
Best Val Macro F1 Present: 0.2883

M24 Metric Visual Epoch [5/20]
Current LR: 0.00002819
Train Loss: 1.8208 | CE: 1.7593 | SupCon: 0.5149 | HardPair: 0.1992 | Train Acc: 0.8395 | Train Macro F1: 0.7341
Val Loss  : 5.5058 | Val Acc  : 0.3168 | Val Macro Precision: 0.2663 | Val Macro Recall: 0.3997 | Val Macro F1 Present: 0.2895 | Val Macro F1 All: 0.2868
Saved best checkpoint: /content/drive/MyDrive/model/M24_metric_learning/train_run_v1/M24_metric_visual_best.pth
Best Val Macro F1 Present: 0.2895

M24 Metric Visual Epoch [6/20]
Current LR: 0.00002684
Train Loss: 1.5080 | CE: 1.4585 | SupCon: 0.4048 | HardPair: 0.1809 | Train Acc: 0.8725 | Train Macro F1: 0.7778
Val Loss  : 5.4303 | Val Acc  : 0.3235 | Val Macro Precision: 0.2633 | Val Macro Recall: 0.3843 | Val Macro F1 Present: 0.2823 | Val Macro F1 All: 0.2771
No significant improvement. bad_epochs=1/5

M24 Metric Visual Epoch [7/20]
Current LR: 0.00002516
Train Loss: 1.3207 | CE: 1.2773 | SupCon: 0.3538 | HardPair: 0.1617 | Train Acc: 0.8948 | Train Macro F1: 0.8096
Val Loss  : 5.5884 | Val Acc  : 0.3277 | Val Macro Precision: 0.2714 | Val Macro Recall: 0.3945 | Val Macro F1 Present: 0.2848 | Val Macro F1 All: 0.2795
No significant improvement. bad_epochs=2/5

M24 Metric Visual Epoch [8/20]
Current LR: 0.00002320
Train Loss: 1.1584 | CE: 1.1219 | SupCon: 0.2929 | HardPair: 0.1449 | Train Acc: 0.9134 | Train Macro F1: 0.8310
Val Loss  : 5.5277 | Val Acc  : 0.3325 | Val Macro Precision: 0.2607 | Val Macro Recall: 0.3884 | Val Macro F1 Present: 0.2841 | Val Macro F1 All: 0.2815
No significant improvement. bad_epochs=3/5

M24 Metric Visual Epoch [9/20]
Current LR: 0.00002103
M24 Metric Training:   8%|▊         | 60/725 [00:13<03:36,  3.07it/s]

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh train_m24_metric_visual_v2.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 312, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 312 (delta 29), reused 22 (delta 22), pack-reused 271 (from 2)
Receiving objects: 100% (312/312), 2.66 MiB | 7.63 MiB/s, done.
Resolving deltas: 100% (164/164), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 28K May  7 12:01 train_m24_metric_visual_v2.py

In [ ]:
import os

M24_V2_DIR = "/content/drive/MyDrive/model/M24_metric_learning/train_run_v2_stable"
os.makedirs(M24_V2_DIR, exist_ok=True)

print("M24 v2 output dir:", M24_V2_DIR)

M24 v2 output dir: /content/drive/MyDrive/model/M24_metric_learning/train_run_v2_stable

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python train_m24_metric_visual_v2.py \
  --train_metadata /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_train_hard_metadata.csv \
  --val_metadata /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_val_hard_metadata.csv \
  --test_metadata /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_test_hard_metadata.csv \
  --idx_to_label /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/idx_to_label.json \
  --output_dir /content/drive/MyDrive/model/M24_metric_learning/train_run_v2_stable \
  --backbone_name convnext_tiny.in12k_ft_in1k \
  --epochs 20 \
  --classes_per_batch 16 \
  --samples_per_class 2 \
  --eval_batch_size 32 \
  --lr 3e-5 \
  --class_weight_exponent 0.12 \
  --hard_weight_max 1.3 \
  --label_smoothing 0.05 \
  --dropout_p 0.45 \
  --supcon_weight 0.05 \
  --freeze_backbone_epochs 1 \
  --patience 5 \
  2>&1 | tee /content/drive/MyDrive/model/M24_metric_learning/train_run_v2_stable/train_log.txt

/content/vaipe-contextual-pill-recognition
=== M24 METRIC VISUAL V2 TRAINING ===
Using device: cuda
Train metadata: /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_train_hard_metadata.csv
Val metadata: /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_val_hard_metadata.csv
Test metadata: /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_test_hard_metadata.csv
Output dir: /content/drive/MyDrive/model/M24_metric_learning/train_run_v2_stable
Train pill images existing: 23189 / 23189
Val pill images existing: 4974 / 4974
Num classes: 108
Train rows: 23189
Val rows: 4974
Train labels: 108
Val labels: 89
Labels in train but missing in val: 19
[np.int64(0), np.int64(3), np.int64(4), np.int64(9), np.int64(13), np.int64(16), np.int64(20), np.int64(25), np.int64(32), np.int64(35), np.int64(44), np.int64(49), np.int64(53), np.int64(66), np.int64(85), np.int64(86), np.int64(94), np.int64(96), np.int64(102)]
Created M24MetricVisualV2Model
Backbone: convnext_tiny.in12k_ft_in1k
Embedding dim: 512
Dropout: 0.45
Batch design: 16 classes x 2 samples
Loss: CE + SupCon
No CosFace
No HardPair loss
hard_weight_max: 1.3
Visual backbone frozen: True
Total params: 28533964
Trainable params: 713836
Class weight exponent: 0.12
Class weight min: 0.5861791968345642
Class weight max: 1.6560120582580566

M24 Metric Visual v2 Epoch [1/20]
Current LR: 0.00003000
Visual backbone frozen: True
Train Loss: 4.8103 | CE: 4.6731 | SupCon: 2.7423 | Train Acc: 0.2463 | Train Macro F1: 0.0855
Val Loss  : 4.9993 | Val Acc  : 0.0195 | Val Macro Precision: 0.0384 | Val Macro Recall: 0.0944 | Val Macro F1 Present: 0.0276 | Val Macro F1 All: 0.0258
Saved best checkpoint: /content/drive/MyDrive/model/M24_metric_learning/train_run_v2_stable/M24_metric_visual_v2_best.pth
Best Val Macro F1 Present: 0.0276

M24 Metric Visual v2 Epoch [2/20]
Current LR: 0.00002982
Visual backbone frozen: False
Rebuilt optimizer after unfreezing.
Train Loss: 3.0980 | CE: 3.0138 | SupCon: 1.6831 | Train Acc: 0.5487 | Train Macro F1: 0.3415
Val Loss  : 4.6779 | Val Acc  : 0.1078 | Val Macro Precision: 0.1880 | Val Macro Recall: 0.2576 | Val Macro F1 Present: 0.1496 | Val Macro F1 All: 0.1496
Saved best checkpoint: /content/drive/MyDrive/model/M24_metric_learning/train_run_v2_stable/M24_metric_visual_v2_best.pth
Best Val Macro F1 Present: 0.1496

M24 Metric Visual v2 Epoch [3/20]
Current LR: 0.00002980
Train Loss: 1.9393 | CE: 1.8933 | SupCon: 0.9206 | Train Acc: 0.7478 | Train Macro F1: 0.5814
Val Loss  : 4.2868 | Val Acc  : 0.1769 | Val Macro Precision: 0.2026 | Val Macro Recall: 0.3417 | Val Macro F1 Present: 0.2041 | Val Macro F1 All: 0.1985
Saved best checkpoint: /content/drive/MyDrive/model/M24_metric_learning/train_run_v2_stable/M24_metric_visual_v2_best.pth
Best Val Macro F1 Present: 0.2041

M24 Metric Visual v2 Epoch [4/20]
Current LR: 0.00002919
Train Loss: 1.4446 | CE: 1.4139 | SupCon: 0.6152 | Train Acc: 0.8294 | Train Macro F1: 0.6915
Val Loss  : 4.1027 | Val Acc  : 0.2185 | Val Macro Precision: 0.2397 | Val Macro Recall: 0.3773 | Val Macro F1 Present: 0.2349 | Val Macro F1 All: 0.2284
Saved best checkpoint: /content/drive/MyDrive/model/M24_metric_learning/train_run_v2_stable/M24_metric_visual_v2_best.pth
Best Val Macro F1 Present: 0.2349

M24 Metric Visual v2 Epoch [5/20]
Current LR: 0.00002819
M24 v2 Training:  11%|█▏        | 82/725 [00:20<03:23,  3.15it/s]

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh train_m25_strong_visual_ce_natural.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 317, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 317 (delta 32), reused 22 (delta 22), pack-reused 271 (from 2)
Receiving objects: 100% (317/317), 2.66 MiB | 7.43 MiB/s, done.
Resolving deltas: 100% (167/167), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 27K May  7 12:22 train_m25_strong_visual_ce_natural.py

In [ ]:
import os

M25_RUN_DIR = "/content/drive/MyDrive/model/M25_strong_visual_ce_natural/train_run_v1"
os.makedirs(M25_RUN_DIR, exist_ok=True)

print("M25 output dir:", M25_RUN_DIR)

M25 output dir: /content/drive/MyDrive/model/M25_strong_visual_ce_natural/train_run_v1

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python train_m25_strong_visual_ce_natural.py \
  --train_metadata /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_train_hard_metadata.csv \
  --val_metadata /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_val_hard_metadata.csv \
  --test_metadata /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_test_hard_metadata.csv \
  --idx_to_label /content/drive/MyDrive/model/M17_faithful_pika/graph_artifacts/idx_to_label.json \
  --output_dir /content/drive/MyDrive/model/M25_strong_visual_ce_natural/train_run_v1 \
  --backbone_name tf_efficientnetv2_s.in21k_ft_in1k \
  --epochs 20 \
  --batch_size 24 \
  --eval_batch_size 32 \
  --backbone_lr 1e-5 \
  --head_lr 5e-5 \
  --class_weight_exponent 0.05 \
  --hard_weight_max 1.05 \
  --label_smoothing 0.03 \
  --dropout_p 0.45 \
  --freeze_backbone_epochs 1 \
  --use_ema \
  --ema_decay 0.999 \
  --patience 5 \
  2>&1 | tee /content/drive/MyDrive/model/M25_strong_visual_ce_natural/train_run_v1/train_log.txt

/content/vaipe-contextual-pill-recognition
=== M25 STRONG VISUAL CE NATURAL TRAINING ===
Using device: cuda
Train metadata: /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_train_hard_metadata.csv
Val metadata: /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_val_hard_metadata.csv
Test metadata: /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_test_hard_metadata.csv
Output dir: /content/drive/MyDrive/model/M25_strong_visual_ce_natural/train_run_v1
Train pill images existing: 23189 / 23189
Val pill images existing: 4974 / 4974
Num classes: 108
Train rows: 23189
Val rows: 4974
Train labels: 108
Val labels: 89
Labels in train but missing in val: 19
[np.int64(0), np.int64(3), np.int64(4), np.int64(9), np.int64(13), np.int64(16), np.int64(20), np.int64(25), np.int64(32), np.int64(35), np.int64(44), np.int64(49), np.int64(53), np.int64(66), np.int64(85), np.int64(86), np.int64(94), np.int64(96), np.int64(102)]
Created M25StrongVisualCEModel
Backbone: tf_efficientnetv2_s.in21k_ft_in1k
Hidden dim: 512
Dropout: 0.45
Natural shuffle: True
Mixup alpha: 0.0
EMA enabled: True
hard_weight_max: 1.05
Visual backbone frozen: True
Total params: 21153468
Trainable params: 975980
Class weight exponent: 0.05
Class weight min: 0.8033214807510376
Class weight max: 1.2382827997207642

M25 Strong Visual CE Epoch [1/20]
Current max LR: 0.00005000
Visual backbone frozen: True
Train Loss: 3.2112 | Train Acc: 0.3095 | Train Macro F1: 0.0246
Val Loss  : 2.6898 | Val Acc  : 0.3918 | Val Macro Precision: 0.0957 | Val Macro Recall: 0.0525 | Val Macro F1 Present: 0.0544 | Val Macro F1 All: 0.0448
EMA Val Loss  : 3.2599 | EMA Val Acc  : 0.3092 | EMA Val Macro F1 Present: 0.0178 | EMA Val Macro F1 All: 0.0147
Saved best checkpoint: /content/drive/MyDrive/model/M25_strong_visual_ce_natural/train_run_v1/M25_strong_visual_ce_best.pth
Best Val Macro F1 Present: 0.0544
Best source: model

M25 Strong Visual CE Epoch [2/20]
Current max LR: 0.00004969
Visual backbone frozen: False
Rebuilt optimizer after unfreezing.
Train Loss: 2.5994 | Train Acc: 0.4289 | Train Macro F1: 0.0829
Val Loss  : 2.2718 | Val Acc  : 0.5020 | Val Macro Precision: 0.1958 | Val Macro Recall: 0.1426 | Val Macro F1 Present: 0.1467 | Val Macro F1 All: 0.1209
EMA Val Loss  : 2.5002 | EMA Val Acc  : 0.4399 | EMA Val Macro F1 Present: 0.0932 | EMA Val Macro F1 All: 0.0768
Saved best checkpoint: /content/drive/MyDrive/model/M25_strong_visual_ce_natural/train_run_v1/M25_strong_visual_ce_best.pth
Best Val Macro F1 Present: 0.1467
Best source: model

M25 Strong Visual CE Epoch [3/20]
Current max LR: 0.00004966
Train Loss: 2.2278 | Train Acc: 0.5039 | Train Macro F1: 0.1473
Val Loss  : 2.0596 | Val Acc  : 0.5392 | Val Macro Precision: 0.2394 | Val Macro Recall: 0.1947 | Val Macro F1 Present: 0.1977 | Val Macro F1 All: 0.1648
EMA Val Loss  : 2.2260 | EMA Val Acc  : 0.5113 | EMA Val Macro F1 Present: 0.1622 | EMA Val Macro F1 All: 0.1337
Saved best checkpoint: /content/drive/MyDrive/model/M25_strong_visual_ce_natural/train_run_v1/M25_strong_visual_ce_best.pth
Best Val Macro F1 Present: 0.1977
Best source: model

M25 Strong Visual CE Epoch [4/20]
Current max LR: 0.00004865
Train Loss: 1.9893 | Train Acc: 0.5558 | Train Macro F1: 0.2157
Val Loss  : 1.9142 | Val Acc  : 0.5756 | Val Macro Precision: 0.3193 | Val Macro Recall: 0.2432 | Val Macro F1 Present: 0.2500 | Val Macro F1 All: 0.2083
EMA Val Loss  : 2.0325 | EMA Val Acc  : 0.5489 | EMA Val Macro F1 Present: 0.2064 | EMA Val Macro F1 All: 0.1720
Saved best checkpoint: /content/drive/MyDrive/model/M25_strong_visual_ce_natural/train_run_v1/M25_strong_visual_ce_best.pth
Best Val Macro F1 Present: 0.2500
Best source: model

M25 Strong Visual CE Epoch [5/20]
Current max LR: 0.00004699
Train Loss: 1.8181 | Train Acc: 0.5959 | Train Macro F1: 0.2845
Val Loss  : 1.8238 | Val Acc  : 0.5921 | Val Macro Precision: 0.3993 | Val Macro Recall: 0.2747 | Val Macro F1 Present: 0.2921 | Val Macro F1 All: 0.2434
EMA Val Loss  : 1.9090 | EMA Val Acc  : 0.5754 | EMA Val Macro F1 Present: 0.2515 | EMA Val Macro F1 All: 0.2095
Saved best checkpoint: /content/drive/MyDrive/model/M25_strong_visual_ce_natural/train_run_v1/M25_strong_visual_ce_best.pth
Best Val Macro F1 Present: 0.2921
Best source: model

M25 Strong Visual CE Epoch [6/20]
Current max LR: 0.00004473
Train Loss: 1.6933 | Train Acc: 0.6233 | Train Macro F1: 0.3422
Val Loss  : 1.7774 | Val Acc  : 0.6104 | Val Macro Precision: 0.4055 | Val Macro Recall: 0.2984 | Val Macro F1 Present: 0.3168 | Val Macro F1 All: 0.2757
EMA Val Loss  : 1.8223 | EMA Val Acc  : 0.5983 | EMA Val Macro F1 Present: 0.3064 | EMA Val Macro F1 All: 0.2525
Saved best checkpoint: /content/drive/MyDrive/model/M25_strong_visual_ce_natural/train_run_v1/M25_strong_visual_ce_best.pth
Best Val Macro F1 Present: 0.3168
Best source: model

M25 Strong Visual CE Epoch [7/20]
Current max LR: 0.00004193
Train Loss: 1.5958 | Train Acc: 0.6433 | Train Macro F1: 0.3881
Val Loss  : 1.7140 | Val Acc  : 0.6228 | Val Macro Precision: 0.4611 | Val Macro Recall: 0.3365 | Val Macro F1 Present: 0.3515 | Val Macro F1 All: 0.2994
EMA Val Loss  : 1.7635 | EMA Val Acc  : 0.6128 | EMA Val Macro F1 Present: 0.3322 | EMA Val Macro F1 All: 0.2768
Saved best checkpoint: /content/drive/MyDrive/model/M25_strong_visual_ce_natural/train_run_v1/M25_strong_visual_ce_best.pth
Best Val Macro F1 Present: 0.3515
Best source: model

M25 Strong Visual CE Epoch [8/20]
Current max LR: 0.00003867
Train Loss: 1.5080 | Train Acc: 0.6614 | Train Macro F1: 0.4221
Val Loss  : 1.6929 | Val Acc  : 0.6275 | Val Macro Precision: 0.4430 | Val Macro Recall: 0.3339 | Val Macro F1 Present: 0.3514 | Val Macro F1 All: 0.2993
EMA Val Loss  : 1.7142 | EMA Val Acc  : 0.6273 | EMA Val Macro F1 Present: 0.3471 | EMA Val Macro F1 All: 0.2989
No significant improvement. bad_epochs=1/5

M25 Strong Visual CE Epoch [9/20]
Current max LR: 0.00003504
Train Loss: 1.4428 | Train Acc: 0.6764 | Train Macro F1: 0.4483
Val Loss  : 1.6688 | Val Acc  : 0.6401 | Val Macro Precision: 0.4739 | Val Macro Recall: 0.3469 | Val Macro F1 Present: 0.3662 | Val Macro F1 All: 0.3154
EMA Val Loss  : 1.6862 | EMA Val Acc  : 0.6351 | EMA Val Macro F1 Present: 0.3580 | EMA Val Macro F1 All: 0.3049
Saved best checkpoint: /content/drive/MyDrive/model/M25_strong_visual_ce_natural/train_run_v1/M25_strong_visual_ce_best.pth
Best Val Macro F1 Present: 0.3662
Best source: model

M25 Strong Visual CE Epoch [10/20]
Current max LR: 0.00003114
Train Loss: 1.3831 | Train Acc: 0.6885 | Train Macro F1: 0.4684
Val Loss  : 1.6655 | Val Acc  : 0.6439 | Val Macro Precision: 0.4580 | Val Macro Recall: 0.3637 | Val Macro F1 Present: 0.3789 | Val Macro F1 All: 0.3263
EMA Val Loss  : 1.6682 | EMA Val Acc  : 0.6415 | EMA Val Macro F1 Present: 0.3673 | EMA Val Macro F1 All: 0.3163
Saved best checkpoint: /content/drive/MyDrive/model/M25_strong_visual_ce_natural/train_run_v1/M25_strong_visual_ce_best.pth
Best Val Macro F1 Present: 0.3789
Best source: model

M25 Strong Visual CE Epoch [11/20]
Current max LR: 0.00002706
Train Loss: 1.3406 | Train Acc: 0.7010 | Train Macro F1: 0.4890
Val Loss  : 1.6663 | Val Acc  : 0.6415 | Val Macro Precision: 0.4846 | Val Macro Recall: 0.3685 | Val Macro F1 Present: 0.3855 | Val Macro F1 All: 0.3284
EMA Val Loss  : 1.6602 | EMA Val Acc  : 0.6464 | EMA Val Macro F1 Present: 0.3774 | EMA Val Macro F1 All: 0.3215
Saved best checkpoint: /content/drive/MyDrive/model/M25_strong_visual_ce_natural/train_run_v1/M25_strong_visual_ce_best.pth
Best Val Macro F1 Present: 0.3855
Best source: model

M25 Strong Visual CE Epoch [12/20]
Current max LR: 0.00002294
Train Loss: 1.2984 | Train Acc: 0.7113 | Train Macro F1: 0.5052
Val Loss  : 1.6732 | Val Acc  : 0.6411 | Val Macro Precision: 0.4637 | Val Macro Recall: 0.3646 | Val Macro F1 Present: 0.3819 | Val Macro F1 All: 0.3360
EMA Val Loss  : 1.6586 | EMA Val Acc  : 0.6466 | EMA Val Macro F1 Present: 0.3864 | EMA Val Macro F1 All: 0.3291
Saved best checkpoint: /content/drive/MyDrive/model/M25_strong_visual_ce_natural/train_run_v1/M25_strong_visual_ce_best.pth
Best Val Macro F1 Present: 0.3864
Best source: ema

M25 Strong Visual CE Epoch [13/20]
Current max LR: 0.00001886
Train Loss: 1.2706 | Train Acc: 0.7206 | Train Macro F1: 0.5149
Val Loss  : 1.6686 | Val Acc  : 0.6446 | Val Macro Precision: 0.4851 | Val Macro Recall: 0.3781 | Val Macro F1 Present: 0.3963 | Val Macro F1 All: 0.3450
EMA Val Loss  : 1.6536 | EMA Val Acc  : 0.6514 | EMA Val Macro F1 Present: 0.3938 | EMA Val Macro F1 All: 0.3428
Saved best checkpoint: /content/drive/MyDrive/model/M25_strong_visual_ce_natural/train_run_v1/M25_strong_visual_ce_best.pth
Best Val Macro F1 Present: 0.3963
Best source: model

M25 Strong Visual CE Epoch [14/20]
Current max LR: 0.00001496
Train Loss: 1.2405 | Train Acc: 0.7244 | Train Macro F1: 0.5191
Val Loss  : 1.6646 | Val Acc  : 0.6441 | Val Macro Precision: 0.4819 | Val Macro Recall: 0.3848 | Val Macro F1 Present: 0.3999 | Val Macro F1 All: 0.3444
EMA Val Loss  : 1.6525 | EMA Val Acc  : 0.6508 | EMA Val Macro F1 Present: 0.3937 | EMA Val Macro F1 All: 0.3426
Saved best checkpoint: /content/drive/MyDrive/model/M25_strong_visual_ce_natural/train_run_v1/M25_strong_visual_ce_best.pth
Best Val Macro F1 Present: 0.3999
Best source: model

M25 Strong Visual CE Epoch [15/20]
Current max LR: 0.00001133
Train Loss: 1.2253 | Train Acc: 0.7300 | Train Macro F1: 0.5309
Val Loss  : 1.6457 | Val Acc  : 0.6484 | Val Macro Precision: 0.4734 | Val Macro Recall: 0.3772 | Val Macro F1 Present: 0.3929 | Val Macro F1 All: 0.3420
EMA Val Loss  : 1.6517 | EMA Val Acc  : 0.6494 | EMA Val Macro F1 Present: 0.3947 | EMA Val Macro F1 All: 0.3435
No significant improvement. bad_epochs=1/5

M25 Strong Visual CE Epoch [16/20]
Current max LR: 0.00000807
Train Loss: 1.2056 | Train Acc: 0.7332 | Train Macro F1: 0.5306
Val Loss  : 1.6703 | Val Acc  : 0.6466 | Val Macro Precision: 0.4730 | Val Macro Recall: 0.3750 | Val Macro F1 Present: 0.3915 | Val Macro F1 All: 0.3444
EMA Val Loss  : 1.6507 | EMA Val Acc  : 0.6510 | EMA Val Macro F1 Present: 0.3952 | EMA Val Macro F1 All: 0.3439
No significant improvement. bad_epochs=2/5

M25 Strong Visual CE Epoch [17/20]
Current max LR: 0.00000527
M25 Natural CE Training:  74%|███████▎  | 711/967 [02:58<01:29,  2.85it/s]

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh build_m26_calibrated_context_ensemble.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 320, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 320 (delta 33), reused 22 (delta 22), pack-reused 271 (from 2)
Receiving objects: 100% (320/320), 2.67 MiB | 7.49 MiB/s, done.
Resolving deltas: 100% (168/168), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 16K May  7 13:51 build_m26_calibrated_context_ensemble.py

In [ ]:
import os

M26_DIR = "/content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1"
os.makedirs(M26_DIR, exist_ok=True)

print("M26 output dir:", M26_DIR)

M26 output dir: /content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python build_m26_calibrated_context_ensemble.py \
  --val_m19_m21_dir /content/drive/MyDrive/model/M22_selective_ensemble/val_predictions \
  --test_m19_m21_dir /content/drive/MyDrive/model/M22_selective_ensemble/test_predictions \
  --m22_dir /content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1 \
  --train_metadata /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_train_hard_metadata.csv \
  --output_dir /content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1 \
  --weight_step 0.05 \
  --logit_adjust_alphas="-0.50,-0.25,0.00,0.10,0.20,0.30,0.40,0.50,0.75,1.00" \
  --temperatures="0.75,1.00,1.25,1.50,2.00" \
  2>&1 | tee /content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1/m26_log.txt

/content/vaipe-contextual-pill-recognition
=== M26 CALIBRATED CONTEXT ENSEMBLE ===
Val M19/M21 dir : /content/drive/MyDrive/model/M22_selective_ensemble/val_predictions
Test M19/M21 dir: /content/drive/MyDrive/model/M22_selective_ensemble/test_predictions
M22 dir         : /content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1
Train metadata  : /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_train_hard_metadata.csv
Output dir      : /content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1
Num classes: 108
Val rows: 4974
Test rows: 4550
Train prior min/max: 8.584796325707173e-05 0.24625488260291026

=== BASELINE METRICS ===
split model  accuracy  macro_f1_present  macro_f1_all  weighted_f1
  val   M19  0.749698          0.490893      0.445440     0.748022
  val   M21  0.756534          0.515325      0.472381     0.750121
  val   M22  0.774829          0.550088      0.488967     0.767312
 test   M19  0.746813          0.443011      0.397890     0.744192
 test   M21  0.741319          0.423311      0.391954     0.735270
 test   M22  0.758022          0.462450      0.411067     0.750668
Grid modes: ['prob_average', 'logit_average']
Num weight combinations: 231
Alphas: [-0.5, -0.25, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.75, 1.0]
Temperatures: [0.75, 1.0, 1.25, 1.5, 2.0]

=== TOP 20 VAL CONFIGS ===
         mode  w_m19  w_m21  w_m22  logit_adjust_alpha  temperature  accuracy  macro_f1_present  macro_f1_all  weighted_f1
logit_average   0.35   0.65   0.00               -0.25         0.75  0.782871          0.563060      0.495284     0.771756
logit_average   0.35   0.65   0.00               -0.25         1.00  0.782871          0.563060      0.495284     0.771756
logit_average   0.35   0.65   0.00               -0.25         1.25  0.782871          0.563060      0.495284     0.771756
logit_average   0.35   0.65   0.00               -0.25         1.50  0.782871          0.563060      0.495284     0.771756
logit_average   0.35   0.65   0.00               -0.25         2.00  0.782871          0.563060      0.495284     0.771756
logit_average   0.45   0.55   0.00               -0.50         0.75  0.788701          0.557287      0.485046     0.774674
logit_average   0.45   0.55   0.00               -0.50         1.00  0.788701          0.557287      0.485046     0.774674
logit_average   0.45   0.55   0.00               -0.50         1.25  0.788701          0.557287      0.485046     0.774674
logit_average   0.45   0.55   0.00               -0.50         1.50  0.788701          0.557287      0.485046     0.774674
logit_average   0.45   0.55   0.00               -0.50         2.00  0.788701          0.557287      0.485046     0.774674
logit_average   0.40   0.55   0.05               -0.50         0.75  0.788500          0.556243      0.484137     0.774241
logit_average   0.40   0.55   0.05               -0.50         1.00  0.788500          0.556243      0.484137     0.774241
logit_average   0.40   0.55   0.05               -0.50         1.25  0.788500          0.556243      0.484137     0.774241
logit_average   0.40   0.55   0.05               -0.50         1.50  0.788500          0.556243      0.484137     0.774241
logit_average   0.40   0.55   0.05               -0.50         2.00  0.788500          0.556243      0.484137     0.774241
logit_average   0.40   0.50   0.10               -0.50         0.75  0.788500          0.555976      0.483905     0.773991
logit_average   0.40   0.50   0.10               -0.50         1.00  0.788500          0.555976      0.483905     0.773991
logit_average   0.40   0.50   0.10               -0.50         1.25  0.788500          0.555976      0.483905     0.773991
logit_average   0.40   0.50   0.10               -0.50         1.50  0.788500          0.555976      0.483905     0.773991
logit_average   0.40   0.50   0.10               -0.50         2.00  0.788500          0.555976      0.483905     0.773991

=== SELECTED CONFIG BY VAL ===
mode: logit_average
w_m19: 0.35
w_m21: 0.65
w_m22: 0.0
logit_adjust_alpha: -0.25
temperature: 0.75

=== VAL M26 RESULTS ===
Mode             : logit_average
Weights M19/M21/M22: 0.35 0.65 0.0
Logit alpha      : -0.25
Temperature      : 0.75
Accuracy         : 0.782871
Macro F1 Present : 0.563060
Macro F1 All     : 0.495284
Weighted F1      : 0.771756
Saved:
/content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1/val_m26_predictions.csv
/content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1/val_m26_probs.npy
/content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1/val_m26_metrics.json

=== TEST M26 RESULTS ===
Mode             : logit_average
Weights M19/M21/M22: 0.35 0.65 0.0
Logit alpha      : -0.25
Temperature      : 0.75
Accuracy         : 0.773187
Macro F1 Present : 0.500298
Macro F1 All     : 0.421548
Weighted F1      : 0.762100
Saved:
/content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1/test_m26_predictions.csv
/content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1/test_m26_probs.npy
/content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1/test_m26_metrics.json

Saved summary: /content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1/m26_summary.csv
Saved grid: /content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1/m26_val_grid_results.csv

Done.

In [ ]:
import pandas as pd
from pathlib import Path

m22_path = Path("/content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1/test_ensemble_predictions.csv")
m26_path = Path("/content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1/test_m26_predictions.csv")

print("M22 exists:", m22_path.exists(), m22_path)
print("M26 exists:", m26_path.exists(), m26_path)

m22 = pd.read_csv(m22_path)
m26 = pd.read_csv(m26_path)

m22_small = m22[[
    "pill_crop_path",
    "true_mapped_label",
    "ensemble_pred_mapped_label",
    "ensemble_is_correct"
]].copy()

m22_small = m22_small.rename(columns={
    "ensemble_pred_mapped_label": "m22_pred",
    "ensemble_is_correct": "m22_correct"
})

m26_small = m26[[
    "pill_crop_path",
    "true_mapped_label",
    "m26_pred_mapped_label",
    "m26_is_correct"
]].copy()

m26_small = m26_small.rename(columns={
    "m26_pred_mapped_label": "m26_pred",
    "m26_is_correct": "m26_correct"
})

cmp = m22_small.merge(
    m26_small,
    on=["pill_crop_path", "true_mapped_label"],
    how="inner"
)

cmp["case"] = "unknown"
cmp.loc[cmp["m22_correct"] & cmp["m26_correct"], "case"] = "both_correct"
cmp.loc[cmp["m22_correct"] & ~cmp["m26_correct"], "case"] = "m22_only_correct"
cmp.loc[~cmp["m22_correct"] & cmp["m26_correct"], "case"] = "m26_only_correct"
cmp.loc[~cmp["m22_correct"] & ~cmp["m26_correct"], "case"] = "both_wrong"

case_summary = (
    cmp["case"]
    .value_counts()
    .rename_axis("case")
    .reset_index(name="count")
)

case_summary["ratio"] = case_summary["count"] / len(cmp)

print("\n====================")
print("1. M22 VS M26 CASE SUMMARY")
print("====================")
print(case_summary.to_string(index=False))

per_class_cmp = (
    cmp.groupby("true_mapped_label")
    .agg(
        samples=("pill_crop_path", "count"),
        m22_correct=("m22_correct", "sum"),
        m26_correct=("m26_correct", "sum")
    )
    .reset_index()
    .rename(columns={"true_mapped_label": "label"})
)

per_class_cmp["m22_acc"] = per_class_cmp["m22_correct"] / per_class_cmp["samples"]
per_class_cmp["m26_acc"] = per_class_cmp["m26_correct"] / per_class_cmp["samples"]
per_class_cmp["m26_minus_m22"] = per_class_cmp["m26_acc"] - per_class_cmp["m22_acc"]

print("\n====================")
print("2. CLASSES WHERE M26 IMPROVES OVER M22")
print("====================")
print(
    per_class_cmp
    .sort_values(["m26_minus_m22", "samples"], ascending=[False, False])
    .head(30)
    .to_string(index=False)
)

print("\n====================")
print("3. CLASSES WHERE M26 IS WORSE THAN M22")
print("====================")
print(
    per_class_cmp
    .sort_values(["m26_minus_m22", "samples"], ascending=[True, False])
    .head(30)
    .to_string(index=False)
)

# Confusion pairs của M26
wrong = m26[m26["true_mapped_label"] != m26["m26_pred_mapped_label"]].copy()

conf_pairs = (
    wrong.groupby(["true_mapped_label", "m26_pred_mapped_label"])
    .size()
    .reset_index(name="wrong_count")
    .sort_values("wrong_count", ascending=False)
)

true_support = m26["true_mapped_label"].value_counts().rename("true_support")
pred_support = m26["m26_pred_mapped_label"].value_counts().rename("pred_support")

conf_pairs = conf_pairs.merge(
    true_support,
    left_on="true_mapped_label",
    right_index=True,
    how="left"
)

conf_pairs = conf_pairs.merge(
    pred_support,
    left_on="m26_pred_mapped_label",
    right_index=True,
    how="left"
)

print("\n====================")
print("4. M26 TOP CONFUSION PAIRS")
print("====================")
print(conf_pairs.head(30).to_string(index=False))

out_dir = Path("/content/drive/MyDrive/model/M26_calibrated_context_ensemble/diagnosis_vs_m22")
out_dir.mkdir(parents=True, exist_ok=True)

cmp.to_csv(out_dir / "m22_vs_m26_row_level.csv", index=False)
case_summary.to_csv(out_dir / "m22_vs_m26_case_summary.csv", index=False)
per_class_cmp.to_csv(out_dir / "m22_vs_m26_per_class_compare.csv", index=False)
conf_pairs.to_csv(out_dir / "m26_confusion_pairs.csv", index=False)

print("\nSaved:")
print(out_dir / "m22_vs_m26_row_level.csv")
print(out_dir / "m22_vs_m26_case_summary.csv")
print(out_dir / "m22_vs_m26_per_class_compare.csv")
print(out_dir / "m26_confusion_pairs.csv")

M22 exists: True /content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1/test_ensemble_predictions.csv
M26 exists: True /content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1/test_m26_predictions.csv

====================
1. M22 VS M26 CASE SUMMARY
====================
            case  count    ratio
    both_correct   3418 0.751209
      both_wrong   1001 0.220000
m26_only_correct    100 0.021978
m22_only_correct     31 0.006813

====================
2. CLASSES WHERE M26 IMPROVES OVER M22
====================
 label  samples  m22_correct  m26_correct  m22_acc  m26_acc  m26_minus_m22
    75       10            2            4 0.200000 0.400000       0.200000
    63        6            1            2 0.166667 0.333333       0.166667
    67       15           11           13 0.733333 0.866667       0.133333
    62        9            8            9 0.888889 1.000000       0.111111
    12        9            7            8 0.777778 0.888889       0.111111
    70       37           12           15 0.324324 0.405405       0.081081
    41       13            5            6 0.384615 0.461538       0.076923
    45       15           13           14 0.866667 0.933333       0.066667
    91      198          158          168 0.797980 0.848485       0.050505
    61       84           69           73 0.821429 0.869048       0.047619
     1       21            6            7 0.285714 0.333333       0.047619
   104       84           39           43 0.464286 0.511905       0.047619
    46       76           65           68 0.855263 0.894737       0.039474
    89      180           73           80 0.405556 0.444444       0.038889
    43      160          137          143 0.856250 0.893750       0.037500
     8       80           49           52 0.612500 0.650000       0.037500
    92       28           24           25 0.857143 0.892857       0.035714
    30       29           25           26 0.862069 0.896552       0.034483
    24       30            4            5 0.133333 0.166667       0.033333
    99      117           55           58 0.470085 0.495726       0.025641
    10      248          202          208 0.814516 0.838710       0.024194
    64      375          349          356 0.930667 0.949333       0.018667
     7       69           34           35 0.492754 0.507246       0.014493
    19       72           49           50 0.680556 0.694444       0.013889
    51      147          128          130 0.870748 0.884354       0.013605
    26       89           75           76 0.842697 0.853933       0.011236
   107     1296         1278         1287 0.986111 0.993056       0.006944
    59       85           36           36 0.423529 0.423529       0.000000
    54       60           59           59 0.983333 0.983333       0.000000
    73       59           25           25 0.423729 0.423729       0.000000

====================
3. CLASSES WHERE M26 IS WORSE THAN M22
====================
 label  samples  m22_correct  m26_correct  m22_acc  m26_acc  m26_minus_m22
    21        3            1            0 0.333333 0.000000      -0.333333
   100        4            3            2 0.750000 0.500000      -0.250000
    50       10            3            1 0.300000 0.100000      -0.200000
   106        6            3            2 0.500000 0.333333      -0.166667
    72       14            4            2 0.285714 0.142857      -0.142857
    84       30           25           23 0.833333 0.766667      -0.066667
    47       16            2            1 0.125000 0.062500      -0.062500
    27       25           16           15 0.640000 0.600000      -0.040000
   103       29            9            8 0.310345 0.275862      -0.034483
    74       42            9            8 0.214286 0.190476      -0.023810
     2       81           55           54 0.679012 0.666667      -0.012346
    59       85           36           36 0.423529 0.423529       0.000000
    54       60           59           59 0.983333 0.983333       0.000000
    73       59           25           25 0.423729 0.423729       0.000000
    29       35           21           21 0.600000 0.600000       0.000000
    37       33           24           24 0.727273 0.727273       0.000000
    36       31            6            6 0.193548 0.193548       0.000000
    97       26           25           25 0.961538 0.961538       0.000000
    34       24           24           24 1.000000 1.000000       0.000000
    52       24            2            2 0.083333 0.083333       0.000000
    56       24           19           19 0.791667 0.791667       0.000000
    95       22            1            1 0.045455 0.045455       0.000000
    87       21            8            8 0.380952 0.380952       0.000000
    55       20           10           10 0.500000 0.500000       0.000000
    38       19           11           11 0.578947 0.578947       0.000000
    60       19           17           17 0.894737 0.894737       0.000000
    79       19           15           15 0.789474 0.789474       0.000000
    40       18            5            5 0.277778 0.277778       0.000000
    65       18           18           18 1.000000 1.000000       0.000000
    14       16            4            4 0.250000 0.250000       0.000000

====================
4. M26 TOP CONFUSION PAIRS
====================
 true_mapped_label  m26_pred_mapped_label  wrong_count  true_support  pred_support
                89                      0           26           180            28
                36                     51           23            31           180
                52                    104           21            24           100
                59                     73           20            85            59
                24                     10           20            30           261
                89                     99           18           180           113
                73                     75           16            59            26
                89                     60           15           180            38
                99                     85           10           117            25
               104                     19            9            84            65
                18                    104            9            10           100
                99                     10            8           117           261
                74                     76            8            42             8
                80                     59            8            16            62
                 7                     28            7            69            24
                 7                     73            7            69            59
                95                     64            7            22           415
                47                     46            7            16            91
                 2                     91            7            81           216
                26                     43            7            89           181
                89                    104            7           180           100
                27                     89            6            25           133
                26                    107            6            89          1370
                70                     59            6            37            62
                 2                     89            6            81           133
                70                    107            6            37          1370
                40                     39            6            18            10
                91                     99            6           198           113
                95                     44            6            22             8
                90                     89            6            13           133

Saved:
/content/drive/MyDrive/model/M26_calibrated_context_ensemble/diagnosis_vs_m22/m22_vs_m26_row_level.csv
/content/drive/MyDrive/model/M26_calibrated_context_ensemble/diagnosis_vs_m22/m22_vs_m26_case_summary.csv
/content/drive/MyDrive/model/M26_calibrated_context_ensemble/diagnosis_vs_m22/m22_vs_m26_per_class_compare.csv
/content/drive/MyDrive/model/M26_calibrated_context_ensemble/diagnosis_vs_m22/m26_confusion_pairs.csv

In [ ]:
%cd /content
!rm -rf vaipe-contextual-pill-recognition
!git clone https://github.com/2274802010922/vaipe-contextual-pill-recognition.git
%cd /content/vaipe-contextual-pill-recognition

!ls -lh build_m27_classwise_fallback_ensemble.py

/content
Cloning into 'vaipe-contextual-pill-recognition'...
remote: Enumerating objects: 323, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 323 (delta 34), reused 22 (delta 22), pack-reused 271 (from 2)
Receiving objects: 100% (323/323), 2.67 MiB | 7.28 MiB/s, done.
Resolving deltas: 100% (169/169), done.
/content/vaipe-contextual-pill-recognition
-rw-r--r-- 1 root root 17K May  7 14:13 build_m27_classwise_fallback_ensemble.py

In [ ]:
import os

M27_DIR = "/content/drive/MyDrive/model/M27_classwise_fallback_ensemble/run_v1"
os.makedirs(M27_DIR, exist_ok=True)

print("M27 output dir:", M27_DIR)

M27 output dir: /content/drive/MyDrive/model/M27_classwise_fallback_ensemble/run_v1

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python build_m27_classwise_fallback_ensemble.py \
  --m22_dir /content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1 \
  --m26_dir /content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1 \
  --output_dir /content/drive/MyDrive/model/M27_classwise_fallback_ensemble/run_v1 \
  2>&1 | tee /content/drive/MyDrive/model/M27_classwise_fallback_ensemble/run_v1/m27_log.txt

/content/vaipe-contextual-pill-recognition
=== M27 CLASS-WISE FALLBACK ENSEMBLE ===
M22 dir: /content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1
M26 dir: /content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1
Output dir: /content/drive/MyDrive/model/M27_classwise_fallback_ensemble/run_v1
Num classes: 108
Val rows: 4974
Test rows: 4550

=== BASE METRICS ===
split model  accuracy  macro_f1_present  macro_f1_all  weighted_f1
  val   M22  0.774829          0.550088      0.488967     0.767312
  val   M26  0.782871          0.563060      0.495284     0.771756
 test   M22  0.758022          0.462450      0.411067     0.750668
 test   M26  0.773187          0.500298      0.421548     0.762100

=== LOW M26 PREDICTED-CLASS RELIABILITY TOP 30 ===
 pred_class  m22_pred_support  m22_pred_precision  m26_pred_support  m26_pred_precision
         44                14            0.000000                13            0.000000
         85                12            0.000000                11            0.000000
          0                 9            0.000000                 8            0.000000
         39                 5            0.000000                 6            0.000000
         47                10            0.000000                 6            0.000000
         62                 6            0.000000                 6            0.000000
         78                 7            0.000000                 6            0.000000
         18                 8            0.000000                 5            0.000000
         86                 5            0.000000                 5            0.000000
        105                 8            0.000000                 5            0.000000
          4                 4            0.000000                 2            0.000000
         53                 2            0.000000                 2            0.000000
         80                 1            0.000000                 2            0.000000
         95                 7            0.000000                 2            0.000000
         67                 2            0.000000                 1            0.000000
         87                11            0.181818                 5            0.200000
         14                21            0.142857                17            0.235294
         73                49            0.367347                49            0.346939
         29                43            0.325581                40            0.350000
         63                10            0.300000                 8            0.375000
         90                15            0.466667                10            0.400000
         68                12            0.500000                12            0.416667
         36                27            0.444444                27            0.444444
         45                13            0.384615                11            0.454545
         57                10            0.500000                11            0.454545
         75                24            0.416667                24            0.458333
         70                46            0.500000                50            0.500000
         41                18            0.555556                19            0.526316
          8                93            0.548387                96            0.531250
          7                39            0.564103                43            0.534884

=== TOP 20 M27 VAL CONFIGS ===
 min_pred_support  m26_bad_precision_threshold  m22_good_precision_threshold  precision_margin  m22_conf_threshold  conf_margin  num_switched  accuracy  macro_f1_present  macro_f1_all  weighted_f1
               10                          0.5                           0.3               0.2                 0.5         -0.2             4  0.783273          0.564228      0.496312     0.772078
               10                          0.5                           0.4               0.2                 0.5         -0.2             4  0.783273          0.564228      0.496312     0.772078
               10                          0.5                           0.5               0.2                 0.5         -0.2             4  0.783273          0.564228      0.496312     0.772078
               10                          0.5                           0.6               0.2                 0.5         -0.2             4  0.783273          0.564228      0.496312     0.772078
               10                          0.6                           0.3               0.2                 0.5         -0.2             4  0.783273          0.564228      0.496312     0.772078
               10                          0.6                           0.4               0.2                 0.5         -0.2             4  0.783273          0.564228      0.496312     0.772078
               10                          0.6                           0.5               0.2                 0.5         -0.2             4  0.783273          0.564228      0.496312     0.772078
               10                          0.6                           0.6               0.2                 0.5         -0.2             4  0.783273          0.564228      0.496312     0.772078
               10                          0.6                           0.3               0.2                 0.0          0.0             5  0.783072          0.564216      0.496301     0.771832
               10                          0.6                           0.3               0.2                 0.2          0.0             5  0.783072          0.564216      0.496301     0.771832
               10                          0.6                           0.4               0.2                 0.0          0.0             5  0.783072          0.564216      0.496301     0.771832
               10                          0.6                           0.4               0.2                 0.2          0.0             5  0.783072          0.564216      0.496301     0.771832
               10                          0.6                           0.5               0.2                 0.0          0.0             5  0.783072          0.564216      0.496301     0.771832
               10                          0.6                           0.5               0.2                 0.2          0.0             5  0.783072          0.564216      0.496301     0.771832
               10                          0.6                           0.6               0.2                 0.0          0.0             5  0.783072          0.564216      0.496301     0.771832
               10                          0.6                           0.6               0.2                 0.2          0.0             5  0.783072          0.564216      0.496301     0.771832
               10                          0.6                           0.3               0.2                 0.3          0.0             4  0.783072          0.564170      0.496261     0.771889
               10                          0.6                           0.3               0.2                 0.4          0.0             4  0.783072          0.564170      0.496261     0.771889
               10                          0.6                           0.4               0.2                 0.3          0.0             4  0.783072          0.564170      0.496261     0.771889
               10                          0.6                           0.4               0.2                 0.4          0.0             4  0.783072          0.564170      0.496261     0.771889

=== SELECTED M27 CONFIG BY VAL ===
min_pred_support: 10
m26_bad_precision_threshold: 0.5
m22_good_precision_threshold: 0.3
precision_margin: 0.2
m22_conf_threshold: 0.5
conf_margin: -0.2

=== VAL M27 RESULTS ===
Switched to M22   : 4
Accuracy          : 0.783273
Macro F1 Present  : 0.564228
Macro F1 All      : 0.496312
Weighted F1       : 0.772078
Saved:
/content/drive/MyDrive/model/M27_classwise_fallback_ensemble/run_v1/val_m27_predictions.csv
/content/drive/MyDrive/model/M27_classwise_fallback_ensemble/run_v1/val_m27_probs.npy
/content/drive/MyDrive/model/M27_classwise_fallback_ensemble/run_v1/val_m27_metrics.json

=== TEST M27 RESULTS ===
Switched to M22   : 2
Accuracy          : 0.773187
Macro F1 Present  : 0.500149
Macro F1 All      : 0.421422
Weighted F1       : 0.762017
Saved:
/content/drive/MyDrive/model/M27_classwise_fallback_ensemble/run_v1/test_m27_predictions.csv
/content/drive/MyDrive/model/M27_classwise_fallback_ensemble/run_v1/test_m27_probs.npy
/content/drive/MyDrive/model/M27_classwise_fallback_ensemble/run_v1/test_m27_metrics.json

Saved summary: /content/drive/MyDrive/model/M27_classwise_fallback_ensemble/run_v1/m27_summary.csv
Saved grid: /content/drive/MyDrive/model/M27_classwise_fallback_ensemble/run_v1/m27_val_grid_results.csv

Done.

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python analyze_m28_m22_m26_complementarity.py \
  --m22_dir /content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1 \
  --m26_dir /content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1 \
  --output_dir /content/drive/MyDrive/model/M28_error_driven_soft_ensemble/run_v1 \
  --num_classes 108 \
  --true_col true_mapped_label

/content/vaipe-contextual-pill-recognition
=== M28 ERROR-DRIVEN CALIBRATED SOFT ENSEMBLE ===
M22 dir    : /content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1
M26 dir    : /content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1
Output dir : /content/drive/MyDrive/model/M28_error_driven_soft_ensemble/run_v1
Num classes: 108

=== INPUT FILES ===
{
  "val": {
    "m22_csv": "/content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1/val_ensemble_predictions.csv",
    "m26_csv": "/content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1/val_m26_predictions.csv",
    "m22_probs": "/content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1/val_ensemble_probs.npy",
    "m26_probs": "/content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1/val_m26_probs.npy"
  },
  "test": {
    "m22_csv": "/content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1/test_ensemble_predictions.csv",
    "m26_csv": "/content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1/test_m26_predictions.csv",
    "m22_probs": "/content/drive/MyDrive/model/M22_selective_ensemble/ensemble_run_v1/test_ensemble_probs.npy",
    "m26_probs": "/content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1/test_m26_probs.npy"
  }
}

=== BASE METRICS ===
split model  accuracy  macro_f1_present  macro_f1_all  weighted_f1
  val   M22  0.774829          0.593354      0.488967     0.767312
  val   M26  0.782871          0.601019      0.495284     0.771756
 test   M22  0.758022          0.541405      0.411067     0.750668
 test   M26  0.773187          0.555209      0.421548     0.762100

=== VAL M22/M26 COMPLEMENTARITY ===
                 case  count    ratio
         both_correct   3804 0.764777
m22_correct_m26_wrong     50 0.010052
m26_correct_m22_wrong     90 0.018094
           both_wrong   1030 0.207077
Oracle upper bound if we could choose the correct model per row, diagnostic only:
{
  "oracle_accuracy": 0.7929232006433454,
  "oracle_macro_f1_present": 0.6197867843781291,
  "oracle_macro_f1_all": 0.5107502204597545,
  "oracle_weighted_f1": 0.7824747446295144
}

=== TEST M22/M26 COMPLEMENTARITY ===
                 case  count    ratio
         both_correct   3418 0.751209
m22_correct_m26_wrong     31 0.006813
m26_correct_m22_wrong    100 0.021978
           both_wrong   1001 0.220000
Oracle upper bound if we could choose the correct model per row, diagnostic only:
{
  "oracle_accuracy": 0.78,
  "oracle_macro_f1_present": 0.577485822821292,
  "oracle_macro_f1_all": 0.438461458068018,
  "oracle_weighted_f1": 0.7700917015389965
}

Searching M28 configs on validation only...

=== TOP 20 M28 VAL CONFIGS ===
             mode  weight_m26  temp_m22  temp_m26  rel_power  smoothing  min_support  rel_floor  conf_gate  margin_gate  accuracy  macro_f1_present  macro_f1_all  weighted_f1
reliability_blend        0.85      1.20      0.85       0.75        3.0            1       0.03       -1.0         -1.0  0.786289          0.604109      0.497831     0.773099
reliability_blend        0.85      1.20      0.85       0.75        3.0            1       0.05       -1.0         -1.0  0.786289          0.604109      0.497831     0.773099
reliability_blend        0.85      1.20      0.85       0.75        3.0            1       0.10       -1.0         -1.0  0.786289          0.604109      0.497831     0.773099
reliability_blend        0.90      1.20      1.00       1.00        5.0            1       0.03       -1.0         -1.0  0.786088          0.603640      0.497444     0.772591
reliability_blend        0.90      1.20      1.00       1.00        5.0            1       0.05       -1.0         -1.0  0.786088          0.603640      0.497444     0.772591
reliability_blend        0.90      1.20      1.00       1.00        5.0            1       0.10       -1.0         -1.0  0.786088          0.603640      0.497444     0.772591
reliability_blend        0.95      1.00      1.00       1.00        5.0            1       0.03       -1.0         -1.0  0.786289          0.603560      0.497379     0.772925
reliability_blend        0.95      1.00      1.00       1.00        5.0            1       0.05       -1.0         -1.0  0.786289          0.603560      0.497379     0.772925
reliability_blend        0.95      1.00      1.00       1.00        5.0            1       0.10       -1.0         -1.0  0.786289          0.603560      0.497379     0.772925
reliability_blend        0.95      0.85      1.00       1.00        5.0            1       0.03       -1.0         -1.0  0.786088          0.603466      0.497300     0.772704
reliability_blend        0.95      0.85      1.00       1.00        5.0            1       0.05       -1.0         -1.0  0.786088          0.603466      0.497300     0.772704
reliability_blend        0.95      0.85      1.00       1.00        5.0            1       0.10       -1.0         -1.0  0.786088          0.603466      0.497300     0.772704
reliability_blend        0.95      1.20      1.20       1.00        3.0            1       0.03       -1.0         -1.0  0.788299          0.603444      0.497282     0.773490
reliability_blend        0.95      1.20      1.20       1.00        3.0            1       0.05       -1.0         -1.0  0.788299          0.603444      0.497282     0.773490
reliability_blend        0.95      1.20      1.20       1.00        3.0            1       0.10       -1.0         -1.0  0.788299          0.603444      0.497282     0.773490
reliability_blend        0.85      1.20      0.85       0.75        3.0            3       0.03       -1.0         -1.0  0.785485          0.603371      0.497223     0.772750
reliability_blend        0.85      1.20      0.85       0.75        3.0            3       0.05       -1.0         -1.0  0.785485          0.603371      0.497223     0.772750
reliability_blend        0.85      1.20      0.85       0.75        3.0            3       0.10       -1.0         -1.0  0.785485          0.603371      0.497223     0.772750
reliability_blend        0.95      1.20      1.20       0.75        3.0            1       0.03       -1.0         -1.0  0.787093          0.603361      0.497215     0.773352
reliability_blend        0.95      1.20      1.20       0.75        3.0            1       0.05       -1.0         -1.0  0.787093          0.603361      0.497215     0.773352

=== SELECTED M28 CONFIG BY VALIDATION ===
{
  "mode": "reliability_blend",
  "score_key": "macro_f1_present",
  "weight_m26": 0.85,
  "temp_m22": 1.2,
  "temp_m26": 0.85,
  "rel_power": 0.75,
  "smoothing": 3.0,
  "min_support": 1,
  "rel_floor": 0.03,
  "conf_gate": -1.0,
  "margin_gate": -1.0
}

=== M28 FINAL RESULTS ===
split model  accuracy  macro_f1_present  macro_f1_all  weighted_f1
  val   M28  0.786289          0.604109      0.497831     0.773099
 test   M28  0.774505          0.553474      0.420230     0.761652

=== VAL M28 CHANGE DIAGNOSTICS VS M26 ===
{
  "changed_from_m26": 59,
  "changed_ratio": 0.011861680739847206,
  "changed_helped": 21,
  "changed_hurt": 4,
  "changed_neutral": 34
}

=== TEST M28 CHANGE DIAGNOSTICS VS M26 ===
{
  "changed_from_m26": 58,
  "changed_ratio": 0.012747252747252748,
  "changed_helped": 13,
  "changed_hurt": 7,
  "changed_neutral": 38
}

Saved files:
/content/drive/MyDrive/model/M28_error_driven_soft_ensemble/run_v1/m28_base_metrics.csv
/content/drive/MyDrive/model/M28_error_driven_soft_ensemble/run_v1/m28_val_grid_results.csv
/content/drive/MyDrive/model/M28_error_driven_soft_ensemble/run_v1/m28_best_config.json
/content/drive/MyDrive/model/M28_error_driven_soft_ensemble/run_v1/val_m28_predictions.csv
/content/drive/MyDrive/model/M28_error_driven_soft_ensemble/run_v1/val_m28_probs.npy
/content/drive/MyDrive/model/M28_error_driven_soft_ensemble/run_v1/val_m28_metrics.json
/content/drive/MyDrive/model/M28_error_driven_soft_ensemble/run_v1/test_m28_predictions.csv
/content/drive/MyDrive/model/M28_error_driven_soft_ensemble/run_v1/test_m28_probs.npy
/content/drive/MyDrive/model/M28_error_driven_soft_ensemble/run_v1/test_m28_metrics.json
/content/drive/MyDrive/model/M28_error_driven_soft_ensemble/run_v1/m28_summary.csv

Done.

In [ ]:
%cd /content/vaipe-contextual-pill-recognition

!python run_m29_classwise_logit_bias_calibration.py \
  --m26_dir /content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1 \
  --output_dir /content/drive/MyDrive/model/M29_classwise_logit_bias_calibration/run_v1 \
  --num_classes 108 \
  --true_col true_mapped_label

/content/vaipe-contextual-pill-recognition
=== M29 CLASS-WISE LOGIT BIAS CALIBRATION ===
M26 dir    : /content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1
Output dir : /content/drive/MyDrive/model/M29_classwise_logit_bias_calibration/run_v1
Num classes: 108
Selection metric: macro_f1_present
Max accuracy drop allowed before penalty: 0.005

=== INPUT FILES ===
{
  "val": {
    "csv": "/content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1/val_m26_predictions.csv",
    "probs": "/content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1/val_m26_probs.npy",
    "true_col": "true_mapped_label"
  },
  "test": {
    "csv": "/content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1/test_m26_predictions.csv",
    "probs": "/content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1/test_m26_probs.npy",
    "true_col": "true_mapped_label"
  }
}

=== BASE M26 METRICS ===
split model  accuracy  macro_f1_present  macro_f1_all  weighted_f1
  val   M26  0.782871          0.601019      0.495284     0.771756
 test   M26  0.773187          0.555209      0.421548     0.762100

=== LOWEST 25 M26 VAL CLASS F1 ===
 class_id  support  pred_support  precision  recall  f1  mean_true_prob  mean_true_rank
       95       21             2        0.0     0.0 0.0        0.001525       14.190476
       23       20             0        0.0     0.0 0.0        0.000544       69.350000
       47       17             6        0.0     0.0 0.0        0.018036       10.000000
       62       16             6        0.0     0.0 0.0        0.007163       13.812500
       67       12             1        0.0     0.0 0.0        0.001519       15.916667
       80       12             2        0.0     0.0 0.0        0.002214        9.666667
      105       10             5        0.0     0.0 0.0        0.003752       39.200000
       18        8             5        0.0     0.0 0.0        0.000016        8.125000
       78        7             6        0.0     0.0 0.0        0.000445       56.000000
       39        6             6        0.0     0.0 0.0        0.028137        9.166667
       42        5             0        0.0     0.0 0.0        0.004533       11.200000
       77        2             0        0.0     0.0 0.0        0.000076        4.500000
        0        0             8        0.0     0.0 0.0        0.000000        0.000000
        3        0             0        0.0     0.0 0.0        0.000000        0.000000
        4        0             2        0.0     0.0 0.0        0.000000        0.000000
        9        0             0        0.0     0.0 0.0        0.000000        0.000000
       13        0             0        0.0     0.0 0.0        0.000000        0.000000
       16        0             0        0.0     0.0 0.0        0.000000        0.000000
       20        0             0        0.0     0.0 0.0        0.000000        0.000000
       25        0             0        0.0     0.0 0.0        0.000000        0.000000
       32        0             0        0.0     0.0 0.0        0.000000        0.000000
       35        0             0        0.0     0.0 0.0        0.000000        0.000000
       44        0            13        0.0     0.0 0.0        0.000000        0.000000
       49        0             0        0.0     0.0 0.0        0.000000        0.000000
       53        0             2        0.0     0.0 0.0        0.000000        0.000000

Searching M29 calibration configs on validation only...

In [7]:
%cd /content/vaipe-contextual-pill-recognition

!python train_m30_hard_error_finetune.py \
  --train_metadata /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_train_hard_metadata.csv \
  --val_metadata /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_val_hard_metadata.csv \
  --test_metadata /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_test_hard_metadata.csv \
  --m26_dir /content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1 \
  --output_dir /content/drive/MyDrive/model/M30_hard_error_finetune/run_v1 \
  --num_classes 108 \
  --true_col mapped_label \
  --epochs 5 \
  --batch_size 32

/content/vaipe-contextual-pill-recognition
=== M30 HARD-ERROR CLASS-BALANCED FINETUNE ===
Train metadata: /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_train_hard_metadata.csv
Val metadata  : /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_val_hard_metadata.csv
Test metadata : /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_test_hard_metadata.csv
M26 dir       : /content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1
Output dir    : /content/drive/MyDrive/model/M30_hard_error_finetune/run_v1
Num classes   : 108
Pill backbone : tf_efficientnetv2_s.in21k_ft_in1k
Rx backbone   : resnet18.a1_in1k
Using device  : cuda | AMP: True

=== DETECTED COLUMNS ===
{
  "train_label_col": "mapped_label",
  "val_label_col": "mapped_label",
  "test_label_col": "mapped_label",
  "pill_col": "pill_crop_path",
  "prescription_col": "prescription_image_path",
  "context_col": "context_labels"
}

=== ROW COUNTS ===
Train rows: 23189
Val rows  : 4974
Test rows : 4550
Train pill images: existing in first 2000 rows = 2000/2000
Train prescription images: existing in first 2000 rows = 2000/2000

=== BASE M26 METRICS ===
split model  accuracy  macro_f1_present  macro_f1_all  weighted_f1
  val   M26  0.782871          0.601019      0.495284     0.771756
 test   M26  0.773187          0.555209      0.421548     0.762100

=== TOP 30 M30 HARD/RARE CLASS WEIGHTS ===
 class_id  train_support  m26_val_support  m26_val_recall  m26_val_f1  freq_weight  hard_weight  final_weight
       77              6                2        0.000000    0.000000     3.037840     4.000000      6.000000
       25              1                0        0.000000    0.000000     7.151259     1.000000      4.162289
       49              1                0        0.000000    0.000000     7.151259     1.000000      4.162289
       42             20                5        0.000000    0.000000     1.754349     4.000000      4.084376
       39             24                6        0.000000    0.000000     1.618920     4.000000      3.769078
       78             37                7        0.000000    0.000000     1.342780     4.000000      3.126184
       13              2                0        0.000000    0.000000     5.115282     1.000000      2.977278
      105             45               10        0.000000    0.000000     1.236232     4.000000      2.878127
       62             63               16        0.000000    0.000000     1.075776     4.000000      2.504562
       80             64               12        0.000000    0.000000     1.068907     4.000000      2.488570
       23             70               20        0.000000    0.000000     1.030834     4.000000      2.399930
       47             73               17        0.000000    0.000000     1.013583     4.000000      2.359767
       18             84                8        0.000000    0.000000     0.958445     4.000000      2.231396
       67             90               12        0.000000    0.000000     0.932727     4.000000      2.171522
       32              4                0        0.000000    0.000000     3.675629     1.000000      2.139348
       95             99               21        0.000000    0.000000     0.898628     4.000000      2.092135
       88              6                1        1.000000    1.000000     3.037840     1.000000      1.768132
       66              8                0        0.000000    0.000000     2.657641     1.000000      1.546843
      102              8                0        0.000000    0.000000     2.657641     1.000000      1.546843
       76             12                4        1.000000    1.000000     2.206656     1.000000      1.284353
       87            121               26        0.038462    0.064516     0.831933     2.631336      1.274132
       21             13                3        0.333333    0.500000     2.127932     1.000000      1.238533
       86             16                0        0.000000    0.000000     1.937815     1.000000      1.127878
       58             18                9        1.000000    1.000000     1.838427     1.000000      1.070031
       22             20                7        1.000000    1.000000     1.754349     1.000000      1.021094
       53             21                0        0.000000    0.000000     1.716889     1.000000      0.999291
       11             22                8        0.625000    0.769231     1.682013     1.000000      0.978992
      100             22                6        0.500000    0.666667     1.682013     1.000000      0.978992
       14             87               18        0.222222    0.228571     0.945253     1.693878      0.931923
      101             25                8        0.500000    0.666667     1.590252     1.000000      0.925584
model.safetensors: 100% 86.5M/86.5M [00:03<00:00, 26.1MB/s]
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
model.safetensors: 100% 46.8M/46.8M [00:00<00:00, 57.7MB/s]

=== TRAINING M30 ===
Epochs: 5 | batch_size: 32 | lr=2e-05 | head_lr=0.0003
/content/vaipe-contextual-pill-recognition/train_m30_hard_error_finetune.py:776: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=amp)

Epoch [1/5] | backbone_trainable=False
/content/vaipe-contextual-pill-recognition/train_m30_hard_error_finetune.py:525: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=amp):
  step 00100/00725 | loss=3.3823 | elapsed=1.8 min
  step 00200/00725 | loss=2.8490 | elapsed=3.5 min
  step 00300/00725 | loss=2.4679 | elapsed=5.1 min
  step 00400/00725 | loss=2.1941 | elapsed=6.7 min
  step 00500/00725 | loss=1.9816 | elapsed=8.4 min
  step 00600/00725 | loss=1.8234 | elapsed=10.0 min
  step 00700/00725 | loss=1.6901 | elapsed=11.7 min
/content/vaipe-contextual-pill-recognition/train_m30_hard_error_finetune.py:569: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=amp):
Train Loss: 1.6622 | Train Acc: 0.4681 | Train Macro F1 Present: 0.4420
Val   Loss: 2.8709 | Val   Acc: 0.4906 | Val   Macro F1 Present: 0.3440 | Val Macro F1 All: 0.2835
Saved new best: /content/drive/MyDrive/model/M30_hard_error_finetune/run_v1/m30_best.pth
/content/vaipe-contextual-pill-recognition/train_m30_hard_error_finetune.py:776: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=amp)

Epoch [2/5] | backbone_trainable=True
/content/vaipe-contextual-pill-recognition/train_m30_hard_error_finetune.py:525: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=amp):
  step 00100/00725 | loss=0.7838 | elapsed=2.4 min
  step 00200/00725 | loss=0.7303 | elapsed=4.1 min
  step 00300/00725 | loss=0.6955 | elapsed=5.8 min
  step 00400/00725 | loss=0.6553 | elapsed=7.6 min
  step 00500/00725 | loss=0.6227 | elapsed=9.3 min
  step 00600/00725 | loss=0.6006 | elapsed=11.1 min
  step 00700/00725 | loss=0.5788 | elapsed=12.9 min
/content/vaipe-contextual-pill-recognition/train_m30_hard_error_finetune.py:569: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=amp):
Train Loss: 0.5741 | Train Acc: 0.8253 | Train Macro F1 Present: 0.8371
Val   Loss: 2.5746 | Val   Acc: 0.5836 | Val   Macro F1 Present: 0.4508 | Val Macro F1 All: 0.3715
Saved new best: /content/drive/MyDrive/model/M30_hard_error_finetune/run_v1/m30_best.pth
/content/vaipe-contextual-pill-recognition/train_m30_hard_error_finetune.py:776: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=amp)

Epoch [3/5] | backbone_trainable=True
/content/vaipe-contextual-pill-recognition/train_m30_hard_error_finetune.py:525: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=amp):
  step 00100/00725 | loss=0.4363 | elapsed=1.9 min
  step 00200/00725 | loss=0.4176 | elapsed=3.7 min
  step 00300/00725 | loss=0.4099 | elapsed=5.4 min
  step 00400/00725 | loss=0.4047 | elapsed=7.2 min
  step 00500/00725 | loss=0.3953 | elapsed=9.0 min
  step 00600/00725 | loss=0.3919 | elapsed=10.7 min
  step 00700/00725 | loss=0.3867 | elapsed=12.5 min
/content/vaipe-contextual-pill-recognition/train_m30_hard_error_finetune.py:569: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=amp):
Train Loss: 0.3853 | Train Acc: 0.9187 | Train Macro F1 Present: 0.9260
Val   Loss: 2.5358 | Val   Acc: 0.5975 | Val   Macro F1 Present: 0.4736 | Val Macro F1 All: 0.3903
Saved new best: /content/drive/MyDrive/model/M30_hard_error_finetune/run_v1/m30_best.pth
/content/vaipe-contextual-pill-recognition/train_m30_hard_error_finetune.py:776: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=amp)

Epoch [4/5] | backbone_trainable=True
/content/vaipe-contextual-pill-recognition/train_m30_hard_error_finetune.py:525: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=amp):
  step 00100/00725 | loss=0.3429 | elapsed=1.9 min
  step 00200/00725 | loss=0.3395 | elapsed=3.7 min
  step 00300/00725 | loss=0.3382 | elapsed=5.5 min
  step 00400/00725 | loss=0.3360 | elapsed=7.3 min
  step 00500/00725 | loss=0.3335 | elapsed=9.0 min
  step 00600/00725 | loss=0.3287 | elapsed=10.8 min
  step 00700/00725 | loss=0.3266 | elapsed=12.5 min
/content/vaipe-contextual-pill-recognition/train_m30_hard_error_finetune.py:569: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=amp):
Train Loss: 0.3261 | Train Acc: 0.9506 | Train Macro F1 Present: 0.9599
Val   Loss: 2.4698 | Val   Acc: 0.6154 | Val   Macro F1 Present: 0.4741 | Val Macro F1 All: 0.3907
Saved new best: /content/drive/MyDrive/model/M30_hard_error_finetune/run_v1/m30_best.pth
/content/vaipe-contextual-pill-recognition/train_m30_hard_error_finetune.py:776: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler(enabled=amp)

Epoch [5/5] | backbone_trainable=True
/content/vaipe-contextual-pill-recognition/train_m30_hard_error_finetune.py:525: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=amp):
  step 00100/00725 | loss=0.3097 | elapsed=1.9 min
  step 00200/00725 | loss=0.3154 | elapsed=3.6 min
  step 00300/00725 | loss=0.3089 | elapsed=5.3 min
  step 00400/00725 | loss=0.3085 | elapsed=7.1 min
  step 00500/00725 | loss=0.3064 | elapsed=8.8 min
  step 00600/00725 | loss=0.3030 | elapsed=10.6 min
  step 00700/00725 | loss=0.3004 | elapsed=12.4 min
/content/vaipe-contextual-pill-recognition/train_m30_hard_error_finetune.py:569: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=amp):
Train Loss: 0.3000 | Train Acc: 0.9650 | Train Macro F1 Present: 0.9713
Val   Loss: 2.4469 | Val   Acc: 0.6307 | Val   Macro F1 Present: 0.4897 | Val Macro F1 All: 0.4036
Saved new best: /content/drive/MyDrive/model/M30_hard_error_finetune/run_v1/m30_best.pth

Best epoch by val macro_f1_present: 5 | score=0.489745
Traceback (most recent call last):
  File "/content/vaipe-contextual-pill-recognition/train_m30_hard_error_finetune.py", line 862, in <module>
    main()
  File "/content/vaipe-contextual-pill-recognition/train_m30_hard_error_finetune.py", line 832, in main
    ckpt = torch.load(best_path, map_location=device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/serialization.py", line 1548, in load
    raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
_pickle.UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, do those steps only if you trust the source of the checkpoint.
	(1) In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL numpy._core.multiarray._reconstruct was not an allowed global by default. Please use `torch.serialization.add_safe_globals([numpy._core.multiarray._reconstruct])` or the `torch.serialization.safe_globals([numpy._core.multiarray._reconstruct])` context manager to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.

In [8]:
%cd /content/vaipe-contextual-pill-recognition

!python train_m30_hard_error_finetune.py \
  --train_metadata /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_train_hard_metadata.csv \
  --val_metadata /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_val_hard_metadata.csv \
  --test_metadata /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_test_hard_metadata.csv \
  --m26_dir /content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1 \
  --output_dir /content/drive/MyDrive/model/M30_hard_error_finetune/run_v1 \
  --num_classes 108 \
  --true_col mapped_label \
  --epochs 0

/content/vaipe-contextual-pill-recognition
=== M30 HARD-ERROR CLASS-BALANCED FINETUNE ===
Train metadata: /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_train_hard_metadata.csv
Val metadata  : /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_val_hard_metadata.csv
Test metadata : /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_test_hard_metadata.csv
M26 dir       : /content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1
Output dir    : /content/drive/MyDrive/model/M30_hard_error_finetune/run_v1
Num classes   : 108
Pill backbone : tf_efficientnetv2_s.in21k_ft_in1k
Rx backbone   : resnet18.a1_in1k
Using device  : cuda | AMP: True

=== DETECTED COLUMNS ===
{
  "train_label_col": "mapped_label",
  "val_label_col": "mapped_label",
  "test_label_col": "mapped_label",
  "pill_col": "pill_crop_path",
  "prescription_col": "prescription_image_path",
  "context_col": "context_labels"
}

=== ROW COUNTS ===
Train rows: 23189
Val rows  : 4974
Test rows : 4550
Train pill images: existing in first 2000 rows = 2000/2000
Train prescription images: existing in first 2000 rows = 2000/2000

=== BASE M26 METRICS ===
split model  accuracy  macro_f1_present  macro_f1_all  weighted_f1
  val   M26  0.782871          0.601019      0.495284     0.771756
 test   M26  0.773187          0.555209      0.421548     0.762100

=== TOP 30 M30 HARD/RARE CLASS WEIGHTS ===
 class_id  train_support  m26_val_support  m26_val_recall  m26_val_f1  freq_weight  hard_weight  final_weight
       77              6                2        0.000000    0.000000     3.037840     4.000000      6.000000
       25              1                0        0.000000    0.000000     7.151259     1.000000      4.162289
       49              1                0        0.000000    0.000000     7.151259     1.000000      4.162289
       42             20                5        0.000000    0.000000     1.754349     4.000000      4.084376
       39             24                6        0.000000    0.000000     1.618920     4.000000      3.769078
       78             37                7        0.000000    0.000000     1.342780     4.000000      3.126184
       13              2                0        0.000000    0.000000     5.115282     1.000000      2.977278
      105             45               10        0.000000    0.000000     1.236232     4.000000      2.878127
       62             63               16        0.000000    0.000000     1.075776     4.000000      2.504562
       80             64               12        0.000000    0.000000     1.068907     4.000000      2.488570
       23             70               20        0.000000    0.000000     1.030834     4.000000      2.399930
       47             73               17        0.000000    0.000000     1.013583     4.000000      2.359767
       18             84                8        0.000000    0.000000     0.958445     4.000000      2.231396
       67             90               12        0.000000    0.000000     0.932727     4.000000      2.171522
       32              4                0        0.000000    0.000000     3.675629     1.000000      2.139348
       95             99               21        0.000000    0.000000     0.898628     4.000000      2.092135
       88              6                1        1.000000    1.000000     3.037840     1.000000      1.768132
       66              8                0        0.000000    0.000000     2.657641     1.000000      1.546843
      102              8                0        0.000000    0.000000     2.657641     1.000000      1.546843
       76             12                4        1.000000    1.000000     2.206656     1.000000      1.284353
       87            121               26        0.038462    0.064516     0.831933     2.631336      1.274132
       21             13                3        0.333333    0.500000     2.127932     1.000000      1.238533
       86             16                0        0.000000    0.000000     1.937815     1.000000      1.127878
       58             18                9        1.000000    1.000000     1.838427     1.000000      1.070031
       22             20                7        1.000000    1.000000     1.754349     1.000000      1.021094
       53             21                0        0.000000    0.000000     1.716889     1.000000      0.999291
       11             22                8        0.625000    0.769231     1.682013     1.000000      0.978992
      100             22                6        0.500000    0.666667     1.682013     1.000000      0.978992
       14             87               18        0.222222    0.228571     0.945253     1.693878      0.931923
      101             25                8        0.500000    0.666667     1.590252     1.000000      0.925584

=== TRAINING M30 ===
Epochs: 0 | batch_size: 32 | lr=2e-05 | head_lr=0.0003

Best epoch by val macro_f1_present: -1 | score=-1000000000.000000
Traceback (most recent call last):
  File "/content/vaipe-contextual-pill-recognition/train_m30_hard_error_finetune.py", line 862, in <module>
    main()
  File "/content/vaipe-contextual-pill-recognition/train_m30_hard_error_finetune.py", line 832, in main
    ckpt = torch.load(best_path, map_location=device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/serialization.py", line 1548, in load
    raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
_pickle.UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, do those steps only if you trust the source of the checkpoint.
	(1) In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL numpy._core.multiarray._reconstruct was not an allowed global by default. Please use `torch.serialization.add_safe_globals([numpy._core.multiarray._reconstruct])` or the `torch.serialization.safe_globals([numpy._core.multiarray._reconstruct])` context manager to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.

In [9]:
%cd /content/vaipe-contextual-pill-recognition

!sed -i 's/torch.load(best_path, map_location=device)/torch.load(best_path, map_location=device, weights_only=False)/g' train_m30_hard_error_finetune.py

/content/vaipe-contextual-pill-recognition

In [10]:
!grep -n "torch.load(best_path" train_m30_hard_error_finetune.py

832:    ckpt = torch.load(best_path, map_location=device, weights_only=False)

In [11]:
%cd /content/vaipe-contextual-pill-recognition

!python train_m30_hard_error_finetune.py \
  --train_metadata /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_train_hard_metadata.csv \
  --val_metadata /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_val_hard_metadata.csv \
  --test_metadata /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_test_hard_metadata.csv \
  --m26_dir /content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1 \
  --output_dir /content/drive/MyDrive/model/M30_hard_error_finetune/run_v1 \
  --num_classes 108 \
  --true_col mapped_label \
  --epochs 0

/content/vaipe-contextual-pill-recognition
=== M30 HARD-ERROR CLASS-BALANCED FINETUNE ===
Train metadata: /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_train_hard_metadata.csv
Val metadata  : /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_val_hard_metadata.csv
Test metadata : /content/drive/MyDrive/model/M24_metric_learning/hard_pair_metadata/m24_test_hard_metadata.csv
M26 dir       : /content/drive/MyDrive/model/M26_calibrated_context_ensemble/run_v1
Output dir    : /content/drive/MyDrive/model/M30_hard_error_finetune/run_v1
Num classes   : 108
Pill backbone : tf_efficientnetv2_s.in21k_ft_in1k
Rx backbone   : resnet18.a1_in1k
Using device  : cuda | AMP: True

=== DETECTED COLUMNS ===
{
  "train_label_col": "mapped_label",
  "val_label_col": "mapped_label",
  "test_label_col": "mapped_label",
  "pill_col": "pill_crop_path",
  "prescription_col": "prescription_image_path",
  "context_col": "context_labels"
}

=== ROW COUNTS ===
Train rows: 23189
Val rows  : 4974
Test rows : 4550
Train pill images: existing in first 2000 rows = 2000/2000
Train prescription images: existing in first 2000 rows = 2000/2000

=== BASE M26 METRICS ===
split model  accuracy  macro_f1_present  macro_f1_all  weighted_f1
  val   M26  0.782871          0.601019      0.495284     0.771756
 test   M26  0.773187          0.555209      0.421548     0.762100

=== TOP 30 M30 HARD/RARE CLASS WEIGHTS ===
 class_id  train_support  m26_val_support  m26_val_recall  m26_val_f1  freq_weight  hard_weight  final_weight
       77              6                2        0.000000    0.000000     3.037840     4.000000      6.000000
       25              1                0        0.000000    0.000000     7.151259     1.000000      4.162289
       49              1                0        0.000000    0.000000     7.151259     1.000000      4.162289
       42             20                5        0.000000    0.000000     1.754349     4.000000      4.084376
       39             24                6        0.000000    0.000000     1.618920     4.000000      3.769078
       78             37                7        0.000000    0.000000     1.342780     4.000000      3.126184
       13              2                0        0.000000    0.000000     5.115282     1.000000      2.977278
      105             45               10        0.000000    0.000000     1.236232     4.000000      2.878127
       62             63               16        0.000000    0.000000     1.075776     4.000000      2.504562
       80             64               12        0.000000    0.000000     1.068907     4.000000      2.488570
       23             70               20        0.000000    0.000000     1.030834     4.000000      2.399930
       47             73               17        0.000000    0.000000     1.013583     4.000000      2.359767
       18             84                8        0.000000    0.000000     0.958445     4.000000      2.231396
       67             90               12        0.000000    0.000000     0.932727     4.000000      2.171522
       32              4                0        0.000000    0.000000     3.675629     1.000000      2.139348
       95             99               21        0.000000    0.000000     0.898628     4.000000      2.092135
       88              6                1        1.000000    1.000000     3.037840     1.000000      1.768132
       66              8                0        0.000000    0.000000     2.657641     1.000000      1.546843
      102              8                0        0.000000    0.000000     2.657641     1.000000      1.546843
       76             12                4        1.000000    1.000000     2.206656     1.000000      1.284353
       87            121               26        0.038462    0.064516     0.831933     2.631336      1.274132
       21             13                3        0.333333    0.500000     2.127932     1.000000      1.238533
       86             16                0        0.000000    0.000000     1.937815     1.000000      1.127878
       58             18                9        1.000000    1.000000     1.838427     1.000000      1.070031
       22             20                7        1.000000    1.000000     1.754349     1.000000      1.021094
       53             21                0        0.000000    0.000000     1.716889     1.000000      0.999291
       11             22                8        0.625000    0.769231     1.682013     1.000000      0.978992
      100             22                6        0.500000    0.666667     1.682013     1.000000      0.978992
       14             87               18        0.222222    0.228571     0.945253     1.693878      0.931923
      101             25                8        0.500000    0.666667     1.590252     1.000000      0.925584
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

=== TRAINING M30 ===
Epochs: 0 | batch_size: 32 | lr=2e-05 | head_lr=0.0003

Best epoch by val macro_f1_present: -1 | score=-1000000000.000000

=== FINAL EVALUATION WITH BEST M30 CHECKPOINT ===
/content/vaipe-contextual-pill-recognition/train_m30_hard_error_finetune.py:569: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=amp):
/content/vaipe-contextual-pill-recognition/train_m30_hard_error_finetune.py:569: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=amp):
split model  accuracy  macro_f1_present  macro_f1_all  weighted_f1
  val   M30  0.630478          0.489740      0.403582     0.638938
 test   M30  0.648352          0.460907      0.349948     0.665573

Saved files:
/content/drive/MyDrive/model/M30_hard_error_finetune/run_v1/m30_config.json
/content/drive/MyDrive/model/M30_hard_error_finetune/run_v1/m30_class_weights.csv
/content/drive/MyDrive/model/M30_hard_error_finetune/run_v1/m30_train_log.csv
/content/drive/MyDrive/model/M30_hard_error_finetune/run_v1/m30_best.pth
/content/drive/MyDrive/model/M30_hard_error_finetune/run_v1/m30_last.pth
/content/drive/MyDrive/model/M30_hard_error_finetune/run_v1/val_m30_predictions.csv
/content/drive/MyDrive/model/M30_hard_error_finetune/run_v1/val_m30_probs.npy
/content/drive/MyDrive/model/M30_hard_error_finetune/run_v1/val_m30_metrics.json
/content/drive/MyDrive/model/M30_hard_error_finetune/run_v1/test_m30_predictions.csv
/content/drive/MyDrive/model/M30_hard_error_finetune/run_v1/test_m30_probs.npy
/content/drive/MyDrive/model/M30_hard_error_finetune/run_v1/test_m30_metrics.json
/content/drive/MyDrive/model/M30_hard_error_finetune/run_v1/m30_summary.csv

Done.